### ISSUE TITLE
curl of jbang not able to download java on debian image

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1018]
```bash
docker run -t debian
apt-get update
apt-get install curl
curl -Ls https://sh.jbang.dev | bash -s - app setup
```

fails with error it cannot download java ...I think we shuold be able to.

**Comment by quintesse** [comment]
This is because the server returns 406 - Not Acceptable

**Comment by quintesse** [comment]
Same thing happens when I run it on my local system, so I'm guessing the service is broken.

**Comment by quintesse** [comment]
Aha, the 406 is because the _actual_reason is a 404 but the server says: "I want to send you a HTML with the error message but I'm not allowed to send you a text/html doc"

**Comment by quintesse** [comment]
Ok, found the problem. You probably copied & pasted the URL from the Windows cmd/ps1 files @maxandersen ? Becuase it's asking for the ZIP file, not the TAR_GZ

**Comment by quintesse** [comment]
Perhaps we could add a test for this? (Wasn't there a problem with AOJ refusing downloads from GitHub actions?)

**Comment by maxandersen** [comment]
I think that has been fixed so we can add tests back.
