### ISSUE TITLE
jbang edit suggests incorrect command when template renames output file

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#1019]
With the following template info:

`
    "junit4b": {
      "file-refs": {
        "{basename}Test.java": "templates/junit4b.java.qute"
      },
      "description": "Basic template for JUnit4 tests"
    }
`

And the init command:

` jbang init --fresh --template=junit4b@jbangdev_local Script.java`

The output is:

[jbang] File initialized. You can now run it with 'jbang Script.java' or edit it using 'jbang edit --open=[editor] Script.java' where [editor] is your editor or IDE, e.g. 'netbeans'

which is puzzling because the created file is ScriptTest.java.

**Comment by grumpyf0x48** [comment]
We could take the first rendered file into account, which works here, but what if the template renders several files ?

**Comment by quintesse** [comment]
The best solution would be to use the one that has `{basename}` in its target name, because that is the one that will have the name the user provided. (If no such file should exist should perhaps just not show the edit message)

**Comment by grumpyf0x48** [comment]
Yes but you can have several files using `{basename}`. Most of the time it won't happen, but you can do it.

**Comment by maxandersen** [comment]
Pick the first one in that case.

**Comment by maxandersen** [comment]
fixed in #1020
