### ISSUE TITLE
Startup scripts are no longer present in the distribution

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#1051]
With 0.82 version, it seems there is no jbang nor jbang.cmd script present in jbang.zip or jbang.tar:

`
pyfourmond@ron-wood:~$ unzip -l Téléchargements/jbang-0.82.0.zip 
Archive:  Téléchargements/jbang-0.82.0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  1980-02-01 00:00   jbang-0.82.0/
        0  1980-02-01 00:00   jbang-0.82.0/bin/
  6216711  1980-02-01 00:00   jbang-0.82.0/bin/jbang.jar
        0  1980-02-01 00:00   jbang-0.82.0/tmp/
---------                     -------
  6216711                     4 files
pyfourmond@ron-wood:~$ tar -tvf Téléchargements/jbang-0.82.0.tar
drwxr-xr-x 0/0               0 1970-01-02 01:00 jbang-0.82.0/
drwxr-xr-x 0/0               0 1970-01-02 01:00 jbang-0.82.0/bin/
-rw-r--r-- 0/0         6216711 1970-01-02 01:00 jbang-0.82.0/bin/jbang.jar
drwxr-xr-x 0/0               0 1970-01-02 01:00 jbang-0.82.0/tmp/
`
How do i start JBang ?

**Comment by maxandersen** [comment]
please use 0.82.1! 0.82 had a bug.
