### ISSUE TITLE
Not compiling in vscode in windows

### ISSUE THREAD

**Issue by vascoosx** [jbangdev/jbang#1073]
Hi,

I am running jbang v0.81.2 and recently had an error while trying to run in windows 10.
The error says "Main method not found in the file, please define the main method as: public static void main(String[] args)".

I have attempted to rebuild the workspace with "alt-shift B" (option Full) but the problem persisted. When I deleted the .class file in the "bin" directory it was not created again after attempting to rebuild with "alt-shift B". Therefore I concluded that it is not recompiling.

I also attempted to recreate everything with `jbang edit --fresh --no-open ...` but it gives me the same directory. So I'm not sure this is really fresh.

**Comment by quintesse** [comment]
First, if you really want to be sure you get a new/fresh directory you can actually clear the project cache by running `jbang cache clear --project`, but that will remove all projects so make sure you don't have any open in any IDEs. But you can also manually delete the project folder yourself if you want.

Second, if your IDE is compiling or not doesn't affect JBang, it does its own compilation, `jbang yourfile.java` should either just work or give you a compile error. If it doesn't seem to pick up the changes you've made to the file you _can_ try running with the `--fresh` option, but that really shouldn't be necessary.

And finally, given the error are you sure you have a proper `main()` method in your code?

**Comment by vascoosx** [comment]
Thank you for your advice. The code was running in the beginning but it stopped running after I've changed some things but I didn't delete the `main()` method.

I haven't deleted the directory in order to be able to investigate it.

I was able to create the jar file. I will see if the jar file runs as expected to check that the code doesn't have any issue.
