### ISSUE TITLE
curl install on Mac appears to be broken

### ISSUE THREAD

**Issue by murphye** [jbangdev/jbang#1075]
```
➜  Desktop curl -Ls https://sh.jbang.dev | bash -s - app setup
➜  Desktop 
➜  Desktop jbang --version                                    
zsh: command not found: jbang
```

When running this, it sits there for a moment, and nothing happens. 

Using Mac OS 11.5.2

**Comment by maxandersen** [comment]
weird - it works for me:

```
curl -Ls https://sh.jbang.dev | bash -s - app setup
Downloading JBang...
Installing JBang...
[jbang] JBang environment is already set up.
```

can you run it like this: `curl -v -Ls https://sh.jbang.dev | bash -x -s - --verbose app setup` and attach the output - then we can see in detail what happens.

**Comment by murphye** [comment]
```
curl -v -Ls https://sh.jbang.dev | bash -x -s - --verbose app setup
*   Trying 192.168.30.2...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.30.2 port 443 failed: Operation timed out
* Failed to connect to sh.jbang.dev port 443: Operation timed out
* Closing connection 0
```

```
dig sh.jbang.dev

; <<>> DiG 9.10.6 <<>> sh.jbang.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40640
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;sh.jbang.dev.			IN	A

;; ANSWER SECTION:
sh.jbang.dev.		300	IN	A	172.67.73.159
sh.jbang.dev.		300	IN	A	104.26.10.211
sh.jbang.dev.		300	IN	A	104.26.11.211

;; Query time: 72 msec
;; SERVER: 192.168.86.1#53(192.168.86.1)
;; WHEN: Sat Nov 13 08:30:16 PST 2021
;; MSG SIZE  rcvd: 89
```

Appears to be trying to contact `192.168.30.2` even though `sh.jbang.dev` has 3 A records pointing to an actual endpoint.

Is this `192.168.30.2` from your dev/test environment?

**Comment by maxandersen** [comment]
No. Nothing I have. Weird.

**Comment by murphye** [comment]
I checked my `/etc/hosts` there is nothing there that should be causing this.

**Comment by murphye** [comment]
When I put `https://sh.jbang.dev` into my web browser, I get a response, with the script as to be expected.

But when I use curl, for some darn reason, it points to the wrong IP.

```
curl -v https://sh.jbang.dev
*   Trying 192.168.30.2...
* TCP_NODELAY set
```

**Comment by murphye** [comment]
I am closing... this is an environmental issue on my end. Any `.dev` is doing this... not a problem for JBang.

**Comment by maxandersen** [comment]
This is all handled by cloudflare so I'm a bit surprised. 

Can you clear your DNS cache and try again ? https://mackeeper.com/blog/flush-dns-cache-on-mac/
