### ISSUE TITLE
Support a syntax that resolves to RELEASE or SNAPSHOT in the DEPS syntax

### ISSUE THREAD

**Issue by lukaseder** [jbangdev/jbang#1086]
**Is your feature request related to a problem? Please describe.**

I have files like these in the catalog:
https://github.com/jOOQ/jbang-catalog/blob/main/parserpro.java

It contains:

```
//DEPS org.jooq.pro:jooq:${jooq.version:RELEASE}
```

The `RELEASE` default only resolves to the latest non-snapshot version. If someone has a snapshot version in their repository, it should be possible to auto-resolve to that as well.

**Describe the solution you'd like**

It may well be that there's already a syntax that does this, but I don't know it? Something like:

```
//DEPS org.jooq.pro:jooq:${jooq.version:RELEASE-OR-SNAPSHOT}
```

There's probably a better, more Maven-idiomatic notation for that?

**Comment by lukaseder** [comment]
The workaround with the above syntax is of course to pass the `-Djooq.version=...` explicitly

**Comment by quintesse** [comment]
I'm not the expert on this part of the code, so I'll leave the final word to @maxandersen , _but_ I think that if Maven itself can't do it, then neither can we. (At least not without a heavy performance penalty where we would basically resolve multiple times, each time trying with different values and see which one terminates successfully. Perhaps doable if you have only one or two of those but it might quickly explode if you have more dependencies like that).

**Comment by maxandersen** [comment]
not at computer right now but try LATEST.

**Comment by lukaseder** [comment]
> not at computer right now but try LATEST.

Yeah duh! Thanks 👌

**Comment by quintesse** [comment]
Ha! Well as you can see I know nothing about Maven 😅
