### ISSUE TITLE
jbang info classpath is broken for scripts that have sources

### ISSUE THREAD

**Issue by JakobFels** [jbangdev/jbang#1096]
Starting with 0.81.0, running `jbang info classpath <scriptfile>` fails with the error `Cannot invoke "dev.jbang.source.RunContext.getContextProperties()" because "ctx" is null`.

I traced down the error to this commit: https://github.com/jbangdev/jbang/commit/3ac55619e0d4a1e297e9fe0254e8876bff7a193c#diff-307e42ab9a41d6b838b9a6827affffe894175baccea0a83f712d9c6d3b27b573

From my understanding, if the inspected script defines //SOURCES, then `ScriptInfo` is instantiated with a `ctx` set to null.
(see https://github.com/jbangdev/jbang/blob/bd8f4223575963dbabe924b53d6c3e6fbcbcb846/src/main/java/dev/jbang/cli/Info.java#L101)
This in turn will fail the lookup.

**Comment by quintesse** [comment]
Good catch @JakobFels , thanks!

**Comment by quintesse** [comment]
This should now be fixed... once I can get it to pass CI.

**Comment by JakobFels** [comment]
Thank you for the quick fix

**Comment by maxandersen** [comment]
@all-contributors please add @JakobFels  for bug
