### ISSUE TITLE
"Could not locate unique class. Found 0 candidates." when the first class does have main method.

### ISSUE THREAD

**Issue by ge0ffrey** [jbangdev/jbang#1099]
To reproduce, take this gist:
  https://gist.github.com/ge0ffrey/9f4c558347f128790e774223f4a63fb3
And run it on:
  https://www.jdoodle.com/try-jbang

**Comment by quintesse** [comment]
I've created a PR that should fix this problem: https://github.com/jbangdev/jbang/pull/1104

It's basically a combination of problems:

- you don't have a public class
- you have several non-public classes
- there's no concept of a filename on jdoodle

These things together make it so JBang isn't able to figure out in which class the `main()` method is located.
I've made it so it looks a bit harder.

Btw @maxandersen, how does JDoodle run the script? As if it comes from stdin?

**Comment by maxandersen** [comment]
@all-contributors please add @ge0ffrey  for bug
