### ISSUE TITLE
Groovy support?

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#1113]
Any plan to support Groovy alike Kotlin?    `jbang hello.groovy` 

```
//GROOVY 3.0.9

println("Hello Groovy")
```

I have some Ops scripts written by Groovy, and I would like to run these groovy scripts with jbang support.  Auto JDK, alias, jbang-catalog.json features are very useful to run Groovy scripts.

**Comment by maxandersen** [comment]
I'm not totally against it but would need someone to contribute it and iterate on it so we can close the gaps.
