### ISSUE TITLE
How about run Java code snippets in README.md? 

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#1138]
Most projects contains code snippets in README.md,   how about run these snippets from jbang?  Extract class name and run with `jbang ClassName` ? 

If JBang support this feature, I think most Java projects will adopt jbang style to write Java snippets.  :)   It's easy for developers to try products and services.

**Comment by maxandersen** [comment]
You mean like suggested in https://github.com/jbangdev/jbang/issues/904 ?

**Comment by linux-china** [comment]
yes. it's correct.   Sorry for duplication.

**Comment by maxandersen** [comment]
no need to be sorry for duplication - good to hear others like it.

About snippet the idea is to keep it simple and just look for ```java blocks.

**Comment by linux-china** [comment]
Directive completion is ready for code block in markdown.
 
<img width="458" alt="Screen Shot 2021-12-21 at 2 48 11 PM" src="https://user-images.githubusercontent.com/46711/147007627-210bf544-14e6-4f0d-9902-b6c0585f610c.png">

**Comment by maxandersen** [comment]
HA! in a few minutes I'll have a PR for .md support.

**Comment by maxandersen** [comment]
give this a try: https://github.com/jbangdev/jbang/pull/1139

**Comment by maxandersen** [comment]
merged to main

**Comment by maxandersen** [comment]
@all-contributors please add @linux-china  for code,ideas

**Comment by maxandersen** [comment]
@all-contributors please add @linux-china for ideas

@all-contributors please add @linux-china for code

**Comment by maxandersen** [comment]
@all-contributors please add @linux-china for ideas

**Comment by maxandersen** [comment]
@all-contributors please add @linux-china for code
