### ISSUE TITLE
NO_COLOR support

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#1168]
JBang IntelliJ IDEA plugin will call jbang cli to get some information, such as. `jbang template list`.  It's easy to parse output with NO_COLOR support.   https://no-color.org/

**Comment by maxandersen** [comment]
Picocli already does this by default. 

Do you see a case where jbang does not honor it ?

Also we can add a more machine friendly output if need be.

**Comment by linux-china** [comment]
My fault. it works `NO_COLOR=true jbang template list`  :)
