### ISSUE TITLE
AWS Lambda with JBang (and Quarkus) is not working properly

### ISSUE THREAD

**Issue by nandorholozsnyak** [jbangdev/jbang#1175]
### Motivation

I have recently started using AWS Lambda and experimenting with the possibilities to run Java code with them. 
I was attending projects with a few functions written in Python, I liked it, but with JBang I think me and other Java developers could do good things with Lambda as well.  
The goal would be to not create a lot of Maven/Gradle projects or overpopulating one Maven/Gradle project with tons of functions, with Quarkus I think it could be done with one project but with JBang I think it would be on another level. In our scenarios a lambda function is a "folder" with only one Python file, I would really like the idea if it could happen with our Java "script" files as well.
Of course, I would not like to focus only on AWS Lambda, but I'm having problems with that one right now.

#### Problems
Use this file as an example:
```java

///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus:quarkus-bom:2.6.1.Final@pom
//DEPS io.quarkus:quarkus-amazon-lambda
//JAVAC_OPTIONS -parameters
//JAVA_OPTIONS -Djava.util.logging.manager=org.jboss.logmanager.LogManager

import org.jboss.logging.Logger;

public class AwsLambda implements RequestHandler<Object, Object> {

    public static final Logger LOG = Logger.getLogger("AwsLambdaLogging");

    @Override
    public Object handleRequest(Object o, Context context) {
        LOG.info("Incoming object:" + o);
        return o;
    }
}

```
After calling the `jbang export portable AwsLambda.java` command JBang is going to create the `.jar` file and a folder called `libs`.
When this generated jar file is going to be uploaded as a Java function to AWS Lambda (with the handler class: `io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler`) on execution the following error is going to happen:
```json
{
  "errorMessage": "Class not found: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler",
  "errorType": "java.lang.ClassNotFoundException"
}
```

The same would happen if the example would be using **_Funq_**, but then it would not be able to find this class: `io.quarkus.funqy.lambda.FunqyStreamHandler`

The problem is that the final `.jar` files does not contain the `libs` folder in itself, and if it would then it would not work as well because AWS Lambda requires this folder to be named `lib`.

Check out `Check for class file issues` section on: https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-java-classnotfound/

> - It's located in /lib or the root directory.
> - Its location is specified in a Java CLASSPATH environment variable. 

#### Methods I tried to overcome the problem without "hacking" the .jar file but did not work
- Setting external jar directory with the `JAVA_TOOL_OPTIONS` env variable to `-Djava.ext.dirs=libs` -> Won't work:
    - > -Djava.ext.dirs=libs is not supported.  Use -classpath instead.
- Setting the `CLASSPATH` variable to `libs/*` (or whatever you think could work) in the AWS function -> Won't work because the MANIFEST.MF file contains the Class-Path header and the JVM will ignore the wildcard (https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html) 
    - > The CLASSPATH environment variable is not treated any differently from the -classpath or -cp options. Wild cards are honored in all of these cases. However, class path wild cards are not honored in the Class-Path jar-manifest header.

#### Possible solutions or/and workarounds
- After calling `jbang export portable xy.java` rename the `libs` folder to `lib` and update the final jar with `jar uf xy.jar lib/` and upload that to AWS.
- Maybe an uber-jar with all dependencies (.class files) - I'm not sure it would work, just an idea.
- Like Quarkus if the `quarkus-amazon-lambda` or `quarkus-funqy-amazon-lambda` is in the project it will create a so called `function.zip` file which would include the `lib` folder, but this requires to rename the `libs` folder to `lib` first. 

### More ideas
Have templates for the following scenarios:
- Quarkus AWS Lambda/Azure/Google Cloud
  - Simple template which would create an `InputObject` and an `OutputObject` as well and depending on the "trigger" type (SQS, S3) prepare the `InputObject` with the required fields.
- Quarkus AWS Lambda/Azure/Google Cloud Funq Lambda

**JBang version**
❯ jbang version          
0.85.1

**Comment by maxandersen** [comment]
Is it enough to just rename libs to lib and it just Works on Az ?

**Comment by maxandersen** [comment]
Happy new year - now at laptop and New Years Eve is over I can comment better :)

> * Quarkus AWS Lambda/Azure/Google Cloud
>   
>   * Simple template which would create an `InputObject` and an `OutputObject` as well and depending on the "trigger" type (SQS, S3) prepare the `InputObject` with the required fields.
> 
> * Quarkus AWS Lambda/Azure/Google Cloud Funq Lambda

These ideas all makes sense to me and its something you can just make happen @nandorholozsnyak - its what jbang catalogs was made for. Anyone can make a jbang-catalog repo and add good getting started examples. I would love to see such a "amazon function with jbang" catalog. Would be great!

With respect to how to run/build a jar on amazon I just know the basics - I always get frustrated with all the steps amazon wants users to do :) if renaming libs to lib helps here I'm fine doing that - also since I realized src isn't srcs nor is bin bins. 

So for that part alone I'll merge #1176 as it is the right thing to do anyhow.

**Comment by maxandersen** [comment]
okey, after reading the amazon docs at https://docs.aws.amazon.com/lambda/latest/dg/java-package.html#java-package-gradle I think I understand how it works - and boy they suck at explaining it :)

Amazon literally just needs a zipped archive of classes and jars. For some reason they then explain how to do it with gradle using a zip task that will result  in  .zip file with .classes from your project AND a lib/ folder ....but then using maven does a a shaded jar which is NOT the same...but it is just then a archive of classes.

In both cases you end up with an archive (zip or jar) that when unzipped is "runnable".

What I don't get is why wouldn't it just work as is today adding the libs folder into the as if you take the exported jar today the jar actually refer to `libs/xyz.jar` which will be there if you do the `jar uf` trick ....does that for some reason not just works ?

**Comment by nandorholozsnyak** [comment]
> So for that part alone I'll merge #1176 as it is the right thi

Will do something like that. Should it be put into the official JBang repostiroy's jbang-catalog.xml or to a new repository?

**Comment by nandorholozsnyak** [comment]
> What I don't get is why wouldn't it just work as is today adding the libs folder into the as if you take the exported jar today the jar actually refer to `libs/xyz.jar` which will be there if you do the `jar uf` trick ....does that for some reason not just works ?

I was experimenting with the MANIFEST.MF file's Class-Path header, but I was just not understanding what is going on. As I wrote above the following requirements should happen: 

```
Check out Check for class file issues section on: https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-java-classnotfound/

> - It's located in /lib or the root directory.
```

So it is just some "strict" rule.

**Comment by maxandersen** [comment]
> > So for that part alone I'll merge #1176 as it is the right thi
> 
> 
> 
> Will do something like that. Should it be put into the official JBang repostiroy's jbang-catalog.xml or to a new repository? 

I suggest you put in a new repository. If something comes out that makes sense to have in main Jbang catalog we can move it over. idea is to have more specialized stuff in separate catalogs to not create "noise" for every user.

**Comment by nandorholozsnyak** [comment]
Should it be closed after the merge @maxandersen ? What do you think about the `--zip` flag for the export command? It was mentioned in the PR:
- https://github.com/jbangdev/jbang/pull/1176#issuecomment-1003636041
- https://github.com/jbangdev/jbang/pull/1176#issuecomment-1003637281

**Comment by nandorholozsnyak** [comment]
It was basically fixed with the rename.
