### ISSUE TITLE
Fails to find java on windows

### ISSUE THREAD

**Issue by blsouthr** [jbangdev/jbang#118]
Downloaded latest jbang 0.27 and added to PATH
Using cmd:
```console
C:\tmp>echo %JAVA_HOME%
C:\jdk8

C:\tmp>jbang.bat
'java' is not recognized as an internal or external command,
operable program or batch file.
```

Now switching to git bash:
```console
$ echo $JAVA_HOME
C:\jdk8
$ java -version
openjdk version "1.8.0_222"

$ jbang --init=cli hello.java
[jbang] File initialized. You can now run it with 'jbang hello.java' or edit it using 'code `jbang --edit hello.java

$ jbang hello.java
/c/tmp/jbang/bin/jbang: line 37: exec: C:jdk8binjava.exe: not found
```

**Comment by maxandersen** [comment]
> C:\tmp>jbang.bat
> 'java' is not recognized as an internal or external command,
> operable program or batch file.

for cmd.exe you need to have java in your path - it seems you don't ? 
we could improve this by making the `jbang.bat` better at looking up java_home. but for now just make sure, java is in ypour path.

> $ jbang hello.java
> /c/tmp/jbang/bin/jbang: line 37: exec: C:jdk8binjava.exe: not found

for git bash - here that does look like a bug - here it finds the java.exe in your java_home but as it detects you are on windows but doesn't know its a "bash" shell calling it returns a wrongly formatted string.

that needs a fix in jbang ;)

**Comment by maxandersen** [comment]
hmm -  i just tested with git bash and it worked for me ;/

what shell are you running exactly here ?

**Comment by blsouthr** [comment]
I'm using git bash shell (MINGW64, git version 2.22.0.windows.1) distributed with git installation for windows. About section of terminal window: mintty 3.0.1 (mintty.github.com)

You were right about cmd. after adding java to path, it worked

**Comment by maxandersen** [comment]
that is over a year old version of git bash - can you try update as I can't reproduce with latest git bash.

**Comment by maxandersen** [comment]
I've fixed the issue I can reproduce (not honoring JAVA_HOME if available) - you can try the latest build at https://github.com/jbangdev/jbang/runs/743873483?check_suite_focus=true

**Comment by blsouthr** [comment]
@manikmagar Updated git to 2.24.1.windows.2, same error. jbang: line 37: exec: C:jdk8binjava.exe: not found

**Comment by manikmagar** [comment]
> @manikmagar Updated git to 2.24.1.windows.2, same error. jbang: line 37: exec: C:jdk8binjava.exe: not found

@blsouthr I guess you meant to mention @maxandersen :)

**Comment by maxandersen** [comment]
> @manikmagar Updated git to 2.24.1.windows.2, same error. jbang: line 37: exec: C:jdk8binjava.exe: not found

how do you even get git bash to resolve windows paths ? :) any attempt I do it automatically convert paths to use / instead of \.

do you have any custom settings I need to activate to detect this situation?

**Comment by blsouthr** [comment]
@maxandersen I don't have any special settings and never had any problems with git shell so far. Could you maybe provide some isolated code for debugging?

**Comment by maxandersen** [comment]
i.e. in my git bash `echo $JAVA_HOME` gives me `C:\Users\max...` (notice the windows style path)

and doing `$JAVA_HOME/bin/java` just works for me.

Do you get same behavior ? 

looking at your error report its as if \'s are stripped out by your shell...

**Comment by blsouthr** [comment]
Yes, here is the output of my git bash shell:
```console
MINGW64 ~
$ echo $JAVA_HOME
C:\jdk8

MINGW64 ~
$ $JAVA_HOME/bin/java -version
openjdk version "1.8.0_222"
```

**Comment by blsouthr** [comment]
@maxandersen yes, jbang.bat would work and your fix is working. Thanks!

**Comment by maxandersen** [comment]
Thanks for verifying. I'll get official release out over the weekend
