### ISSUE TITLE
Support to resolve dependences with sources jar

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#1181]
Now jbang resolves dependency's jar to local repository, how about  to download sources jar when invoke  `jbang info tools HelloWorld.java` command?  These sources jars are very import for debugging during development.

**Comment by maxandersen** [comment]
Is there A case where ides can't figure that out in it's own?

**Comment by linux-china** [comment]
Now IntelliJ IDEA will call `mvn dependency:sources` to fetch sources jars, then relates jar and sources jar together. 

![Screen Shot 2022-01-04 at 6 10 21 PM](https://user-images.githubusercontent.com/46711/148149606-38ca4a7f-7361-46b5-9cfc-ca46fe507516.png)

**Comment by maxandersen** [comment]
Or gradle or use its own fetch sources, right?

So where is the case jbang fetching it is useful?

**Comment by linux-china** [comment]
Yes, Gradle will resolve sources jar automatically, but the storage is different with Maven local repository.   

![image](https://user-images.githubusercontent.com/46711/148155467-105b151a-77c5-423b-a39a-cfebcb1c345f.png)

If `jbang info tools HelloWorld.java` can output  sources jar, and it will be useful for IDE. 

```
  "resolvedSources": [
    "/Users/user1/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0-sources.jar"
  ],
```

**Comment by maxandersen** [comment]
Okey - makes sense to add optional extra option that resolves the sourced. 

But what would the list of sources be used for ? Wouldn't it need to be linked to some GAV or is it not enough to just look if there is a neighboring source/javadoc next to the .jar?

**Comment by linux-china** [comment]
I'm not familiar with VS Code Java, but for IntelliJ IDEA the sources list is enough.   

```java
public static void addModuleLibrary(@NotNull Module module,
                                      @Nullable String libName,
                                      @NotNull List<String> classesRootUrls,
                                      @NotNull List<String> sourceRootUrls,
                                      @NotNull DependencyScope scope)
```

Even the files of source jar are not in local repository now,   and it still ok for IDEA.  IDEA will monitor these sources jar files all time.  When these sources jar files available,  and IDEA will index these sources jar files.

**Comment by linux-china** [comment]
Close it now because IntelliJ IDEA can download source jars from Maven repository by GAV.
