### ISSUE TITLE
JBang always recompiling the scripts

### ISSUE THREAD

**Issue by gsmet** [jbangdev/jbang#1189]
**Describe the bug**

For a month or so now, JBang is always recompiling my JBang scripts and I always get the following output when executing my JBang script:
```
[jbang] Building jar...
[jbang] Post build with io.quarkus.launcher.JBangIntegration
Jan 10, 2022 5:44:25 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.4.2.Final
Jan 10, 2022 5:44:25 PM io.quarkus.deployment.QuarkusAugmentor run
INFO: Quarkus augmentation completed in 585ms
```

**To Reproduce**

No idea how to reproduce it outside of my environment. Things were working (i.e. it compiled the scripts only when I changed them) and then it started recompiling them for each execution.

It might be a coincidence but I think it started when I got JBang telling me that there was a new version around and that I should update.

I have this behavior for all the scripts of the Quarkus release process:
https://github.com/quarkusio/quarkus-release/blob/main/prerequisites.java

That I execute for instance with:
```
jbang --verbose prerequisites.java --micro --branch=2.2
```

I haven't updated nor removed the cache as I thought it might be useful to keep things this way.

**JBang version**

```
[jbang] jbang version 0.70.0
Cache: /home/gsmet/.jbang/cache
Config: /home/gsmet/.jbang
Repository:/home/gsmet/.m2/repository
0.70.0
```

**Comment by maxandersen** [comment]
Can you tar/zip with archive mode the cache and send/share to me? 

And when done try do jbang clear cache for each individual cache and see if a specific clear  makes it right  ?
(My guess is jar cache)

**Comment by gsmet** [comment]
I sent you the cache on Zulip as GitHub doesn't want it.

**Comment by gsmet** [comment]
Removing only the jar cache didn't work for me. Removing the whole cache directory fixed it.

**Comment by maxandersen** [comment]
Okey. Should be able to reproduce with the cache.

**Comment by gsmet** [comment]
I have saved the whole ~/.jbang directory if need be.

**Comment by maxandersen** [comment]
just noticed you are on 0.70 - do please update (`jbang version --update` or your used package manager) and see if things improves.

**Comment by maxandersen** [comment]
I couldn't spot anything particularly weird or wrong in your cache, nor could I reproduce the issue so I double-checked what conditions triggers rebuilds in the latest jbang (0.86):

- if the expected cached jar is missing
- if the jar creation date is younger than the source file
- if any of the dependencies needed are newer than the source file (i.e. if you are using a snapshot dependency we'll rebuild if that dependency was updated)
- if the requested java version is smaller/younger than the previous used java version

Which one that triggers a specific build we don't print at the moment so I'm adding that now for the verbose printing to help debug when/if it happens again.
