### ISSUE TITLE
jbang app install should ensure the alias can be built/resolved 

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1192]
this is to reduce users getting asked to trust a URL when they run the script rather than at install time.

**Comment by maxandersen** [comment]
this needs rolling back as using curl wont work then as no tty available to ask.

**Comment by quintesse** [comment]
Ah, okay. So what would be the alternative? We can't just try the downloading part because that would still ask the same question. Add some new system that bypasses the whole download code and does a HEAD request or something?

**Comment by maxandersen** [comment]
so I reverted the revert (for now) as I do thing asking at app install is a better experience.

The "solution" for the case of jbang is to have an explicit call to trust add,  before running app install:

```
 curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
curl -Ls https://sh.jbang.dev | bash -s - app install quarkus@quarkusio
```

closing this (again) as https://github.com/jbangdev/jbang/issues/608 still around

**Comment by quintesse** [comment]
Eww, that looks pretty horrible. I wonder if we should look into the possibility of using GUI pop-ups. Then we'd only be left with situations that people are working remotely or within a container.
