### ISSUE TITLE
if home dir is a  symboli link jbang thinks it is  a managed install

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1193]
**Describe the bug**

```
[jbang] jbang version 0.70.0
Cache: /home/gsmet/.jbang/cache
Config: /home/gsmet/.jbang
Repository:/home/gsmet/.m2/repository
```

but the real path is /data/home/gsmet

**Comment by quintesse** [comment]
What exactly is the problem? (Meaning what error occurs in what situation. How to reproduce)

**Comment by maxandersen** [comment]
If home dir is symbolic link 'jbang version --update' keeps insisting user most use their package manager to install. 

Somewhere we are probably comparing symbolic link vs absolute/real path and this getting a false instead of a true.

**Comment by quintesse** [comment]
> Somewhere we are probably comparing symbolic link vs absolute/real path and this getting a false instead of a true.

Indeed. This is now fixed.
