### ISSUE TITLE
Install fails downloading JDK on Windows with no existing java install, using Bash script; disco JDK endpoint URL incorrect?

### ISSUE THREAD

**Issue by scottkurz** [jbangdev/jbang#1195]
**Describe the bug**

In a Windows 10, Git Bash shell (or cygwin I assume), I would like to install via:
>  curl -Ls https://sh.jbang.dev | bash -s - app setup

rather than using the PS scripts (since I'm not a PS user).  

Instead I get the following error:
 
> $ curl -Ls https://sh.jbang.dev | bash -s - app setup
> Downloading JBang...
> Installing JBang...
> Downloading JDK 11. Be patient, this can take several minutes...
> Error downloading JDK

**To Reproduce**

By trying and failing to recreate the problem on other Windows/Linux VMs, and by enabling bash trace, I see that the problem occurs specifically because:
1. I don't have JAVA_HOME or JAVA_EXEC set
2. I don't have any `javac` on my PATH, i.e. `command -v javac` in `javacInPath()` returns empty. 

So basically:
1. unset JAVA_HOME
2. unset JAVA_EXEC
3. make sure `command -v javac` returns empty (by adjusting PATH or however)
4. do the install: `curl -Ls https://sh.jbang.dev | bash -s - app setup`

### BAD URL - foojay disco 'directuris'
So, now that we see what's unique about this use case, we can see this takes us down the path to:
```bash
      jdkurl="https://api.foojay.io/disco/v2.0/directuris?distro=aoj&libc_type=$libc_type&archive_type=tar.gz&operating_system=$os&package_type=jdk&version=$javaVersion&release_status=ga&architecture=$arch&latest=available"
      download $jdkurl "$TDIR/bootstrap-jdk.tgz"
```

But if you do a ` curl -Lf` on this URL you'll get a 404.

If you hit:  **https://api.foojay.io/disco/v2.0/**
or **https://api.foojay.io/swagger-ui/** 
you'll see several other endpoints, but none aligned with:    `https://api.foojay.io/disco/v2.0/directuris`

**Expected behavior**
Just trying to install

**JBang version**
N/A

**Additional context**
See above

**Comment by maxandersen** [comment]
Thanks for the report. It is expected the uri is not in the swagger/public api. Using a experimental api - but it should still work. Will investigate.

**Comment by maxandersen** [comment]
Ohhh - it's the bashscript. It might not request proper windows info....

**Comment by maxandersen** [comment]
okey so I can confirm seeing the same issue. @quintesse did this ever work ? (running bash under windows with no java installed?)

@scottkurz workaround is of course to run powershell version of the installer or is that not working either ? (besides your wish to try avoid using PS :)

**Comment by quintesse** [comment]
I've created a PR that should fix this, but of course the URL still fails so I can't test it 100%

**Comment by maxandersen** [comment]
@all-contributors please add @scottkurz for issue

Thanks scott - and kudos for detailed bug report !

**Comment by scottkurz** [comment]
> I've created a PR that should fix this, but of course the URL still fails so I can't test it 100%

@quintesse I'm confused how the #1196 PR relates to the issue as I described it.    

But maybe you're saying the bigger point is that you don't control the disco endpoint/API and it's expected that it will start working again at some point.   I guess I'll try in a few days..not urgent for me.   Thanks.

**Comment by quintesse** [comment]
@scottkurz you're right to be confused :-)

I didn't make clear I was reacting to @maxandersen 's statement:

> okey so I can confirm seeing the same issue. @quintesse did this ever work ?

That's the only thing I fixed _assuming_ there is/was indeed an issue with the service

**Comment by quintesse** [comment]
Hmm but it seems actually that the service is _not_ the problem, let me investigate some more...

**Comment by quintesse** [comment]
So @maxandersen , the issue is that when we switched to Foojay the download URL got more complex. One of the changes being that it now needs different `distro` arguments depending on the Java version we want to download. This was implemented in the Java code but _not_ in the startup scripts. So basically it not only Windows, _all_ startup scripts are wrong, FIxing them now.
