### ISSUE TITLE
Documentation is no longer published

### ISSUE THREAD

**Issue by jmini** [jbangdev/jbang#1212]
**Describe the bug**
Go to https://www.jbang.dev/documentation/

You will see:
> This page is just here to have sitemap generation work. Its content should be overwritten at build time - if you for some reason see this on https://jbang.dev you found a bug :)

<img width="917" alt="Screenshot 2022-01-25 at 16 02 10" src="https://user-images.githubusercontent.com/1222165/151002390-d6b0a96c-20d9-4545-965f-0dce7438a163.png">

**Expected behavior**
The documentation is published.

**Comment by maxandersen** [comment]
Thank you! Was missing an update on main site to aggregate the updated jbang-idea docs.

**Comment by maxandersen** [comment]
/@all-contributors please add @jmini  for docs
