### ISSUE TITLE
windows cygwin shell fails for install

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1223]
**Describe the bug**
found in https://stackoverflow.com/questions/70893995/jbang-on-cygwin-shell

```
curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
Downloading JBang... 
Error downloading JBang
```

I  confirm this happens using cygwin shell. not sure why yet.

**Comment by maxandersen** [comment]
```
Downloading JBang...
+ mkdir -p /home/max/.jbang/cache/urls
+ jburl=https://github.com/jbangdev/jbang/releases/latest/download/jbang.tar
+ download https://github.com/jbangdev/jbang/releases/latest/download/jbang.tar /home/max/.jbang/cache/urls/jbang.tar
++ command -v curl
+ '[' -x /cygdrive/c/WINDOWS/system32/curl ']'
+ curl -sLf -o /home/max/.jbang/cache/urls/jbang.tar https://github.com/jbangdev/jbang/releases/latest/download/jbang.tar
+ retval=23
+ '[' 23 -ne 0 ']'
+ echo 'Error downloading JBang'
Error downloading JBang
+ exit 23
```

**Comment by quintesse** [comment]
I get something different:

```
$ curl -Ls https://sh.jbang.dev | bash -x -s - app install --fresh --force quarkus@quarkusio
+ javaVersion=11
++++ absolute_path bash
++++ [[ bash = /* ]]
++++ [[ bash =~ ^[A-z]:/ ]]
++++ echo /home/root/bash
+++ resolve_symlink /home/root/bash
+++ [[ cygwin != darwin* ]]
+++ minusFarg=-f
++++ readlink -f /home/root/bash
+++ sym_resolved=/home/root/bash
+++ [[ -n /home/root/bash ]]
+++ echo /home/root/bash
++ dirname /home/root/bash
+ abs_jbang_dir=/home/root
+ libc_type=glibc
+ file_type=tar.gz
+ case "$(uname -s)" in
++ uname -s
+ os=windows
+ libc_type=c_std_lib
+ file_type=zip
+ case "$(uname -m)" in
++ uname -m
+ arch=x64
+ [[ 11 -eq 8 ]]
+ [[ 11 -eq 11 ]]
+ distro=temurin
+ [[ -z '' ]]
+ JBDIR=/home/root/.jbang
+ [[ -z '' ]]
+ TDIR=/home/root/.jbang/cache
+ '[' -f /home/root/jbang.jar ']'
+ '[' -f /home/root/.jbang/jbang.jar ']'
+ [[ ! -f /home/root/.jbang/bin/jbang.jar ]]
+ [[ ! -f /home/root/.jbang/bin/jbang ]]
+ /home/root/.jbang/bin/jbang app install --fresh --force quarkus@quarkusio
Error: Could not find or load main class dev.jbang.Main
Caused by: java.lang.ClassNotFoundException: dev.jbang.Main
+ exit 1
```

**Comment by maxandersen** [comment]
short fix to have cygwin shell fallback to old behavior of calling powershell script?

**Comment by quintesse** [comment]
I think we don't need to be in a rush, right? We can take a little time to figure out what's wrong I think.

**Comment by quintesse** [comment]
Ok, so I installed a new version of Cygwin and now I get the same error.
Do you get the same error if you just copy & paste the curl command? (remove the `s` otherwise you won't see any output)

```
$ curl -Lf -o ~/.jbang/cache/urls/jbang.tar https://github.com/jbangdev/jbang/releases/latest/download/jbang.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135  100   135    0     0    790      0 --:--:-- --:--:-- --:--:--   794
100   648  100   648    0     0   2935      0 --:--:-- --:--:-- --:--:--     0
Warning: Failed to create the file /home/tako/.jbang/cache/urls/jbang.tar: No
Warning: such file or directory
  0 6160k    0  4113    0     0   6840      0  0:15:22 --:--:--  0:15:22  6840
curl: (23) Failure writing output to destination
```

**Comment by quintesse** [comment]
Dunno what's going on, but it all seems completely broken on Cygwin.
I can fix the `curl` command but then the problem just moved to the error I pasted earlier https://github.com/jbangdev/jbang/issues/1223#issuecomment-1024412877

And I can trace it back to this weirdness:

```
~ $ java -classpath ~/.jbang/bin/jbang.jar dev.jbang.Main version
Error: Could not find or load main class dev.jbang.Main
Caused by: java.lang.ClassNotFoundException: dev.jbang.Main
~ $ java -classpath home/tako/.jbang/bin/jbang.jar dev.jbang.Main version
Error: Could not find or load main class dev.jbang.Main
Caused by: java.lang.ClassNotFoundException: dev.jbang.Main
~ $ java -classpath .jbang/bin/jbang.jar dev.jbang.Main version
0.87.0
~ $ cd .jbang/bin
~/.jbang/bin $ java -classpath ~/.jbang/bin/jbang.jar dev.jbang.Main version
Error: Could not find or load main class dev.jbang.Main
Caused by: java.lang.ClassNotFoundException: dev.jbang.Main
~/.jbang/bin $ java -classpath jbang.jar dev.jbang.Main version
0.87.0
```

So somehow it runs okay when using relative paths but breaks as soon as you use absolute paths. The same happens with the `curl` command btw. Relative paths for the `-o` parameter work, absolute paths don't. (This includes `/tmp` for examples, so it's not just `/home/....`)

**Comment by maxandersen** [comment]
Looking at https://stackoverflow.com/questions/24318596/bash-cannot-execute-a-perl-script-using-an-absolute-path could it be Either Curl or tar doesnt handle cygwin paths ?

**Comment by quintesse** [comment]
That's what I thought too, but the paths are normal (probably because we're only using $HOME which is "inside" the simulated Unix directory tree. The `/cygdrive` is only used if you want to have an absolute path to something on a Windows drive. At least that's how I understand things.

Eg. `cygpath /home/tako` or `cygpath ~` just return `/home/tako`.

And remember it isn't just curl or tar, java doesn't work either, because even with Jbang and a JDK available it still doesn't run.

**Comment by maxandersen** [comment]
So what happens if we last dos/windows paths to the apps? Will they work then ?

**Comment by quintesse** [comment]
Holy shit, that's indeed it. How does that even work?? How can bash scripts work in Cygwin if paths still have to be Windows paths? Anyway. So yes, the fix is then to go back to calling the Powershell script, no other way about it.

**Comment by berndschatz** [comment]
> Holy shit, that's indeed it. How does that even work?? How can bash scripts work in Cygwin if paths still have to be Windows paths? Anyway. So yes, the fix is then to go back to calling the Powershell script, no other way about it.

Did you already try ,,cygpath'' ?

e.g. --> https://cygwin.com/cygwin-ug-net/using-effectively.html

~~~
$ cygpath ~/.jbang/bin/jbang.jar
/home/BESCHAT/.jbang/bin/jbang.jar
~~~

**Comment by quintesse** [comment]
Sure, but that's completely Cygwin-specific, it's going to make the bash shell script a complete mess.

**Comment by quintesse** [comment]
Oh god, you know what the problem is? It's because nowadays Windows comes with its own `curl`! So if you don't have `curl` installed for Cygwin, which it doesn't by default, it will fall back to the Windows one, which of course doesn't understand Unix paths.

**Comment by berndschatz** [comment]
> Oh god, you know what the problem is? It's because nowadays Windows comes with its own `curl`! So if you don't have `curl` installed for Cygwin, which it doesn't by default, it will fall back to the Windows one, which of course doesn't understand Unix paths.

i just asked me, why your curl command worked for me :)

**Comment by quintesse** [comment]
So yes, the moment I install `curl` using the Cygwin setup _and_ (important!) open a new shell, the download works at least.
But the remaining problem is still `java`, which still needs a special Cygwin path....
Perhaps for that single path we can use `cygpath`, but that doesn't make we very happy TBH.

**Comment by quintesse** [comment]
Ok, created a PR that at least fixes the important problem of Jbang failing to execute. For Cygwin we fall back to the old behaviour of running `jbang.cmd`. This _does_ mean that some of the usage instructions (eg. when running `jbang jdk java-env`) will be _incorrect_ when running with Cygwin (it will give the instructions for running with CMD, not for Bash).

Can you perhaps check if this works for you @berndschatz ?

**Comment by berndschatz** [comment]
~~~
$ which java
/cygdrive/c/Program Files/Eclipse Adoptium/jdk-11.0.14.9-hotspot/bin/java

$ echo $JAVA_HOME
C:\Program Files\Amazon Corretto\jdk1.8.0_292

$ curl -Ls https://sh.jbang.dev | bash -s - app setup                                                               JAVA_HOME is set but does not seem to point to a valid Java JDK
Fehler: Hauptklasse dev.jbang.Main konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: dev.jbang.Main
~~~

**Comment by berndschatz** [comment]
~~~
$ which java
/cygdrive/c/Program Files/Eclipse Adoptium/jdk-11.0.14.9-hotspot/bin/java

$ export JAVA_HOME="c\\Program Files\\Eclipse Adoptium\\jdk-11.0.14.9-hotspot"

$ curl -Ls https://sh.jbang.dev | bash -s - app setup
JAVA_HOME is set but does not seem to point to a valid Java JDK
Fehler: Hauptklasse dev.jbang.Main konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: dev.jbang.Main
~~~

or 

~~~
$ export JAVA_HOME="/cygdrive/c/Program Files/Eclipse Adoptium/jdk-11.0.14.9-hotspot"
$ curl -Ls https://sh.jbang.dev | bash -s - app setup
JAVA_HOME is set but does not seem to point to a valid Java JDK
Fehler: Hauptklasse dev.jbang.Main konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: dev.jbang.Main
~~~

**Comment by quintesse** [comment]
@berndschatz you have use the version from the PR and run that. So something like this:

```
curl -Ls https://raw.githubusercontent.com/jbangdev/jbang/d36ae761bfe5dbacb7fc69ebb733ccbfd1b164f9/src/main/scripts/jbang | bash -s app setup
```
