### ISSUE TITLE
jbang alias list and jbang alias add prints/add empty properties

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1241]
**Describe the bug**

`jbang alias add -f . main.java` result in jbang-catalog.json to have empty properties added. Should just not be generated IMO.

But then `jbang alias list` prints:

```
jfxcentral = jfx-central.com as a JavaFX application
             Properties: {}
main@maxandersen/wordle-solve = https://github.com/maxandersen/wordle-solve/blob/HEAD/src/main.java
                                Properties: {}
```

which also is unnecessary as it equates to not have any properties.

**Comment by quintesse** [comment]
Indeed, that's most likely a regression.

**Comment by grumpyf0x48** [comment]
This issue is fixed.
