### ISSUE TITLE
Make trust interactive perhaps?

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#128]
Right now jbang has become more difficult to use for non-dev users with the introduction of "trust". It would perhaps be a good idea to make JBang interactively ask the user if a remote script should be executed or not. That would probably also mean having to add an option to prevent that question (and automatically fail, like now).

```
$ jbang http://some/url
Untrusted source http://some/url
Do you want to trust this source? (Yes/No/Always): A
Added as a permanent trusted source
. . .
```

**Comment by maxandersen** [comment]
I kinda wanted to but can't be done as the `///` comment trick decouples the console thus don't have a TTY.

if you can find a way around that i'm all ears.

**Comment by quintesse** [comment]
Darnit. Yeah, don't see a way around that right now either.

**Comment by maxandersen** [comment]
just tried it again and it actually seem to work now...not sure why...pretty sure I got a null console last I tried...

**Comment by maxandersen** [comment]
fixed a while ago.
