### ISSUE TITLE
`jbang config set` updates config key with updated value

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#1299]
**Describe the bug**
When updating an existing key in JBang configuration, the key is replaced with the value to update and the value is unchanged.

**To Reproduce**
1.  jbang config list
2.  jbang config set run.debug 7272
3. jbang config set init.template cli
4. jbang config list
5. jbang config set run.debug 7373
6. jbang config list

**Expected behavior**
Config value should have been replaced with updated value.

**JBang version**
[jbang] jbang version 0.91.0
Cache: /home/java_user/.jbang/cache
Config: /home/java_user/.jbang
Repository:/home/java_user/.m2/repository
0.91.0

**Additional context**
$ jbang config list
init.template = hello
run.debug = 4004
run.jfr = filename={baseName}.jfr
wrapper.install.dir = .

$ jbang config set run.debug 7272
[jbang] Option 'run.debug' set to '7272' in /home/java_user/.jbang/jbang.properties

$ jbang config set init.template cli
[jbang] Option 'init.template' set to 'cli' in /home/java_user/.jbang/jbang.properties

$ jbang config list
init.template = cli
run.debug = 7272
run.jfr = filename={baseName}.jfr
wrapper.install.dir = .

$ jbang config set run.debug 7373
[jbang] Option 'run.debug' set to '7373' in /home/java_user/.jbang/jbang.properties

$ jbang config list
**7373 = 7272**
init.template = cli
run.debug = 4004
run.jfr = filename={baseName}.jfr
wrapper.install.dir = .

**Comment by grumpyf0x48** [comment]
I'm working on a fix. Will make a PR soon.

**Comment by quintesse** [comment]
ooh nasty bug! Looking forward to your fix :+1: :slightly_smiling_face:

**Comment by quintesse** [comment]
Fixed by #1307
