### ISSUE TITLE
//FILES should support glob patterns 

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1338]
from beginning I deliberaly made it so //FILES was a 1-to-1 mapping to allow use it on remote urls.

But more and more I try use jbang for quarkus/ui apps I can't see it be useful unless we allow use of globpatterns, i.e. `//FILES templates/=**.qute.html` to include all files named qute.html in all subdirs.

tried doing a quickfix but atm RefTarget assumes it only resolves to a single file...so need some new notion.

**Comment by quintesse** [comment]
Well `RefTarget` was made with that specifically in mind, the fact that it _had_ to resolve to a single target or it wouldn't work.

So are you fine with some (at some point perhaps many) scripts not being able to run from URLs?

**Comment by maxandersen** [comment]
> So are you fine with some (at some point perhaps many) scripts not being able to run from URLs?

I'm not "fine", but I'm willing to live with it because without it using jbang for more than trivial few-files projects becomes tedious + we can warn/detect if glob patterns are used (could even in future consider a jbang.resources file that jbang can make to provide a index to resolve from).

Today in quarkus app just for a simple quarkus+htmx app (both tech that greatly reduce the setup you need) we have to do:

```
//FILES templates/Main/index.html=Main/indexbad.html
//FILES templates/Main/board.html=Main/board.html
//FILES templates/Main/chats.html=Main/chats.html
```

and everytime you add another html you need remember to keep adding such lines and it just gets out of hand.
Similar when writing even small animation or resource handling project having to manually outline them is tedious.
 
vs what we could offer:
```
//FILES templates/=**.qute.html
```

now I as a user can just add more folders/source files and all just works.

p.s. this editing fails hard with current jbang edit as you can't add more files but thats why inplace jbang edit is important; it works quite well with the jbang-idea workflow though.

**Comment by quintesse** [comment]
Ok.

Btw, I'm not sure I understand this syntax:

```
//FILES templates/=**.qute.html
```

I'm assuming you just wrote that down quickly without actually thinking about it much? Otherwise there are several things that seem wrong in that line 🙂

**Comment by quintesse** [comment]
Ahh okay, you're _mounting_ under "templates/", that wasn't what I expected given that the files to add were ".qute" files.

Then the only thing left would be to write `**.html.qute` because we only support ".qute" being the last part of the filename.

**Comment by aghasemi** [comment]
> from beginning I deliberaly made it so //FILES was a 1-to-1 mapping to allow use it on remote urls.
> 
> But more and more I try use jbang for quarkus/ui apps I can't see it be useful unless we allow use of globpatterns, i.e. `//FILES templates/=**.qute.html` to include all files named qute.html in all subdirs.
> 
> tried doing a quickfix but atm RefTarget assumes it only resolves to a single file...so need some new notion.

The same thing would also be useful for `//SOURCES`

**Comment by maxandersen** [comment]
Sources already support this.
