### ISSUE TITLE
Installing an app from a catalog from GitHub is broken

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang#1345]
**Describe the bug**
`jbang app install --fresh --force quarkus@quarkusio` fails with the following error:

```
[jbang] [ERROR] Could not download https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] Run with --verbose for more details
```
**To Reproduce**
1. Run `jbang app install --fresh --force quarkus@quarkusio`
2. See error

**Expected behavior**
`quarkus` app should have been installed 

**JBang version**
```
[jbang] jbang version 0.92.2
Cache: /Users/ggastald/.jbang/cache
Config: /Users/ggastald/.jbang
Repository:/Users/ggastald/.m2/repository
0.92.2
```
**Additional context**
Reported in https://github.com/quarkusio/quarkus/issues/25201

**Comment by quintesse** [comment]
Btw, I see that there was output in the linked issue.

**Comment by gastaldi** [comment]
It seems to be a GitHub glitch, but I wonder if we shouldn't be consuming the URL as proposed in https://github.com/quarkusio/quarkus/issues/25201#issuecomment-1111035488 instead

**Comment by gastaldi** [comment]
@quintesse would it make sense to fall back to the `default_branch` specified in https://api.github.com/repos/quarkusio/quarkus for example when 404 is returned to the attempted URL?

**Comment by maxandersen** [comment]
Also https://github.com/jbangdev/jbang-action/commit/c11f21c01f32e28e43fc8843e5028ca3dbcd507d/checks?check_suite_id=6284894449 failed for similar reason but different catalog.
