### ISSUE TITLE
Forcing dependencies update (like maven "-U")

### ISSUE THREAD

**Issue by jmini** [jbangdev/jbang#1347]
**Is your feature request related to a problem? Please describe.**

When jbang downloads artifact, it seems to be bound to the updatePolicy configured for maven, which is daily by default (see https://maven.apache.org/ref/3.8.5/maven-settings/settings.html#releases)

In maven you have the `-U` (or `--update-snapshots`) flag to force the update of dependencies.

**Describe the solution you'd like**

A way (maybe the existing command `--fresh`) to force jbang to be sure to get the latest version.

**Describe alternatives you've considered**

Run `mvn -U dependency:get -Dartifact=<my dep>` before running `jbang` to be sure to have resolved the latest version.

**Comment by maxandersen** [comment]
--fresh ?

**Comment by maxandersen** [comment]
Oh - you are saying fresh doesn't download snapshot updates ? That could be.

**Comment by maxandersen** [comment]
We need to pass in a mavenupdatepolicy - https://github.com/shrinkwrap/resolver/blob/f564882d785db86460f43cc7512650e3efae3380/maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/repository/MavenUpdatePolicy.java

Then if doable have --fresh force update snapshots and have something like a `--fresh=always|never|auto` to fine tune  it. 

Idea being if you want fresh you also want fresh snapshots.
