### ISSUE TITLE
jbang script should be able to bootstrap itself

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#135]
on linux/osx jbang could have a bootstrap option to make `./helloworld.java` would install jbang + jvm to run

related to #134 and #133

**Comment by quintesse** [comment]
Also see #219

**Comment by maxandersen** [comment]
So .. if that other script happens to download the jar. We would just have to get the bootstrap in user scripts be to download that script...

**Comment by quintesse** [comment]
Just to clarify "that other script" is still `jbang[.cmd]`. There's just an added piece to it that checks if there's a jbang.jar in the same folder and if not it will download jbang, unpack it and pass control over to the newly unpacked script. (That last thing is so older scripts can more easily stay forward compatible)

**Comment by quintesse** [comment]
But yes, any user scripts that want to use Jbang just need to get the `jbang[.cmd]` in some way.

**Comment by maxandersen** [comment]
this is now possible using `///usr/bin/env curl -LSs https://sh.jbang.dev | bash -s - "$0" "$@"; exit $?` instead of the normal jbang #! line.

**Comment by quintesse** [comment]
Figured out a "smart" version of the bootstrap that does not require the script to be obtained to work. We might want to add an example script for this just so people know it's possible?

```
///usr/bin/env echo '
/*'>/dev/null
JB=$(/usr/bin/env command -v jbang) ; JB=${JB:-${JBANG_DIR:-$HOME/.jbang}/bin/jbang}
[ -f $JB ] && exec $JB "$0" "$@" ||
/usr/bin/env curl -LSs https://sh.jbang.dev | exec bash -s - "$0" "$@" ; exit $?
*/
```

**Comment by maxandersen** [comment]
We should have it documented as a minimum and we could have a 'jbang bootstrap app.java' that replaces the standard line and put this instead.
