### ISSUE TITLE
JBang "add alias --deps" end up in "repositories" section (instead of "dependencies")

### ISSUE THREAD

**Issue by ivangsa** [jbangdev/jbang#1367]
**Describe the bug**

`jbang alias add --deps=<dependencies>`

end in the **repositories** section in jbang-catalog.json (instead of **depedencies** section)

**To Reproduce**
1. `jbang alias add --name=apimock -m=io.github.apimock.Main --deps=org.openapi4j:openapi-operation-validator:1.0.7  io.github.zenwave360:zenwave-apimock:0.1.0`
2. `cat $HOME/.jbang/jbang-catalog.json`

Actual generated alias is:

```
    "apimock": {
      "script-ref": "io.github.zenwave360:zenwave-apimock:0.1.0",
      "repositories": [
        "org.openapi4j:openapi-operation-validator:1.0.7"
      ],
      "main": "io.github.apimock.Main"
    }
```

**Expected behavior**

```
    "apimock": {
      "script-ref": "io.github.zenwave360:zenwave-apimock:0.1.0",
      "dependencies": [
        "org.openapi4j:openapi-operation-validator:1.0.7"
      ],
      "main": "io.github.apimock.Main"
    }
```

**JBang version**

> $ jbang version --verbose
> [jbang] jbang version 0.94.0
> Cache: C:\Users\ivan.garcia\.jbang\cache
> Config: C:\Users\ivan.garcia\.jbang
> Repository:C:\Users\ivan.garcia\.m2\repository
> 0.94.0

**Additional context**

**Comment by maxandersen** [comment]
ah! that explains https://github.com/jbangdev/jbang/issues/1354#issuecomment-1124057499

**Comment by quintesse** [comment]
Fixed now in latest code. Thanks for your bug report, @ivangsa

**Comment by ivangsa** [comment]
hi @quintesse 

Also if I use the **--repos** switch on the command line they end up on the `classpaths` section

```
      "classpaths": [
        "https://oss.sonatype.org/content/repositories/snapshots"
      ],
```

**Comment by maxandersen** [comment]
We'll get a release out this week with a fix.

**Comment by quintesse** [comment]
> Also if I use the --repos switch on the command line they end up on the classpaths section

Yeah, all arguments got "shifted", so basically most of them will be wrong. All of that has been fixed by this PR.
