### ISSUE TITLE
Existing Java installation not detected on Mac OSX 

### ISSUE THREAD

**Issue by yeroc** [jbangdev/jbang#1385]
**Describe the bug**
I just installed JBang for the first time (via brew) and for some reason it's not detecting the JDK already on my path but instead is downloading a new JDK.

**To Reproduce**
```
brew install jbangdev/tap/jbang
jbang --verbose help
```

**Expected behavior**
I expected JBang to use the existing JDK 17 installation on my path.  Instead I get a message that it's downloading JDK 17.

**JBang version**

```
$ brew info jbang
jbangdev/tap/jbang: stable 0.95.0
Unleash the power of Java
https://jbang.dev
/opt/homebrew/Cellar/jbang/0.95.0 (8 files, 6MB) *
  Built from source on 2022-06-23 at 16:10:33
From: https://github.com/jbangdev/homebrew-tap/blob/HEAD/Formula/jbang.rb
License: MIT
```

**Additional context**
I'm using jenv to manage multiple java installs:
```
$ jenv versions
  system
  11
  11.0
  11.0.14
* 17 (set by /Users/yeroc/.jenv/version)
  17.0
  17.0.2
  openjdk64-11.0.14
  openjdk64-17.0.2
```
Java 17 is on my path:
```
$ java -version
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
```
but when I run JBang it insists on installing a new JDK:
```
$ jbang --verbose help
Downloading JDK 17. Be patient, this can take several minutes...
^C
```
If it matters this is a MacBook Air M1 (arm64) running  macOS 12.4.

**Comment by yeroc** [comment]
Examining the jbang shell script it seems like the `javacInPath()` is evaluating to `false` but I don't understand why because when I evaluate a similar expression I get true:
```
$ os=mac; [[ -x "$(command -v javac)" && ( $os != "mac" || $(/usr/libexec/java_home &> /dev/null) ) ]] && echo false || echo true
true
```
and here's the output from java_home for completeness:
```
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
$ echo $?
0
```

**Comment by maxandersen** [comment]
That is weird. 

Do note we are looking for javac not java. 

Is javac present in path or $java_home/bin?

**Comment by yeroc** [comment]
Yeah... It's perplexing.  javac is on the path as well:

```
$ javac -version
javac 17.0.3
```

**Comment by yeroc** [comment]
I edited `/opt/homebrew/bin/jbang` and added a `-x` parameter to the first line for debugging.  Here's the output:
```
$ jbang --verbose --version
+ javaVersion=11
+ abs_jbang_dir=/opt/homebrew/Cellar/jbang/0.95.0/libexec/bin
+ libc_type=glibc
+ file_type=tar.gz
+ case "$(uname -s)" in
++ uname -s
+ os=mac
+ libc_type=libc
+ case "$(uname -m)" in
++ uname -m
+ '[' mac = mac ']'
+ arch=arm64
+ javaVersion=17
+ [[ mac == windows ]]
+ [[ -z '' ]]
+ [[ 17 -eq 8 ]]
+ [[ 17 -eq 11 ]]
+ [[ 17 -ge 17 ]]
+ distro=temurin
+ [[ -z '' ]]
+ JBDIR=/Users/yeroc/.jbang
+ [[ -z '' ]]
+ TDIR=/Users/yeroc/.jbang/cache
+ '[' -f /opt/homebrew/Cellar/jbang/0.95.0/libexec/bin/jbang.jar ']'
+ jarPath=/opt/homebrew/Cellar/jbang/0.95.0/libexec/bin/jbang.jar
+ '[' -f /opt/homebrew/Cellar/jbang/0.95.0/libexec/bin/jbang.jar.new ']'
+ unset JAVA_EXEC
+ [[ -n '' ]]
+ [[ -z '' ]]
+ javacInPath
++ command -v javac
+ [[ -x /Users/yeroc/.jenv/shims/javac ]]
+ [[ mac != \m\a\c ]]
++ /usr/libexec/java_home
+ [[ -n '' ]]
+ '[' -x /Users/yeroc/.jbang/currentjdk/bin/javac ']'
+ export JAVA_HOME=/Users/yeroc/.jbang/cache/jdks/17
+ JAVA_HOME=/Users/yeroc/.jbang/cache/jdks/17
+ JAVA_EXEC=/Users/yeroc/.jbang/cache/jdks/17/bin/java
+ '[' '!' -d /Users/yeroc/.jbang/cache/jdks/17 ']'
+ [[ mac == '' ]]
+ [[ arm64 == '' ]]
+ mkdir -p /Users/yeroc/.jbang/cache/jdks
+ echo 'Downloading JDK 17. Be patient, this can take several minutes...'
Downloading JDK 17. Be patient, this can take several minutes...
+ jdkurl='https://api.foojay.io/disco/v2.0/directuris?distro=temurin&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=17&architecture=arm64&latest=available'
+ download 'https://api.foojay.io/disco/v2.0/directuris?distro=temurin&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=17&architecture=arm64&latest=available' /Users/yeroc/.jbang/cache/bootstrap-jdk.tar.gz
++ command -v curl
+ '[' -x /usr/bin/curl ']'
+ curl -sLf -o /Users/yeroc/.jbang/cache/bootstrap-jdk.tar.gz 'https://api.foojay.io/disco/v2.0/directuris?distro=temurin&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=17&architecture=arm64&latest=available'
^C
```

**Comment by yeroc** [comment]
I did find a workaround is to manually set `JAVA_HOME`.  Or rather, I configured a `jenv` plugin which does that for me. So now:
```
$ echo $JAVA_HOME
/Users/yeroc/.jenv/versions/17
$ jbang --version
0.95.0
```
I still can't figure out why it's not picking up the java/javac on the path though.  Seems to be some sort of bug there somewhere.

**Comment by quintesse** [comment]
Can you perhaps test a tiny shell script, just to see if we can drill down to the actual issue?

Something like:

```bash
#!/usr/bin/env bash

os=mac

javacInPath() {
  [[ -x "$(command -v javac)" && ( $os != "mac" || $(/usr/libexec/java_home &> /dev/null) ) ]]
}

if javacInPath; then
  echo "found"
else
  echo "not found"
fi
```

Because the flow of the debug output is all correct, so obviously `javacInPath` is somehow not returning the expected value. Or the `if` is somehow interpreting the result wrongly.

**Comment by yeroc** [comment]
Sure...
```
$ cat jb
#!/usr/bin/env bash

os=mac

javacInPath() {
  [[ -x "$(command -v javac)" && ( $os != "mac" || $(/usr/libexec/java_home &> /dev/null) ) ]]
}

if javacInPath; then
  echo "found"
else
  echo "not found"
fi
```
output:
```
$ ./jb
not found
```

**Comment by quintesse** [comment]
Hmm wait, I actually thought you're original test went okay when you executed it manually , but now I see that you switched "true" and "false". It should really have been:

```
os=mac; [[ -x "$(command -v javac)" && ( $os != "mac" || $(/usr/libexec/java_home &> /dev/null) ) ]] && echo true || echo false
```

So if that fails it must mean that `command -v javac` fails. Can you try running that and show the output?

**Comment by yeroc** [comment]
```
$ cat jb
#!/usr/bin/env bash

os=mac

javacInPath() {
  [[ -x "$(command -v javac)" ]]
}

if javacInPath; then
  echo "found"
else
  echo "not found"
fi
```
output:
```
$ ./jb
found
```

**Comment by yeroc** [comment]
However, what about this?
```
$ cat jb
#!/usr/bin/env bash

os=mac

javacInPath() {
  [[ -x $(/usr/libexec/java_home &> /dev/null) ]]
}

if javacInPath; then
  echo "found"
else
  echo "not found"
fi

/usr/libexec/java_home
```
output:
```
$ ./jb
not found
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
```

**Comment by quintesse** [comment]
That's very weird, you already showed that `/usr/libexec/java_home ; echo $?` printed `0`.

Can you manually just run `/usr/libexec/java_home &> /dev/null` in your shell? Followed by `echo $?`.
And perhaps `$(/usr/libexec/java_home &> /dev/null)` followed by `echo $?` as well.

**Comment by yeroc** [comment]
Output:
```
$ /usr/libexec/java_home &> /dev/null
$ echo $?
0
$ $(/usr/libexec/java_home &> /dev/null)
$ echo $?
0
```

**Comment by yeroc** [comment]
I'm not a shell programming expert but it seems to me perhaps the correct test would be?:
```
  [[ -x "$(command -v javac)" && ( $os != "mac" || /usr/libexec/java_home ) ]]
```
According to https://unix.stackexchange.com/a/220840/220249 the `$(/usr/libexec/java_home &> /dev/null)` test evaluates to `false` when there's no output (which there won't be since the output is being redirected).

**Comment by quintesse** [comment]
@yeroc it seems to me that that would print out the Java path each time you run `jbang`, that doesn't seem correct.

But you seem to be right at least that simply using `$(/usr/libexec/java_home &> /dev/null)` isn't correct. Thing is I don't have a Mac so I can't really test this. I know this is done because all Macs have a pre-installed `java` / `javac` command, even if Java isn't actually installed. When you don't have Java installed and try to run any of these commands the OS will ask the user if they want to install Java. So on Macs we use `java_home` to detect if Java is installed or not. But I don't remember if it's because `java_home` does not exist before Java gets installed or because it returns an error... Do you, @maxandersen ?

**Comment by quintesse** [comment]
Hmm seems I'm obviously even less of an shell expert because it turns out that output written bny commands used in tests isn't actually displayed. I didn't know that...

**Comment by quintesse** [comment]
So, thinking about it some more I propose the following test:

```
[[ -x "$(command -v javac)" ]] && ( [[ $os != "mac" ]] || /usr/libexec/java_home &> /dev/null )
```

Assuming that running `java_home` will:

 a) print out a path to the default Java SDK, if installed
 b) print out an error message (or nothing) and return a non-zero exit code, if Java is not installed

**Comment by yeroc** [comment]
@quintesse That looks correct to me.  According to https://stackoverflow.com/a/44158166/85464 `java_home` should be responding in the manner you describe.

**Comment by yeroc** [comment]
@quintesse I know it's not relevant to the issue at hand but `java_home` has an interesting option to ask for a specific JDK version install that could be used to find the path to an existing installation for a specific version:
```
/usr/libexec/java_home --failfast --version 17
```
(The `--failfast` option is important as otherwise it'll just return the default JDK if a match isn't found).
