### ISSUE TITLE
The jbang.cmd wrapper doesn't seem to work on Windows 2022 (GH Actions)

### ISSUE THREAD

**Issue by helpermethod** [jbangdev/jbang#1386]
**Describe the bug**
When doing a matrix build with jbang, the wrapper is used to install and run jbang. But on the Windows 2022 runner it fails for unknown reasons.

https://github.com/helpermethod/p2e/runs/7063238127?check_suite_focus=true#step:4:54

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1562019/175833004-094b1fa8-7948-4684-934c-eb8117d77925.png">

**To Reproduce**
1. Install the jbang wrapper and check it into version control
2. Create a GH Actions workflow with a matrix build (macos-12, ubuntu-22.04, windows-2022)
3. Run the build
4.  The jbang step will fail but only on the Windows 2022 runner

**Expected behavior**
The jbang step should work on Windows 2022 just as well as on Mac OS and Ubuntu, similar to the Maven wrapper, which somehow manages to work in all 3 environments (see https://github.com/helpermethod/connor/blob/761e5288eb31305c5faf09ff078ffc3b8afb83cc/.github/workflows/ci.yml#L85 for an example).

**JBang version**
```
[jbang] jbang version 0.95.0
Cache: /Users/weilero/.jbang/cache
Config: /Users/weilero/.jbang
Repository:/Users/weilero/.m2/repository
0.95.0
```

**Comment by quintesse** [comment]
That is indeed a bug. It's because the wrapper should also copy the `jbang.ps1` file. As a work-around you can copy that file yourself from `~/.jbang/bin/jbang.ps1`.
