### ISSUE TITLE
./jbang export local --native calls the wrong native-image executable on Windows Server 2022

### ISSUE THREAD

**Issue by helpermethod** [jbangdev/jbang#1394]
**Describe the bug**
On Windows Server 2022, `./jbang export local --native ...` tries to call `native-image.exe` instead of `native-image.cmd`, see

https://github.com/helpermethod/p2e/runs/7211828761?check_suite_focus=true#step:5:62

**To Reproduce**
1. Create a GitHub Actions Workflow
2. Use the official setup-graalvm Action for settings up Java 17 with native-image
3. Run ./jbang export local --native --output p2e p2e.java on Windows Server 2022
4. The wrong executable is called by jbang

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/1562019/177521979-02dcb8c5-c5f9-44cc-9e55-cf2c859683a3.png">

**Expected behavior**
`native-image.cmd` is called instead.

**JBang version**
```
[jbang] jbang version 0.95.0
Cache: /Users/weilero/.jbang/cache
Config: /Users/weilero/.jbang
Repository:/Users/weilero/.m2/repository
0.95.0
```

**Comment by helpermethod** [comment]
Sorry, the repo was accidentally set to private. The link should work now.

**Comment by quintesse** [comment]
Yup, `.exe` is hard-coded. I'm guessing that up to now `native-image` has always been an EXE on Windows. They must have  changed that recently?

https://github.com/jbangdev/jbang/blob/main/src/main/java/dev/jbang/source/builders/BaseBuilder.java#L305

**Comment by helpermethod** [comment]
I guess they changed it when it became an optional part of the GraalVM dists. I'll See If I can find out sth.

**Comment by quintesse** [comment]
It seems the .exe is now located in `$JAVA_HOME/lib/svm/bin` and the .cmd just starts that. Probably they reorganized things.

**Comment by quintesse** [comment]
Ok, I created a fix for this which _should_ work. #1395

**Comment by quintesse** [comment]
Ok, so the fix does work, but I encountered a couple of other issues along the way:

- #1396
- #1397
