### ISSUE TITLE
native-image doesn't like Windows paths in JARs

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#1396]
In JBang we generate JARs that contain paths to their dependencies. Now although this does work (as long as you don't move the resulting JAR to a different OS) it:

a) does not seem to adhere to [the spec](https://docs.oracle.com/en/java/javase/17/docs/specs/jar/jar.html#class-path-attribute) which specifies that the MANIFEST Class-Path should only contain relative paths/URLs

b) the Graal native-image does _not_ like the absolute Windows paths at all and exits with an error that the path contains illegal characters (`:`)

We might try to see if we can use `file:` URLs instead. According to the spec they are allowed, although still not absolute, but we might be able to get away with it. Otherwise we might want to revisit the idea that we add a `Class-Path` to our JARs by default (perhaps make it an option of `export` instead?).

**Comment by quintesse** [comment]
> We might try to see if we can use file: URLs instead.

Just tested this and no, native-image doesn't seem to support that. (Which is actually not in accordance to the spec which says that file URLs are allowed)

**Comment by quintesse** [comment]
Tested with a version of Jbang that doesn't add `Class-Path` and that works. So perhaps we should just not add `Class-Path` anymore to our JARs' MANIFESTs. It might not be too much of a problem, how many people will run the cached JAR by itself? The `export` function correctly adds relative paths so that's okay. Wdyt @maxandersen ?

**Comment by maxandersen** [comment]
so we regen the path on the fly everytime? i think that should be fine.

**Comment by quintesse** [comment]
Sure, we could do that. But what advantage do we get for keeping an, apparently unsupported, feature that most likely nobody is using?

And how would we do it? We remove the paths, create the native image and put the paths back in again? That doesn't sound like a very nice solution. Or do we create a temporary copy of the JAR without the paths, create the native iamge and then delete the temporary copy?

**Comment by helpermethod** [comment]
`native-image` doesn't need a JAR at all, right? Maybe you could skip the JAR generation in the case of a native image being exported?

**Comment by maxandersen** [comment]
Then we would need to compile again or keep a directory around with the compiled classes - just for native image. 

It simplifes things if a jar is what we Pass on.

**Comment by helpermethod** [comment]
Hi @maxandersen, @quintesse,

I gave version 0.96.0 a try but there still seems to be problem with the Windows path.

https://github.com/helpermethod/p2e/runs/7340216008?check_suite_focus=true#step:4:62

![image](https://user-images.githubusercontent.com/1562019/178988463-5063cd68-2013-4455-a847-92f04c017d2c.png)

**Comment by quintesse** [comment]
Hi @helpermethod, can you try with `export portable`? The `local` export will still use the absolute file paths.
Besides that we'll be changing the `--native` flag for a separate `export native` in the next version because it really doesn't make much sense.

> Don't want to bitch around there

Don't worry, you're helping us a lot by letting us know what works and what not!

**Comment by quintesse** [comment]
@helpermethod this seems a GraalVM native-image problem: https://github.com/oracle/graal/issues/1514

Make sure all the files and working directory are all on the same drive. (Even links to files/folders can cause this!)
