### ISSUE TITLE
`jbang.cmd` broken after #1389 when `JAVA_HOME` has spaces

### ISSUE THREAD

**Issue by garodriguezlp** [jbangdev/jbang#1412]
**Describe the bug**
`jbang.cmd` broken after #1389 when `JAVA_HOME` has spaces

**To Reproduce**
1. Install `jbang` version `0.96.0` on a Windows 10 host using `chocolatey`. 
```ps1
choco install jbang
```
2. execute `jbang --version`
3. See error
```
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Expected behavior**
`jbang` should work fine on Windows 10 host 

**JBang version**
`0.96.0`

**Additional context**

- Host version
```
PS C:\WINDOWS\system32> [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19044  0
```

- Potentially impacted community

Anyone who has installed `jbang` and the `jdk` using [`chocolatey`](https://chocolatey.org/), given that the installation script uses `jbang.cmd` as the `BinFile` 

![image](https://user-images.githubusercontent.com/1432287/181658115-945511bf-ac46-488c-8b4f-cc094b94c513.png)

And the `jdk` usually gets installed in the `C:\Program Files` dir, which has a space. 

![image](https://user-images.githubusercontent.com/1432287/181658372-32b2c9c4-07bc-4320-9fc3-13e497c9f2f5.png)

**Comment by garodriguezlp** [comment]
@maxandersen and @quintesse I think [>> this <<](https://github.com/jbangdev/jbang/pull/1389/files#r932767038) is the root cause of this issue

**Comment by quintesse** [comment]
@garodriguezlp and this should also be fixed in the latest release.

**Comment by garodriguezlp** [comment]
Hi @quintesse! Yes, I tested it out with the latest release (v0.96.1), and it's working fine for me. 😎

Thanks!!

**Comment by quintesse** [comment]
Great! Thanks for your help!
