### ISSUE TITLE
Installation fails due to changed 3rd party API

### ISSUE THREAD

**Issue by steve1337** [jbangdev/jbang#1414]
**Describe the bug**

https://api.foojay.io/disco/v2.0/directuris returns 404 this means installations of JDK fail

Hardcoded URL: https://github.com/jbangdev/jbang/blob/main/src/main/scripts/jbang#L202

```bash
curl -Ls https://sh.jbang.dev | bash -s - app setup
Downloading JBang...
Installing JBang...
Downloading JDK 11. Be patient, this can take several minutes...
wget: server returned error: HTTP/1.1 404 Not Found
Error downloading JDK
```

**To Reproduce**

Run this
```bash
curl -Ls https://sh.jbang.dev | bash -s - app setup
```

**Expected behavior**
JDK will be installed

**Comment by steve1337** [comment]
Apparently only a temporary outage. 

See: https://github.com/foojayio/discoapi/issues/62#issuecomment-1199092426

CLOSING this issue.

**Comment by quintesse** [comment]
Ok, thanks for the heads-up anyway!
And we'll take a look at the v3 API they mention.
