### ISSUE TITLE
Wrong args parsing for apps installed in Windows using Powershell

### ISSUE THREAD

**Issue by garodriguezlp** [jbangdev/jbang#1416]
**Describe the bug**

Wrong args parsing for apps installed in Windows using Powershell.

**To Reproduce**

1. Install `jbang` in a `Windows 10` host using `PowerShell`:

    ```ps1
    iex "& { $(iwr -useb https://ps.jbang.dev) } app setup"
    ```

2. Install `spring-boot-cli` as a `jbang` `app` with the `spring` name:

    ```ps1
    jbang app install --name=spring org.springframework.boot:spring-boot-cli:2.7.1:full
    ```

3. Try to initialize a new project by running:

    ```ps1
    spring init -j 11 -d web demo
    ```

    ```ps1
    'init -j 11 -d web demo' is not a valid command. See 'help'
    ```

**Expected behavior**

The `sprig-boot-cli` should be able to initialize a new project.

**JBang version**

```ps1
➜ jbang version --verbose
[jbang] jbang version 0.96.0
Cache: C:\Users\gustavo.rodriguezl\.jbang\cache
Config: C:\Users\gustavo.rodriguezl\.jbang
Repository:C:\Users\gustavo.rodriguezl\.m2\repository
0.96.0
```

**Additional context**

- Host info

```
➜ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

- Workaround:

1. Edit the installed app's `Powershell` script [`spring.ps1`] by changing the `$` prefix to `@` on the `args` variable:

    ```ps1
    jbang run org.springframework.boot:spring-boot-cli:2.7.1:full @args
    ```

2. Try to initialize a new project by running:

    ```ps1
    spring init -j 11 -d web demo
    ```

3. You should see something like this:

    ```ps1
    ➜ spring init -j 11 -d web demo
    Using service at https://start.spring.io
    Project extracted to '...\demo'
    ```

- What could be happening here?
    - I think [this 👇](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.2) could explain it better

![image](https://user-images.githubusercontent.com/1432287/181841959-39dd9b95-867b-4809-ab1e-ecc617e36837.png)

**Comment by garodriguezlp** [comment]
[quintesse](https://github.com/quintesse) I think this is what I was talking here https://github.com/jbangdev/jbang/pull/1413#issuecomment-1199458320

**Comment by quintesse** [comment]
@garodriguezlp this should be fixed now in the latest release, can you confrim?

**Comment by garodriguezlp** [comment]
Yes @quintesse. It's working fine in v0.96.1

**Comment by quintesse** [comment]
Perfect. Thanks!
