### ISSUE TITLE
cannot run kotlin on Windows because wrong extension of kotlinc

### ISSUE THREAD

**Issue by yeung66** [jbangdev/jbang#1433]
**Describe the bug**
the code now will add `.exe` extension for `kotlinc`  in Windows, but the kotlin-compiler downloaded only contains `kotlinc` and `kotlinc.bat`. Therefore it should use `kotlinc.bat` in Windows, otherwise it causes exception.

**To Reproduce**
on Windows
1. `jbang init -t hello.kt hello.kt`
2. `jbang --verbose .\hello.kt`

**Expected behavior**
output Hello World
instead of 
```
[jbang] [ERROR] Cannot run program "C:\Users\...\.jbang\cache\kotlincs\1.6.10\kotlinc\bin\kotlinc.exe": CreateProcess error=2
```

**JBang version**
Paste output of `jbang version --verbose`
`[jbang] jbang version 0.97.0`

**Comment by garodriguezlp** [comment]
Guys, please 🙏, I hope you can release this fix ASAP. 😅 I'm eagerly waiting for it. 

BTW. Thank you sooooooooooooo much @yeung66 !!
