### ISSUE TITLE
Provide a tool friendly version of `jbang templates list` (i.e JSON output)

### ISSUE THREAD

**Issue by fbricon** [jbangdev/jbang#1453]
**Describe the bug**
When run in a terminal, humans can easily parse the output of `jbang templates list`, notably `jitpack@jbangdev`, because the output is coloured:

<img width="1032" alt="Screenshot 2022-09-09 at 13 20 41" src="https://user-images.githubusercontent.com/148698/189339068-e49197d3-bf7d-4263-a897-f0a1483bbfa4.png">

When running that command in the context of an IDE, you want to disable coloring but then the output becomes just
```
agent = Agent template
cli = CLI template
github@jbangdev = Simple cli to querying github
hello = Basic Hello World template
hello.groovy = Basic groovy Hello World template
hello.kt = Basic kotlin Hello World template
jitpack@jbangdev = Initializes a bare-bone jitpack.yml to enable publishing a jbang script as a maven artifact via jitpack.

Example: `jbang init -t jitpack@jbangdev myapp.java` and then commit this to github and visit jitpack.io to trigger its build.
junit@jbangdev = Basic template for JUnit tests
qcli = Quarkus CLI template
qmetrics = Quarkus Metrics template
qrest = Quarkus REST template
readme.md = Basic markdown readme template
```

Properly parsing that output becomes more complex than necessary, it's not just splitting each line on '='. A more tools friendly option would output JSON for instance, with the addition of a flag.

**Comment by quintesse** [comment]
Thought this was a pretty good idea so I decided to add a `--json` option to *all* `list` commands! :-)
