### ISSUE TITLE
app installation does not support paths with spaces

### ISSUE THREAD

**Issue by jeffmaury** [jbangdev/jbang#1472]
**Describe the bug**
Have a JBang script in a folder with a space in it. Run `jbang app install` and try to run the installed app

```
[jbang] [ERROR] Script or alias could not be found or read: 'C:\work\src\github.com\jeffmaury\kuben'
[jbang] Run with --verbose for more details
```

**To Reproduce**
1. Create a JBang script with space in folder
2. run j`bang app install ...`
3. run installed app

**Expected behavior**
App should run

**JBang version**
```
[jbang] jbang version 0.98.0
Cache: C:\Users\JeffMAURY\.jbang\cache
Config: C:\Users\JeffMAURY\.jbang
Repository:C:\Users\JeffMAURY\.m2\repository
0.98.0
```

**Additional context**

**Comment by quintesse** [comment]
Confirmed.

**Comment by quintesse** [comment]
Fixed, thanks @jeffmaury !
