### ISSUE TITLE
expose/enable compile with debug

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1478]
turns out debugging with jbang compiled does not work great as we dont add `-g` on javac  by default.

```
 -g                           Generate all debugging info
  -g:{lines,vars,source}       Generate only some debugging info
  -g:none                      Generate no debugging info
```

we could add `-g` in a first fix, but might wanna have a way for users to specify: `none,lines,vars,source`.

Possibly: `jbang -g=none whatever` would be sufficient....just feels `-g` is quite non-informative.

**Comment by maxandersen** [comment]
discovered when vscode-jbang tried adding debugging: https://github.com/microsoft/vscode-java-debug/issues/1233

**Comment by garodriguezlp** [comment]
Hello @maxandersen, @quintesse! 

Did you check if this break the Kotlin compilation? I'm not 100% sure. But it looks like it does. 😅

**Comment by quintesse** [comment]
Hi @garodriguezlp , yeah somebody else noticed that as well: https://github.com/jbangdev/jbang/issues/1512
It's already been fixed, let's see if we can release it soon.

**Comment by kdubb** [comment]
@quintesse I'm using `0.110.0` and get the `-g` compile error with Kotlin. How do I fix this?

**Comment by maxandersen** [comment]
I'll release shortly. Otherwise use own build from main.

**Comment by maxandersen** [comment]
https://github.com/jbangdev/jbang/releases/latest is out
