### ISSUE TITLE
jbang not working with editor command containing spaces

### ISSUE THREAD

**Issue by zakkak** [jbangdev/jbang#1497]
**Describe the bug**
Using an editor command that includes spaces, e.g. to pass some flags to the editor, results in jbang failing to start the editor.

**To Reproduce**
```
jbang init test.java
jbang --verbose edit --open="emacs -q" test.java
```

**Expected behavior**
The editor should open like it does when the editor command contains no spaces.

**JBang version**
```
$ jbang version --verbose                         
[jbang] jbang version 0.99.1
Cache: /home/zakkak/.jbang/cache
Config: /home/zakkak/.jbang
Repository:/home/zakkak/.m2/repository
0.99.1
```

**Additional context**

Inspecting the verbose logs I see that it tries to run:
```
sh -c 'emacs -q' /home/zakkak/.jbang/cache/projects/test.java_jbang_f4678053209f27a8516ec2f3d31c665efd854f8d2af4453fcc9261c5303481aa/test
```

Which is AFAIK executed as `sh -c "'emacs -q' /home/zakkak/.jbang/cache/projects/test.java_jbang_f4678053209f27a8516ec2f3d31c665efd854f8d2af4453fcc9261c5303481aa/test"`
by the `ProcessBuilder`.

To my understanding `jbang` needs to trim the editor command before passing it to `sh`.

**Comment by maxandersen** [comment]
it is kinda of a known limitiation. 

Workaround is to put the command in a script and use that.

issue is how do you handle `jbang --verbose edit --open="/home/user/dir with a space/emacs -q" test.java` ?

can't just separate by space.

**Comment by zakkak** [comment]
Yes, that's exactly the issue I faced when trying to solve this :)

To me the expected behaviour would be for jbang to require escaped spaces for path names with spaces, e.g.:

`jbang --verbose edit --open="/home/user/dir\ with\ a\ space/emacs -q" test.java`

or require the path containing spaces to be quoted, e.g.:

`jbang --verbose edit --open="'/home/user/dir\ with\ a\ space/emacs' -q" test.java`

AFAIU this would be consistent with both the bash shell and the powershell.

**Comment by quintesse** [comment]
My first reaction is that his is a little too specific a use-case to merit the increase in parsing complexity. Remember that this is _quoting within quoting_! The current quoting handling is already way more complex that we want it to be, I for one am not looking forward to adding a minor feature like this at the cost of that much complexity.
