### ISSUE TITLE
Regression with GitHub repositories authentication

### ISSUE THREAD

**Issue by gsmet** [jbangdev/jbang#1504]
With JBang 0.97.0, I got the public GitHub repositories authentication working by:
- pushing the GITHUB_TOKEN secret to the action
- injecting it as an env var
- name the GitHub repository where my action is `github`
- the default `~/.m2/settings.xml` for the `github` pushes the secret as the password:

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>github</id>
      <username>${env.GITHUB_ACTOR}</username>
      <password>${env.GITHUB_TOKEN}</password>
    </server>
  </servers>
</settings>
```

With the latest version, this setup no longer works and I get a 401 Unauthorized error when JBang tries to get the artifact from the GitHub (not so) public repository.

The setup of the action:
https://github.com/gsmet/github-action-playground/blob/main/action.yml
(see how I installed JBang 0.97.0 or latest via SDKMAN!)

The workflow using the action:
https://github.com/gsmet/github-action-playground-target/blob/main/.github/workflows/publish-image.yml#L39-L44

A working workflow using 0.97.0 (only the Linux build is supposed to work as my dirty SDKMAN! install only works on Linux):
https://github.com/gsmet/github-action-playground-target/actions/runs/3395475566/jobs/5645406665

A failing workflow using latest:
https://github.com/gsmet/github-action-playground-target/actions/runs/3395508036/jobs/5645479380

**Comment by maxandersen** [comment]
@quintesse something we missed when moving from shrinkwrap to aether raw ?

**Comment by maxandersen** [comment]
Might just be we don't interpolate that ${} value.

**Comment by quintesse** [comment]
That's definitely possible. But handling of the settings.xml file is done internally by Aether itself (we just tell it what file to read). But perhaps it needs some kind of special invocation to enable it. I've done a quick search but haven't been able to find anything. I'd need to spend more time on this.

**Comment by maxandersen** [comment]
I can confirm that env variables does get interpolated, so it is something different.

**Comment by maxandersen** [comment]
ok, figured out the root cause.

We explicitly create RemoteRepos where we skip what the Session has of auth settings meaning it completely ignores the auth settings.

Surprised if any auth actually works :/


proxies etc. is resolved lazily so that seem to work.

**Comment by quintesse** [comment]
That's how I've seen it done in all the examples.
And we actually had people test the authentication bit, it was after all the main reason why we started this refactor in the first place.
So I'm not sure if this is a special case or not.

**Comment by maxandersen** [comment]
I'll need to test gitlab private auth that is headers based but at least for GitHub with username and password the auth field of repository is always null without my fix.
