### ISSUE TITLE
Copr Error: This repository does not have any builds yet so you cannot enable it now.

### ISSUE THREAD

**Issue by murphye** [jbangdev/jbang#1511]
**Describe the bug**
See the error message below. I am using Rocky Linux 9, if that matters.

```
sudo dnf copr enable @jbangdev/jbang 
[sudo] password for eric: 
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/@jbangdev/jbang? [y/N]: y
Error: This repository does not have any builds yet so you cannot enable it now.
```

**Comment by maxandersen** [comment]
Hmmm...that should just work. Need to check what stopped it.

**Comment by maxandersen** [comment]
any idea what builds rocky linux 9 needs?  see https://copr.fedorainfracloud.org/coprs/g/jbangdev/jbang/ for what we already have.

**Comment by murphye** [comment]
Looks like builds are failing which jives with error message.

https://copr.fedorainfracloud.org/coprs/g/jbangdev/jbang/builds/

**Comment by quintesse** [comment]
It seems the PPC builds are failing.

**Comment by maxandersen** [comment]
Yea the failures are in obscure platforms. Unless @murphye has a PowerPC?

**Comment by murphye** [comment]
PowerPC... I wish ;-). 

I am running an Intel Xeon :-) 

Rocky is RHEL 9 binary compatible and I have not had any issues with any of the repos when it comes to installing RPMs.

That being said, this is my first time ever using Copr.

**Comment by maxandersen** [comment]
I'm by far also not copr expert but just to show it does work (at least for Fedora) - here is me using it on fedora

```
 sudo dnf copr enable @jbangdev/jbang
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/@jbangdev/jbang? [y/N]: y
Repository successfully enabled.
[root@55ad346241af /]# dnf install jbang
Copr repo for jbang owned by @jbangdev
```

**Comment by maxandersen** [comment]
that said i can confirm that from rockylinux I get same error as you.

**Comment by murphye** [comment]
I wonder if you would get the same error on RHEL 9 as well?

**Comment by maxandersen** [comment]
Probably. I earlier today activated some additional epel builds. 

They should be complete now. Can you try again ?

**Comment by murphye** [comment]
Yes, that did the trick!
