### ISSUE TITLE
Universally adding '-g' to the compiler invocation breaks kotlin scripts

### ISSUE THREAD

**Issue by evanchooly** [jbangdev/jbang#1512]
kotlinc doesn't support a `-g` flag so kotlin scripts can't be compiled.

**Comment by maxandersen** [comment]
How does debugging symbols work for kotlin?

**Comment by evanchooly** [comment]
It looks like kotlinc includes them by default.  There's no explicit flag for (except for `kotlinc-native` which is a different binary). The only hits I get for it are how to remove them.

**Comment by maxandersen** [comment]
so no option/way to remove debug symbols?

**Comment by evanchooly** [comment]
I don't see anything obvious.  as i dug in to the hits i did find on google they were all about remove LOG.debug() calls more than anything else.
