### ISSUE TITLE
JBang manual installation doesn't work out of the box on a fresh Windows 10 installation: The system cannot find the path specified

### ISSUE THREAD

**Issue by mikoskinen** [jbangdev/jbang#1520]
**Describe the bug**

I'm testing JBang using Windows 10's Sandbox feature so this is a fresh Windows 10 without anything installed before. JBang works but there are some issues getting things started. Instead of working jbang I get _The system cannot find the path specified._

**To reproduce:**

1. Download the 0.101.0 release from https://github.com/jbangdev/jbang/releases/tag/v0.101.0 
2. Extract the files from zip's bin-folder to c:\temp\jbang
3. Start command prompt and go to c:\temp\jbang
4. Type jbang

Expected result: Java 11 is automatically installed and things work.

Result:

> powershell -NoProfile -ExecutionPolicy Bypass -NonInteractive -Command "C:\temp\jbang\jbang.ps1 jdk install "           
> The system cannot find the path specified.                                                                              
> The system cannot find the path specified.        

Now if I manually run the powershell command from the same command prompt:

powershell -NoProfile -ExecutionPolicy Bypass -NonInteractive -Command "C:\temp\jbang\jbang.ps1 jdk install 11"

I get:

> Downloading JDK 11. Be patient, this can take several minutes...

And then the report that JDK has been installed and now if I type jbang, I get:

> jbang is a tool for building and running .java/.jsh scripts and jar packages.

And I can install apps etc. and everything seems to be working.

![image](https://user-images.githubusercontent.com/143570/204078433-398dae30-4764-4197-a2dc-9fc83624fef7.png)

**Comment by maxandersen** [comment]
Does the error happen again if you delete ~/.jbang and run the script again ?

**Comment by mikoskinen** [comment]
Thanks for the question. Yep, the error happens again:

![image](https://user-images.githubusercontent.com/143570/204711336-11e53844-7b28-4b63-95fc-4cc134a54ff8.png)

**Comment by mikoskinen** [comment]
I tested some previous versions by downloading the artifacts, unzipping them and executing jbang. This is again Windows Sandbox, using the default Command Prompt. I downloaded the versions semi randomly:

0.101.0: Doesn't work
0.96.1: Doesn't work
0.87.0: Doesn't work
0.56.0: Works

So I then went through some commits and tested more versions:

0.81.1: Works
0.82.1: Doesn't work

Maybe caused by this: https://github.com/jbangdev/jbang/commit/fe08627b9d2448855e67c10f0ff09a5119ad9cda

**Comment by mikoskinen** [comment]
Actually I think the issue is simply that the powershell command for installing jdk has been echoed out. I created a PR which removes the echo.

**Comment by quintesse** [comment]
So the actual cause was this: https://github.com/jbangdev/jbang/pull/1038/commits/f30b47c2f7818e3a9208cc7d7217282b57e4a721#diff-2ad55f7d842df32728cb021b489809bb13010988731de9867b7fa886864d8a3bR53 and you're absolutely right that that echo shouldn't be there! Good catch!

**Comment by maxandersen** [comment]
well that explains a lot of mysterious reports - thanks @mikoskinen !
