### ISSUE TITLE
`jbang app setup` detection is not reliable

### ISSUE THREAD

**Issue by fbricon** [jbangdev/jbang#1524]
Had an issue trying to install a jbang app. Following the instructions I ran:

> ➜ jbang app setup
[jbang] JBang environment is already set up.

But my app couldn't be found. Turns out `.jbang/bin` was not added to the path, because I had this comment in my .zshrc:
```bash
# export JBANG_EDITOR=code
```

and dev.jbang.cli.App.java's check is pretty naive: 
https://github.com/jbangdev/jbang/blob/ff431883d46baaa582ed6b6379a8e5aae069a8d9/src/main/java/dev/jbang/cli/App.java#L465

**Comment by quintesse** [comment]
It's indeed naive, but at the same time it's pretty hard to come up with something that will always work. So the moment we encounter anything mentioning "jbang" in a comment line we assume _something_ has been added at some point and we shouldn't try again. In this case it's obvious that you as a user have changed things related to JBang in your config and we therefore assume that we should leave things alone.

There's always the `--force` option to bypass that check and just add those lines anyway. We could perhaps mention that option in the warning message, as we do for some other commands that have a force option.

**Comment by fbricon** [comment]
yeah I don't think trying to be more clever will cover all uses cases, but improving the documentation would certainly help

**Comment by quintesse** [comment]
You up for creating a PR for this perhaps? 🙂

**Comment by quintesse** [comment]
PR merged. Closing.
