### ISSUE TITLE
app install --name doesnt work

### ISSUE THREAD

**Issue by ennishol** [jbangdev/jbang#1531]
app install --name doesnt work

**To Reproduce**
1.`jbang app install --fresh --force --native --name=killport kill@quarkusio`
```
[jbang] Resolving dependencies...
[jbang]    info.picocli:picocli:4.6.3
[jbang]    org.zeroturnaround:zt-exec:1.12
[jbang]    org.slf4j:slf4j-simple:1.7.30
[jbang] Dependencies resolved
[jbang] Building jar...
[jbang] Command installed: killport

```
2. `cat ~/.jbang/bin/killport`
`#!/bin/sh
exec jbang run --native kill@quarkusio "$@"`

3.` killport -p 8080`
`Error: Could not find or load main class kill
Caused by: java.lang.ClassNotFoundException: kill`

allias installed with --name param should work according to
https://www.jbang.dev/documentation/guide/latest/install.html

**Comment by ennishol** [comment]
btw, without --native param it is working as expected

**Comment by maxandersen** [comment]
hmm, seems like native is not passed to the build. good catch. thats a bug.

**Comment by kanha-gupta** [comment]
@maxandersen Hi, i need some direction to approach this issue

**Comment by maxandersen** [comment]
I haven't looked but find in Alias Add command where --native gets passed in and make sure before it calls build it has native boolean passed in.

**Comment by kanha-gupta** [comment]
@maxandersen hey i've submitted a PR
https://github.com/jbangdev/jbang/pull/1547

**Comment by quintesse** [comment]
PR merged. Closing.
