### ISSUE TITLE
Incorrect handling of arguments with space/metachars

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#154]
If you run JBang with single quoted arguments to prevent special processing taking place then things go wrong once the first processing phase hsa finished and the actual Java commands get executed.

Eg the command `jbang echo.java 'foo *' bar` should result in `echo.java` being called with two arguments: `foo *` and `bar`, but instead it receives those 2 plus the entire list of iles that happen to be in the current directory.

This is because in the final command that gets executed the arguments are not quoted at all. This problem also exists for any other meta-characters like redirection or variables etc etc

On Linux/Mac the suggestion is to single quote *all* arguments passed by the user to prevent any extra special processing taking place (that should already have been handled by the user's shell when they started JBang).

On Windows it's a bit more complicated but can be summarized by:

 1. Double quote all arguments with `^"` (not simply `"`)
 2. Then within the string escape all metacharacters (`(`, `)`, `%`, `!`, `^`, `"`, `<`, `>`, `&`, `|`) using `^` (including `^` itself `^^`)
 3. Except for double quotes which need to be escaped like this: `\^"`

**Comment by maxandersen** [comment]
there is also https://github.com/jbangdev/jbang/issues/157

**Comment by maxandersen** [comment]
this is still borked on linux/mac.

**Comment by maxandersen** [comment]
fixed in the #155 thus that is awesome :)
