### ISSUE TITLE
Make `info tools` download JDKs again

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#1569]
After a heated discussion it was decided to again download JDKs when using `info tools`

**Comment by fbricon** [comment]
will "availableJdkPath" always be set? Whether it downloads a JDK or uses a non-JBang managed one

**Comment by quintesse** [comment]
> will "availableJdkPath" always be set? Whether it downloads a JDK or uses a non-JBang managed one

That's the idea, yes.

**Comment by quintesse** [comment]
Well, there's one caveat. It will show what Jbang would use to build or run that script. But there are cases where Jbang itself doesn't know where the JDK is installed!

An example is a system JDK on a Mac. Jbang knows it's in the PATH and it knows what version it is, but there's just no easy way to detect where that JDK is actually installed. So let's say the script says `//JAVA 14+` and that system JDK is version 16 then Jbang _will_ use that JDK (by simply running `java` or `javac` without any path) but `info tools` will be unable to show the path to that JDK.

Btw, the old `info` wouldn't show anything in that case either. In fact the current `info` should do a better job of finding the paths to JDKs than older versions.

**Comment by fbricon** [comment]
I think it's fine if we can't know the location of a JDK found on the PATH. We already fallback to using whatever is available in the Eclipse (or IDEA) instance in that case.
