### ISSUE TITLE
JBang default to run with Java 17?

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1582]
### Discussed in https://github.com/jbangdev/jbang/discussions/1088

<div type='discussions-op-text'>

<sup>Originally posted by **maxandersen** November 22, 2021</sup>
Currently jbang defaults to Java 11 if no other java found.

Should we move it up to Java 17 ? 

Reasons for: 
  records and multi line strings are super useful when writing scripts and utilities

Reasons against:
gradle still seem to suck when running under Java 17 so jbang edit experience aint great
many(?) libraries still have challenges with Java 17 due to the enforced locked down jdk.

Because if reasons against i'm leaning on staying on Java 11 but I wish someone could 
convince me otherwise.

Thoughts?</div>

**Comment by maxandersen** [comment]
lets make the default jbang fetches if nothing else installed be 17.

jbang should though still work and run on java 8.

**Comment by maxandersen** [comment]
mainly to increase likelihood for windows to work #1575 

when changing this need to ensure the jbang edit gradle will work on java 17.

**Comment by quintesse** [comment]
I think it's a good idea that JBang installs a modern Java version (LTS) by default. We have to go with the times and show people what's available. If we encounter any problems we'll try to find solutions or workarounds and as a final fix there's always the possibility to install/depend on older Java versions. And we make that very easy.
