### ISSUE TITLE
update with brew to v 0.106 fails

### ISSUE THREAD

**Issue by ThomasStuetz** [jbangdev/jbang#1606]
==> Downloading https://github.com/jbangdev/jbang/releases/download/v0.106.0/jbang-0.106.0.z
curl: (22) The requested URL returned error: 404

Error: jbang: Failed to download resource "jbang"
Download failed: https://github.com/jbangdev/jbang/releases/download/v0.106.0/jbang-0.106.0.zip

Can you please add this file.
Thank you for your good work
Tom

**Comment by maxandersen** [comment]
Yes. Seems there was a failure to publish the version specific artifacts. Will need to do a rebuild.

**Comment by maxandersen** [comment]
0.106.1 released - and it has the right zip uploaded.

should fix brew soon!
