### ISSUE TITLE
jbang alias list https://registry.quarkus.io results in unnecessary lookups

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1608]
after https://.../jbang-catalog.json has been checked and failed we spent N more requests against github/bitbucket which is definitely not needed for http.* urls.

**Comment by maxandersen** [comment]
this makes quarkus cli super slow at syncing as it takes 2+ seconds to decide there is no catalog

**Comment by quintesse** [comment]
URLs really aren't allowed here so the solution to this problem would be to show an input validation error
