### ISSUE TITLE
when generated command line gets too big use @-files when calling java/javac

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#161]
Java supports passing files with arguments using the `@` sign. JBang also supports this because of Picocli, but we need to support this when we call out to Java. Because on Windows the size of the command line is limited. This means on WIndows a user could pass a gazillion arguments to JBang using an @-file and that wouldn't work the moment we try to pass those on to the generated Java command.

**Comment by maxandersen** [comment]
jbang does that already afaik.

```
  ~/code/personal/jbang/itests   master ?6 ·······················································································
❯ echo helloworld.java Tako > args.txt
  ~/code/personal/jbang/itests   master ?7 ·······················································································
❯ jbang @args.txt
[jbang] Building jar...
Hello Tako
```

or did you mean when we call out to java we should use @ to pass args to java ?

**Comment by quintesse** [comment]
Updated title and description.

**Comment by maxandersen** [comment]
ack on having a `if (arglength > whateverlimitunderlyingoshas) call using @-files` ...

**Comment by quintesse** [comment]
The only downside is that we wouldn't have a way to clean up after ourselves. But if we only use it for those cases where we exceed those limits it should hopefully not happen too often.

**Comment by maxandersen** [comment]
we could "garbage collect" them from time to time ;) "delete files in ~/.jbang/launchcache/ that are >24hrs old" or something ;)

**Comment by maxandersen** [comment]
updated title - I wonder what the lmits actually are if there even are a usecase that will hit them...is't windows like 8K these days ?

**Comment by quintesse** [comment]
Remember the PR I created for Graal (https://github.com/oracle/graal/pull/2443)? That was _exacty_ this problem. So people do encounter this "in the wild".

**Comment by maxandersen** [comment]
Yes, but if your jbang scripts have as many dependencies as a full blown enterprise app you are asking for troubles :) 

As said, if we can figure out the exact limits when argfile approach is necessary + an actual usecase to test against then I'm fine adding it....

**Comment by quintesse** [comment]
Well it doesn't need to be dependencies, you just have to pass 8K in arguments (The Graal native compiler for example passes all classes it compiles by name, which is why it gets to such ridiculous lengths).

And 8K seems to be the best answer looking at things like: https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation and: https://stackoverflow.com/a/57036194/2889926

**Comment by quintesse** [comment]
Was fixed by https://github.com/jbangdev/jbang/commit/6310bbd44712ac9269376bb76e885c842fbcd667
