### ISSUE TITLE
jbang jdk java-env command return wrong path separator in PowerShell

### ISSUE THREAD

**Issue by tomazzupan** [jbangdev/jbang#1611]
**Describe the bug**
In PowerShell command `jbang jdk java-env` return wrong path separator (:) instead of  (;). For instance it returns
`$env:PATH="C:\Java\openJDK\zulu17.40.19-ca-jdk17.0.6-win_x64\bin:$env:PATH"`

but should be

`$env:PATH="C:\Java\openJDK\zulu17.40.19-ca-jdk17.0.6-win_x64\bin;$env:PATH"`

**To Reproduce**
1. Open PowerShell console
2. Execute command `jbang jdk java-env`
3. Returned command for `PATH` environment  variable has wrong path separator

**JBang version**
0.105.2

**Comment by quintesse** [comment]
Confirmed. Thanks for bringing this to our attention @tomazzupan !

**Comment by quintesse** [comment]
A fix for this has been created #1613
