### ISSUE TITLE
jbangdev/jbang-action - Release 0.107.0

### ISSUE THREAD

**Issue by davsclaus** [jbangdev/jbang#1624]
https://hub.docker.com/r/jbangdev/jbang-action/tags

The last tag is 0.106.1
Can we have a release for 0.107.0

**Comment by maxandersen** [comment]
Hmm. Something must have gone wrong in the publishing. It's all automatic. Or at least supposed to be. 

I'm without laptop this weekend so will have to wait to Monday :/
