### ISSUE TITLE
Piped input

### ISSUE THREAD

**Issue by blsouthr** [jbangdev/jbang#164]
would it be possible to add support for piped input?
this works:
```console
./hello.java Stranger
```
but not this
```console
echo Stranger | ./hello.java
```

**Comment by maxandersen** [comment]
What do you have in your hello.java?

**Comment by maxandersen** [comment]
I just tried using this basic class:

```
//usr/bin/env jbang "$0" "$@" ; exit $?
// //DEPS <dependency1> <dependency2>

import static java.lang.System.*;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class hellopipe {

    public static void main(String... args) throws IOException {
        
        BufferedReader in = null;
    try {
        in = new BufferedReader(new InputStreamReader(System.in));
        String line;
        while ((line = in.readLine()) != null) {
            System.out.println(line);
        }
    }
    catch (IOException e) {
        System.err.println("IOException reading System.in " + e);
        throw e;
    }
    finally {
        if (in != null) {
            in.close();
        }
    }
    
    }
}
```

and with that I can do `echo stranger | jbang hellopipe.java`, `echo stranger | ./hellopipe.java` or `./hellopipe.java < somefile.txt`

are you seeing different behaviour ?

**Comment by blsouthr** [comment]
Thanks! Your example works. I just though it might also work with piccoli, i.e. for standard generated 
```console 
jbang init --template=cli hello.java
```

maybe new option --template=clireadline ?

**Comment by maxandersen** [comment]
Its worth noting that reading from input and parsing commad line options are two very different things.

if you can think of a additional template that you think others can benefit from feel free to contribute something similar to https://github.com/jbangdev/jbang/blob/master/src/main/resources/init-cli.java.qute

basically any `init-<templatename>.java.qute` will be used by `--template<templatename>`

I'll close this isse for now but feel free to open PR/issue to improve in this area.
