### ISSUE TITLE
Allow `jbang --debug` to connect to a debugger

### ISSUE THREAD

**Issue by danberindei** [jbangdev/jbang#1640]
**Is your feature request related to a problem? Please describe.**

I'd like to run JBang so it connects to a debugger that is listening for incoming connections. 
The main advantage over JBang listening for a connection from a debugger is that in IntelliJ I can check "Auto restart" in the remote debug configuration, and a new debug session will start automatically every time I re-run the jbang script.

**Describe the solution you'd like**

When I run `jbang --debug=server=n,address=localhost:5005`, JBang should connect to my IDE listening on port 5005 instead of trying to listen on port 5005 itself.

It would also be nice to get a description of the `--debug` arguments in `jbang --help`.

**Describe alternatives you've considered**

I can keep using `server=y` and start the debugger manually every time I run the script.

Or there may be an enviromnent variable that gives me finer control over the debug arguments.

**Comment by maxandersen** [comment]
Waaat? Where in your ide do You enable Listening?

**Comment by maxandersen** [comment]
Cool. Got it working. Never noticed that feature but for sure makes sense. It's a shame it blocks the port and can't run multiple debug sessions this way. 

But yeah @quintesse suggested we allow doing:  

-debug=server=n,address=localhost:5005

But also

-debug=server=n

Or any other combo of CSV values and thus let you tweak the common default avoiding repeating the common values repeatedly.

**Comment by danberindei** [comment]
Sorry, I missed your question! Happy you got it working anyway.

It is indeed a shame that the debugger doesn't accept a second connection and it doesn't close the server port either, but with the auto-restart option it's still a win when doing lots of iterations on a script (or as I used to use it, running a test suite repeatedly and using conditional breakpoints to debug flaky tests).

**Comment by maxandersen** [comment]
Yes. It's now available in jbang latest release.
