### ISSUE TITLE
revise syntax for main class designation

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#166]
after implementing support for doing `jbang info.picocli:picocli-codegen:4.2.0/picocli.codegen.aot.graalvm.ReflectionConfigGenerator` I realised that specifying the main class that way doesn't work for plain jar based launches, ie. `jbang helloworld.jar/blah.main` will fail as no (good) way to know `/blah.main` is not the intended file.

my first thought is to add a `--main` or similar flag; would also make it much more explicit and code simipler to be honest. 

@quintesse wdyt?

**Comment by quintesse** [comment]
Yes, I think that would be a good idea. For a moment I thought about using `#`, which is a typìcal thing for UIRLs. But I prefer being explicit with a flag.

**Comment by maxandersen** [comment]
# is treated as a comment in bash thus it will just cancel out everything else.

**Comment by quintesse** [comment]
Yeah, you'd have to quote the entire argument. So a flag is just better in every way IMO. 👍

**Comment by maxandersen** [comment]
done; `-m/--main` now forcefully overrides any main class "calculation" for jar or script running...
