### ISSUE TITLE
The JDK version installed by JBang at the time of installation of JBang itself

### ISSUE THREAD

**Issue by aghasemi** [jbangdev/jbang#1676]
When installing JBang, if it cannot find a JDK installed on the system, it tries to install the latest LTS release (right?). Is there a way to customise that, so that it installs a "given" version instead if it does not find any on the system?

Thanks

**Comment by quintesse** [comment]
Yes, there is, you can set `JBANG_DEFAULT_JAVA_VERSION`, it's explained here: https://www.jbang.dev/documentation/guide/latest/usage.html

**Comment by aghasemi** [comment]
It seems this variable is ignored when installing JBang itself, or am I doing something wrong?

![image](https://github.com/jbangdev/jbang/assets/7351535/dbc5b05c-316b-4798-a121-920fceab55ec)

**Comment by quintesse** [comment]
If you're using it like that I think the variable is only applied to the first command (the `curl`). Try using:

```
JBANG_DEFAULT_JAVA_VERSION=21 ( curl ... | bash ... )
```

I haven't tested this myself, so I'm not sure if this is the correct syntax.
As a last resort you could use a separate `export JBANG_DEFAULT_JAVA_VERSION=21` command before running the curl/bash command.

**Comment by aghasemi** [comment]
Ah, it worked now. Many thanks for the tricky tip.

**Comment by quintesse** [comment]
Glad to be of help!

Btw, I just realized that this would probably have worked as well:

```
curl ... | JBANG_DEFAULT_JAVA_VERSION=21 bash ... 
```

**Comment by aghasemi** [comment]
> Glad to be of help!
> 
> Btw, I just realized that this would probably have worked as well:
> 
> ```
> curl ... | JBANG_DEFAULT_JAVA_VERSION=21 bash ... 
> ```

Yes. Actually, this is the one that worked for me, not the parentheses (Ubuntu 22.04).
