### ISSUE TITLE
Cannot download Java 21 

### ISSUE THREAD

**Issue by aghasemi** [jbangdev/jbang#1681]
**Describe the bug**
Probably a very temporary situation given Java 21 was released today, but still you may want to now the following link returns 404 now: 
https://github.com/adoptium/temurin21-binaries/releases/download/jdk21-2023-09-01-15-41-beta/OpenJDK21U-jdk_x64_linux_hotspot_2023-09-01-15-41.tar.gz

**To Reproduce**
1. Run a script with `//JAVA 21`
2. See error

**Expected behavior**

**JBang version**
```
[jbang] [0:545] jbang version 0.110.1
Cache: /root/.jbang/cache
Config: /root/.jbang
Repository:/root/.m2/repository
0.110.1
 ```
**Additional context**

**Comment by maxandersen** [comment]
Damn. Yeah - happens on every major release of java - there are a few days of no download :/

**Comment by aghasemi** [comment]
Just an update that the link is still broken :)

**Comment by maxandersen** [comment]
Yeah. I thought it was fixed but seems foojay has issues. We've reported it.

**Comment by maxandersen** [comment]
this is now fixed - it is still 21 early access builds due to https://adoptium.net/blog/2023/09/temurin21-delay/ but its as good as it gets.

```
 eval $(jbang jdk java-env 21)
JAVA_HOME is set but does not seem to point to a valid Java JDK
[jbang] Downloading JDK 21. Be patient, this can take several minutes...
[jbang] Installing JDK 21...
❯ java --version
openjdk 21-beta 2023-09-19
OpenJDK Runtime Environment Temurin-21+35-202309042140 (build 21-beta+35-ea)
OpenJDK 64-Bit Server VM Temurin-21+35-202309042140 (build 21-beta+35-ea, mixed mode)
```

**Comment by aghasemi** [comment]
Yes, wanted to comment here. Thanks for the update. Anyways the Java 21 support for VSCode Java Extension is still pending, so not much work to do.

**Comment by maxandersen** [comment]
It will be there soon...

**Comment by aghasemi** [comment]
It seems we now have the LTS 21 version. Thanks.
