### ISSUE TITLE
Custom debug port not taken into account

### ISSUE THREAD

**Issue by essobedo** [jbangdev/jbang#1689]
**Describe the bug**
When a custom debug port is provided thanks to the parameter `--debug`, the port `4004` is still used.

**To Reproduce**
1. Execute `jbang init helloworld.java`
2. Launch it with `jbang --debug 5000 helloworld.java`
3. Result:
```
Listening for transport dt_socket at address: 4004
```

**Expected behavior**
The port `5000` should be used instead of the default port `4004`

**JBang version**
```
[jbang] [0:323] jbang version 0.111.0
Cache: /Users/nicolasfilotto/.jbang/cache
Config: /Users/nicolasfilotto/.jbang
Repository:/Users/nicolasfilotto/.m2/repository
0.111.0
```

**Comment by maxandersen** [comment]
was introduced in https://github.com/jbangdev/jbang/commit/d87feaa96419fa88c2f934bf2478002c9a6de084 - no idea how I could have missed that the port was always overriding it all.
