### ISSUE TITLE
Where does JBang look for proxy information when downloading JDKs?

### ISSUE THREAD

**Issue by aghasemi** [jbangdev/jbang#1694]
Hi,

My JBang installation works fine with proxy when downloading Maven dependencies, but not when downloading JDKs. The proxy is specified in both `~/.m2/settings.xml` and `http_proxy` (and related) environment variables. Is there a third place JBang expects to see proxy? 

Many thanks

**Comment by gwentey** [comment]
Same issue here...

**Comment by maxandersen** [comment]
Hmm. For http download it uses standard java httpd so the system properties should work?

**Comment by aghasemi** [comment]
http_proxy or HTTP_PROXY?

**Comment by maxandersen** [comment]
jbang -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128

**Comment by quintesse** [comment]
Also important to know which OS you're using. Not all OSes use the same system to set up proxies.

**Comment by gwentey** [comment]
jbang -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128
with this we can't put credentials (username@password)

**Comment by maxandersen** [comment]
I don't have access to a proxy that requires authentication. What do you normally do for java apps to have this work?

**Comment by maxandersen** [comment]
Tried `Dhttp.proxyHost=myproxy -Dhttp.proxyPort=myport -Dhttp.proxyUser=myuser -Dhttp.proxyPassword=mypass -Dhttps.proxyHost=myproxy -Dhttps.proxyPort=myport -Dhttps.proxyUser=myuser -Dhttps.proxyPassword=mypass`

?

Note: afaik none of this is jbang specific. Just standard java proxy config.

**Comment by quintesse** [comment]
Those options don't seem to work for me (see #1695)

**Comment by gwentey** [comment]
I tried options don’t work too for me

**Comment by DyspC** [comment]
Hello, 

I was looking into an issue like this when downloading remote scripts but looking into the code it appears the JBangJdkProvider and RemoteResourceResolver use the same utility class so I'll report here

https://github.com/jbangdev/jbang/blob/d8b8bb4613f6b07b6601f148a56c2f9faf5d301c/src/main/java/dev/jbang/util/Util.java#L800

The download process uses the `URL::openConnection` method that IIRC does not use any other proxy than the one it's fed 

Hardcoding it and rebuilding jbang locally fixes it for me so it would be great if this proxy was somehow configurable

```java
		URL url = new URL(fileURL);
		Proxy proxy = new Proxy(Proxy.Type.HTTP, InetSocketAddress.createUnresolved("localhost", 3128));
		URLConnection urlConnection = url.openConnection(proxy);
		configurator.configure(urlConnection);
```

**Comment by maxandersen** [comment]
I'm surprised as the testing of proxy settings did make a difference. 

Maybe we miss a specific test and missed that path.

**Comment by maxandersen** [comment]
-Dhttpxxx settings should be listened to in that connection. Are you saying setting those properties have no effect for you?

**Comment by DyspC** [comment]
> -Dhttpxxx settings should be listened to in that connection. Are you saying setting those properties have no effect for you?

Yeah pretty much, I'm actually putting them anyway (http.proxyHost and http.proxyPort) because my script is a light CLI for a specific part of an API so I need them in the script, I also tried setting java.net.useSystemProxies to true and that didn't help either

**Comment by aghasemi** [comment]
MacOS here as well.

**Comment by maxandersen** [comment]
okey so i went a bit deep and realized our docs/comment on this have been to imprecise.

PR here https://github.com/jbangdev/jbang/pull/1700/files to improve the current docs.

basically you must export or set the properties in JAVA_TOOL_OPTIONS to work AND have proxies configured in settings.xml 

ie. `export JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=tinyproxy -Dhttp.proxyPort=8888 -Dhttps.proxyHost=tinyproxy -Dhttps.proxyPort=8888` before running jbang env@jbangdev.

you also need to set env vars if you want curl/bash settings to get pickedup.

Please see the PR and see if you can make that work - if not then I would love to know.

**Comment by maxandersen** [comment]
going to close this as all documented now. do comment or open new issue if still problems.
