### ISSUE TITLE
JBang does not trust http sources

### ISSUE THREAD

**Issue by DyspC** [jbangdev/jbang#1696]
**Describe the bug**

Running `jbang http://my.server/static/script.jsh` always says the url is untrusted

Selecting 2 to add the domain to trusted sources adds 'http://my.server/static/' to the trusted array (or says it's already present)

**To Reproduce**
1. Expose a script on an unsecure http remote
2. Try to run it

**Expected behavior**
The user should not be asked again and again to add an already trusted source

**JBang version**
```
[jbang] [0:349] jbang version 0.110.1
Cache: /home/Clement.Descamps/.jbang/cache
Config: /home/Clement.Descamps/.jbang
Repository:/home/Clement.Descamps/.m2/repository
0.110.1
```

**Additional context**
I suppose this is because the trust evaluation prefixes it with "https://" and messes the URI parser

```java
			URI parsedTrustedSource;
			if (trustedSource.startsWith("https://")) {
				parsedTrustedSource = new URI(trustedSource);
				if (!url.getScheme().equals(parsedTrustedSource.getScheme())) {
					continue;
				}
			} else {
				parsedTrustedSource = new URI("https://" + trustedSource);
			}

			if (url.getAuthority().equals(parsedTrustedSource.getAuthority())) {
				if (pathMatches(url.getPath(), parsedTrustedSource.getPath())) {
					return true;
				} else {
					continue;
				}
			}
```

```java
jshell> new URI("https://http://my.server/static/generate-software-secret.jsh").getPath()
$4 ==> "//my.server/static/generate-software-secret.jsh"

jshell> new URI("http://my.server/static/generate-software-secret.jsh").getPath()
$5 ==> "/static/generate-software-secret.jsh"

jshell> new URI("http://my.server/static/generate-software-secret.jsh").getAuthority()
$6 ==> "my.server"

jshell> new URI("https://http://my.server/static/generate-software-secret.jsh").getAuthority()
$7 ==> "http:"
```

**Comment by ritikverma2000** [comment]
Hi @DyspC  I would like to work on this issue.

**Comment by DyspC** [comment]
Hello, no problem!

**Comment by maxandersen** [comment]
yeah; seems like a simple fix of allowing http too...not sure why we even try add https:// if it does not start with https to start with.

@ritikverma2000 or @DyspC if either of you are up for it feel free to open a PR!

**Comment by ritikverma2000** [comment]
Hi @DyspC can you pls check this pull request once. I have done the required code fix. 
https://github.com/jbangdev/jbang/pull/1698

**Comment by quintesse** [comment]
Fixed by https://github.com/jbangdev/jbang/pull/1698
