### ISSUE TITLE
Extend Catalog system with implicit catalogs

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#172]
Right now Catalogs need to be explicitly added. This issue is for introducing "implicit catalogs" where, if the user tries to run `some-alias@some-catalog` and the "some-catalog" is not defined Jbang will look in some predefined places to see if that catalog exists.

Where to look? Well `some-catalog` can either be an `organization/repository` pair which will look for a `jbang-catalog.json` file in the root of that repository on either GitHub, GitLab or BitBucket. Or it can simply be the `organization` part and the repository will then be assumed to be "jbang-catalog".

To prevent having to go to the process of looking up repositories each time we should add the first successful lookup as an explicit Catalog. (So if `some-alias@some-catalog` does not exist, but looking up `some-catalog/jbang-catalog/jbang-catalog.sjon` on Github gives a result we should basically perform a `jbang catalog add some-catalog https://github.com/some-catalog/jbang-catalog/jbang-catalog.json` so any references to `some-catalog` will immediately resolve to the correct URL in the future)

**Comment by maxandersen** [comment]
yeah, my thinking was like here on implicit lookup and positive match is found to just record explicit catalog....we do need to figure out how to handle updates...

maybe just to a http check to get Last-Modified header and if file date < url last-modified we redownload ?

**Comment by quintesse** [comment]
> we do need to figure out how to handle updates...

Well, isn't that what `jbang catalog update` is for?

**Comment by maxandersen** [comment]
sure...but if we can avoid users having to know that would be better imo ;)

**Comment by quintesse** [comment]
Dunno, I'm not a fan of auto-updating stuff tbh. That's why I like sdkman, it tells you there's new stuff but you still have to ask for it. You're the boss though :-)

**Comment by maxandersen** [comment]
Well, telling me there is an update would be good start :)

**Comment by quintesse** [comment]
This is now done. I decided to add branches as well. So you can do:

 - `jbang run alias@implicit`
 - `jbang run alias@implicit/jbang-catalog`
 - `jbang run alias@implicit/jbang-catalog/master`

And they'd all point to the same catalog.
