### ISSUE TITLE
Catalogue references to branches with / in them do not work

### ISSUE THREAD

**Issue by timfel** [jbangdev/jbang#1729]
The line [here](https://github.com/jbangdev/jbang/blob/cdbf260414fc596bcb2b18d41e8e9ee8fb981c16/src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java#L51) prevents refs with slashes in them (which are IME common in many projects) from being used as refs. This prevents the GraalPy catalogue from working

```bash
jbang hello@oracle/graalpython/release/graal-vm/24.0 "print(1*4)"
```

This should resolve https://raw.githubusercontent.com/oracle/graalpython/release/graal-vm/24.0/jbang-catalog.json, but it won't. I think the code should simple be
```diff
		} else {
			path = "";
		}
-		String[] names = parts[0].split("/");
+		String[] names = parts[0].split("/", 3);
-		if (names.length > 3) {
-			return null;
-		}
		String org = names[0];
		String repo;
		if (names.length >= 2 && !names[1].isEmpty()) {
```

**Comment by quintesse** [comment]
TBH I didn't know this was even possible. We'd have to make sure that this doesn't match other valid URLs but if not this seems like a simple fix.

**Comment by timfel** [comment]
> TBH I didn't know this was even possible. We'd have to make sure that this doesn't match other valid URLs but if not this seems like a simple fix.

What other valid URLs are you thinking of? It cannot match any other for github or gitlab, since those are used for the branch names.
