### ISSUE TITLE
Passing `--native-option=--verbose` doesn't work

### ISSUE THREAD

**Issue by zakkak** [jbangdev/jbang#1786]
**Describe the bug**
Native image supports building with `--verbose` option, but jbang refuses to accept it (probably because it conflicts with its own `--verbose` option) with:

```
$ jbang -n --native-option=--verbose Hello.java                                                                                             
Expected parameter for option '--native-option' but found '--verbose'
```

**To Reproduce**
```
jbang init Hello.java
jbang -n --native-option=--verbose 
```

**Expected behavior**
The native build should proceed with verbose logging (for the native image build) enabled

**JBang version**
```
$ jbang version --verbose                      
[jbang] [0:134] jbang version 0.116.0
```

**Comment by quintesse** [comment]
This actually seems to be an issue with PicoCli, investigating if we can somehow convince it to accept this.

**Comment by quintesse** [comment]
Ok, found the solution: https://picocli.info/#_enable_consuming_option_names_or_subcommands

**Comment by quintesse** [comment]
Ok, created a fix for this. Thanks for the issue @zakkak !

**Comment by zakkak** [comment]
Thanks for the quick fixes @quintesse !
