### ISSUE TITLE
Passing `-n --fresh` rebuilds the jar but not the native image 

### ISSUE THREAD

**Issue by zakkak** [jbangdev/jbang#1787]
**Describe the bug**
I would like to force a rebuild of the native image, but using `--fresh` doesn't seem to do the trick.

**To Reproduce**
```
jbang init Hello.java
jbang -n Hello.java
jbang -n --fresh Hello.java
```

**Expected behavior**
I would expect the native image for Hello.java to be built twice, but it only gets built the first time.

**JBang version**

```
jbang version --verbose                      
[jbang] [0:136] jbang version 0.116.0
```

**Comment by quintesse** [comment]
Thanks for bringing this to our attention @zakkak ! I've created a fix which will most likely be available in the next version.

**Comment by zakkak** [comment]
Thank you @quintesse !
