### ISSUE TITLE
jbang jdk default <version> fails on Windows

### ISSUE THREAD

**Issue by jcrben** [jbangdev/jbang#1793]
**Describe the bug**
Follow-up to https://github.com/jbangdev/jbang/issues/1574 by @quintesse 

This is when using "Git Bash" - and particularly the msys bash inside of it. 

This is what I see:

```
Ben@t480-ben dotfiles [master]$ jbang jdk default 21
[jbang] Creation of symbolic link failed C:\Users\Ben\.jbang\currentjdk -> C:\Users\Ben\.jbang\cache\jdks\21
[jbang] Now try creating a hard link instead of symbolic.
[jbang] Creation of hard link failed C:\Users\Ben\.jbang\currentjdk -> C:\Users\Ben\.jbang\cache\jdks\21
[jbang] [ERROR] Failed to create link C:\Users\Ben\.jbang\currentjdk -> C:\Users\Ben\.jbang\cache\jdks\21
[jbang] Run with --verbose for more details
```

**To Reproduce**
I'm running bash on Windows 10. `uname -a` reports `MSYS_NT-10.0-19045 t480-ben 3.4.7-25de8b84.x86_64 2023-08-28 21:32 UTC x86_64 Msys`

I reproduced this in Powershell IIRC but my main way of working in Windows is inside cygwin / msys.

I execute via the Windows Terminal - I configure a profile like this after installing Git via `winget install Git.Git`. I'm using `/Git/usr/bin/bash.exe` which has the cygwin dll included, but not sure that matters.

```
            {
                "commandline": "%PROGRAMFILES%/Git/usr/bin/bash.exe -i -l",
                "guid": "{00000000-0000-0000-ba54-000000000002}",
                "icon": "%PROGRAMFILES%/Git/mingw64/share/git/git-for-windows.ico",
                "name": "Bash",
                "startingDirectory": "%USERPROFILE%"
            },
````

```
scoop install jbang
jbang jdk install 21
jbang jdk default 21
```

**Expected behavior**
jbang jdk default 21 should succeed

**JBang version**
```
$ jbang version --verbose
[jbang] [0:425] jbang version 0.116.0
Cache: C:\Users\Ben\.jbang\cache
Config: C:\Users\Ben\.jbang
Repository: C:\Users\Ben\.m2\repository
0.116.0
```

**Additional context**
I don't think requiring Developer Mode is good - many people developing in Windows are doing it for security reasons and it's hard convince a security department to enable Developer Mode.

As noted earlier in the linked issue, you can't hard link to directories. But there's another option - use junctions instead. fnm did that recently https://github.com/Schniz/fnm/pull/519 - see also https://github.com/kubernetes-sigs/krew/issues/843

An example of creating a junction from my initial dotfiles setup script: `powershell.exe New-Item -ItemType Junction -Force -Path $(cygpath -m "$HOME/scoop/persist/vscode/data/user-data/User") -Target $(cygpath -m "$SCRIPT_DIR"/config/vscode/User)`

**Comment by jcrben** [comment]
I dropped into a debugger to see what was happening - fyi it skipped the if condition here which triggers the warning message.
![image](https://github.com/jbangdev/jbang/assets/5614134/3eab3bcd-aa77-4613-8d13-da93e1cc4ef4)

**Comment by quintesse** [comment]
Unfortunately I don't think there's an easy way to create junctions with Java, which is what we'd need.

**Comment by jcrben** [comment]
@quintesse for the junction question - to avoid Developer Mode in a place where it isn't permitted - what are your thoughts on just calling powershell or cmd.exe as an external process on Windows? would like to be able to use this in a secured corporate environment

if not, maybe I'll just fork it privately inside the secure environment and maintain  the forked version

**Comment by quintesse** [comment]
See https://github.com/orgs/jbangdev/discussions/1805
