### ISSUE TITLE
support "nearest" .jbang-catalog notion 

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#180]
Imagine this:

```
$ git clone https://github.com/quarkusio/awesomeproject
$ cd awesomeproject
$ jbang --verbose someautomationscript
Found alias `someautomationscript` in .jbang-catalog.
Running somescript.java
....
```

or 

```
$ cd somewhere
$ jbang --verbose asciidoctor
Found alias `asciidoctor` in `~/.jbang/jbang-catalog`
Running https://...
..
$ jbang --verbose someautomationscript
Found alias `someautomationscript` in .jbang-catalog.
Running somescript.java
....
```

idea is to support localized/nearest in parent alias's that you can use and have default configured in your folders / git projects.

...you can do some crazy things with this when you start thinking about it :)

This might want us to reconsider how the alias format is defined but I think this places nice into the idea of making jbang scripts super easy to consume and use.

could even work well with a  `./jbangw` (wrapper :) to "bootstrap"...

/cc @quintesse

**Comment by quintesse** [comment]
Sounds like a neat idea.

**Comment by quintesse** [comment]
Btw, personally I'd go for `.bang-catalog.json` if you _really_ want to make it hidden. At least it will be somewhat easier to edit. But why do you want to hide the file?
