### ISSUE TITLE
Allow extra classpath option in command line when running aliases

### ISSUE THREAD

**Issue by ivangsa** [jbangdev/jbang#1802]
**Is your feature request related to a problem? Please describe.**

I'm the maintainer of a CLI code generator that uses APIs (openapi, asyncapi) and other models as source input. These are often packed as GAV jars. The software can read these source inputs from the classpath as `classpath:/path/to/file` which is something it can do when running as a maven plugin.

This is very handy because users can generate code from APIs that are already packaged as GAV jars within the organization (without unpacking or downloading them)

I would like this to work also when run as a jbang alias.

**Describe the solution you'd like**

This example would add the extra classpath option to the alias own classpath.

`jbang --cp="./local/folder;com.acme:artifact:RELEASE" <alias name> [args]`

I would like also to control wether this extra classpath is appended or prepended.

If I could prepend `cp` to `deps` then I could use this technique to also override the software resources with custom local resources (like templates...)

**Describe alternatives you've considered**

I have considered using alias arguments to pass this extra classpath and then manually implement the managment of the classpath (most probably using jbang DependencyResolver classes)

**Additional context**

**Comment by maxandersen** [comment]
Doesn't --deps just work for you here ?

**Comment by ivangsa** [comment]
oh yes!! it works on the command line as well (and --cp also works)

It would be great if --cp and --deps from the command line would prepend entries to the overall classpath, in that way I could use it to override some resources (I'm not thinking about java classes)... but this may break existing usecases..

do you think it may be a way to prepend this entries instead of appending?

**Comment by quintesse** [comment]
@ivangsa we actually thought about this some time ago and decided not to bother because you can't override classes this way, but I hadn't thought about resources! We'll have to give this some thought but it's definitely an interesting use-case.

**Comment by maxandersen** [comment]
@ivangsa it is quite messy if we change to put classpath in front of the resolved dependencies.Z

we would need a --prepend--classpath or similar. That starts being very borderline useful IMO.

Can you try give more specific example where this is really required and you have no other better option?

**Comment by ivangsa** [comment]
> we would need a --prepend--classpath or similar. That starts being very borderline useful IMO.

I perfectly understand this

> Can you try give more specific example where this is really required and you have no other better option?

I have this [jbang catalog](https://github.com/ZenWave360/zenwave-sdk/blob/main/jbang-catalog.json), which is a CLI code generator where each jar entry contains java code an some templates

I would like users to be able to override a particular template, without packing a jar file with it, so the overriding template is just a plain file on the project..

Then they can create a local jbang-catalog.json like: 

```json
{
  "aliases": {
    "zw": {
      "classpaths": [
        "./custom-templates/"
      ],
     // all the remaining jar dependencies here, maybe pinned to a version
    }
  },
  "templates": {}
}
```

> no other better option?

- I can try adding an option on my CLI entry point and handling the classpath myself (I'm not sure how easy this would with modern jvm versions)
- Or for my usecase just playing with Handlebars template loader

I understand that this is quite a breaking change, and being able to pass --cp and --deps to the command line is a big step forward for my use case.

**Comment by ivangsa** [comment]
I'm closing this as complete. 
Being able to pass extra --deps and --cp to an alias is good enough (I mean great) for my usecase.
Thanks a lot for your help!
