### ISSUE TITLE
support --java 13+

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#182]
right now //JAVA 13 is *forcing* java 13 jdk to be used - which can be good in some cases. I think we should allow `//JAVA 13+` to indicate 13 or higher.

could even allow `//JAVA 13,14` or `//JAVA 11-14,16` in case there is a broken thing in java 15...but i can't think of a usecase thus for now lets start allowing `//JAVA <version>+` to state minimum version.

**Comment by quintesse** [comment]
The `+` is already implemented. Didn't I tell you that?

**Comment by maxandersen** [comment]
No you did'nt and it didn't worm when I tested. Will test again :)

**Comment by maxandersen** [comment]
it works! magic :)
