### ISSUE TITLE
add /usr/lib/jvm as a optional jdk location to search for preinstalled javass

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1825]
from https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/JBang.20failure/near/455967437 @sanne felt sad his already installed jdks via fedora dnf was not being found.

fedora (and possible other linux distros) install jvm's into `/usr/lib/jvm` which has subdirs for both jre's and jdk's but i think our base path provider already ensures it only picks up jdks.

thus should be fairly easy adding a UsrLibJvm provider...other is `/etc/alternatives` but here its intermixed with tons of others so might affect performance. Maybe have a Linux or Fedora provider that looks in /usr/lib/jvm first - then /etc/alternatives ?

**Comment by quintesse** [comment]
Definitely a good idea.
