### ISSUE TITLE
build-jdk burned into jar - should it be using 1.8 or 8 ?

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#183]
found in #178, build-jdk is burned into manifest but it is using 1.8 as opposed to 8...is that what we want/need?﻿

**Comment by quintesse** [comment]
It's an "official"· field, used by Maven for example. It's contents follows Java numbering conventions AFAICS, so Java 8 -> 1.8.

**Comment by quintesse** [comment]
See: https://www.baeldung.com/java-jar-manifest#3-maven

**Comment by maxandersen** [comment]
Excellent. Then it's all good!
