### ISSUE TITLE
Show used java version when asking for version

### ISSUE THREAD

**Issue by msangel** [jbangdev/jbang#1832]
Yes, mine feature related to problem.  Right now I have 4 different JAVAs on my computer, one was preintalled, 3 other I installed via [jabba](https://github.com/shyiko/jabba) (before I used [jenv](https://github.com/jenv/jenv) for the same):
```
✔ swift3:~> jabba ls
adopt@1.8.0-292
openjdk@1.17.0
openjdk@1.11.0-2
temurin@17
✔ swift3:~> 
```

And when I run jbang  **I have no glue which java version will be used**. 

As a solution I would like to have output similar to what maven show now on asking the version:

![image](https://github.com/user-attachments/assets/f710a58e-dc0e-42e7-be6b-48cce05631df)

**Comment by quintesse** [comment]
Use `jbang --verbose version`

**Comment by msangel** [comment]
@quintesse thanks!
Was not expected that. Nice output. I believe it must be by default(the the mentioned maven).
