### ISSUE TITLE
JEP 467: Markdown Documentation Comments

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#1834]
Any plan to add [JEP 467](https://openjdk.org/jeps/467) support?

Now JBang uses `//DEPS`, and `/// DEPS` is friendly for JEP 467. 

```
/// JAVA 23
/// JAVA_OPTS --enable-preview -Xmx1024m -Djava.awt.headless=true
/// JAVA_OPTS -Dserver.port=8082
```

or use jbang code fence?  

```
/// ```jbang
/// JAVA 23
/// JAVA_OPTS --enable-preview -Xmx1024m -Djava.awt.headless=true
/// JAVA_OPTS -Dserver.port=8082
/// ```
```

**Comment by quintesse** [comment]
To me this seems "wrong", in the way that using `///`, like `/**` is meant for documentation, JavaDoc documentation to be precise. The normal `//` and `/*` are meant for regular comments. I'd say that JBang tags are definitely not documentation, so the choice for using regular comment symbols is the best one (or the least bad one). Remember that if we'd use those tags the JBang tags would probably end op in the generated documentation! That's definitely not something we'd want.

**Comment by maxandersen** [comment]
Not following what this would bring? Jbangs instructions aren't supposed to be considered as javadoc?

**Comment by maxandersen** [comment]
@linux-china when you write `/// DEPS is friendly for JEP 467` what do you mean ? for me that would mean javadoc makes the statement parts of the javadoc for next following code (class/method/field etc.) - which is not something that at least to me make sense.

for me it is already working well with JEP 467 by not having any interference of meaning.

especially that the top-most line `///usr/bin/env jbang "$0" "$@" ; exit $?` is NOT picked up as a jep comment despite the triple-/'s.

so please let us know why you think you believe jbang directives should be part of markdown rendered javadoc?

**Comment by maxandersen** [comment]
going to close this as afaics jbang already works and are compatible with jep 467 thus I'm not following what the value is in making DEPS identify as markdown comments. 

Please  (re)open if you see an issue/usecase where it should be different.
