### ISSUE TITLE
settle on catalog implicit syntax

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#184]
discussed in https://github.com/jbangdev/jbang/pull/179/#issuecomment-660119576

﻿

**Comment by quintesse** [comment]
What's implemented (and merged) now is: 

```
<aliasname>@<org/user>(/<reponame>(/branch|sha1)?)(~path)
```

Where <reponame> defaults to "jbang-catalog" if not specified
And <branch> defaults to "master" if not specified

Do we need more discussion or can we close this?

**Comment by maxandersen** [comment]
Sounds good. 

Once github changes default master name it will break the internet :)
