### ISSUE TITLE
missing github release for v0.119.0

### ISSUE THREAD

**Issue by chenrui333** [jbangdev/jbang#1840]
👋 looks like 0.119.0 was tagged for a while, but there is no github release for it, raise this issue for some awareness. Thanks!

**Comment by maxandersen** [comment]
Thé 119.0 failed so had to do a 119.1. 

Does it break some automation somewhere ?

**Comment by maxandersen** [comment]
you are completely right. something is not right. looking into it!

**Comment by maxandersen** [comment]
for some reason the release was in draft :/ rolling out now.
