### ISSUE TITLE
Annotated classes in Markdown are not recognized

### ISSUE THREAD

**Issue by andreaTP** [jbangdev/jbang#1854]
**Describe the bug**
A new class declared in a Markdown file is not getting compiled/recognized when it's annotated.

**To Reproduce**
- write a Markdown file `test.md` with this content:

```md
    ```java
    @Generated("foo")
    public class Foo {
        public Foo() {};
    }
    ```
    ```java
    new Foo();
    ```
```
- run `jbang test.md`
- result in this error:
```
Error:
cannot find symbol
  symbol:   class Foo
new Foo();
    ^-^
```
- removing the `Generated` annotation everything works as expected (applies to any annotation)

**Expected behavior**
The script should execute resolving the class `Foo`.

**JBang version**
```
[jbang] [0:217] jbang version 0.116.0
```

**Additional context**
Found [here](https://github.com/dylibso/chicory/pull/629/files#diff-093af1f8155f641965dfc27aa2a13413e2bb8d699327547d34df1a7dc4c9d8b5R163).

**Comment by quintesse** [comment]
The actual error is quite a bit longer:

```
jshell> @Generated("foo")
   ...> public class Foo {
jshell> @Generated("foo")
   ...> public class Foo {l possible completions; total possible completions: 537>
   ...>     public Foo() {
   ...>                 System.out.println("Foo");
   ...>         };
   ...> }
|  created class Foo, however, it cannot be referenced until class Generated is declared

jshell> new Foo();
|  Error:
|  cannot find symbol
|    symbol:   class Foo
|  new Foo();
|      ^-^

```

And the clue to know why it's failing is there in the middle: "created class Foo, however, it cannot be referenced until class Generated is declared"

**Comment by quintesse** [comment]
@andreaTP no, it's because `@Generated` is not included in any JRE or JDK (it's part of the JDK but not included, don't ask me why, but see things like https://stackoverflow.com/a/61206500/2889926)

I've confirmed this by putting the code in a .java file and it gives me this:

```bash
$ java test2.java
test2.java:1: error: cannot find symbol
@Generated("foo")
 ^
  symbol: class Generated
1 error
error: compilation failed
```

**Comment by andreaTP** [comment]
I think we should not focus on the specific `Generated` annotation, as it might be that I have not accurately narrowed down the issue.
In the original example I'm:

- including the annotation on the class path using //DEPS
- using it after
- same error message (the short one from jbang)

**Comment by quintesse** [comment]
Ok, but then your reproducer example isn't complete ;-)

If I turn the annotation into `@Deprecated` I do get an error, but a different one this time:

```
Error:
illegal start of type
@Deprecated;
```

But it does actually run the code!

If I change the annotation to `@Deprecated()` it doesn't complain anymore and everything runs fine.

So the annotation handling definitely is a bit strange in jshell but it _does_ work and at least in my simple test JBang works as well.

Could you perhaps update your reproducer to include the missing bits?

**Comment by quintesse** [comment]
So we can close this issue, right @andreaTP ?

**Comment by andreaTP** [comment]
I'm experimenting a bit, and it seems that the issue is indeed a `JShell` bizarre behavior.
Do you know how I can submit an issue there?

**Comment by quintesse** [comment]
No, idea to be honest, this seems to be the official page for bug reports: https://bugreport.java.com/

**Comment by andreaTP** [comment]
Thanks, we can close this I assume.
