### ISSUE TITLE
alias list should support implicit catalogs, i.e. `jbang alias list @quintesse`

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#187]
now that jbang run supports implicit catalog so should jbang alias list.

atm it just says "unkwnon catalog '@quintesse'

**Comment by quintesse** [comment]
THis already works, but it's `jbang alias list quintesse` (or `jbang catalog list quintesse`), not `@quintesse`. The `@` is to separate the alias from the catalog, it's not part of the catalog name.

**Comment by maxandersen** [comment]
ack - makes sense.

**Comment by quintesse** [comment]
So this can be closed, right?
