### ISSUE TITLE
We should add a //DESC or //DESCRIPTION tag for scripts

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#190]
This way we can extract that and use it for the "description" field in the `jbang-catalog.json` files.

Multiple tags would be joined together as a block of text.

**Comment by maxandersen** [comment]
related/same as #174 is it not ?

**Comment by quintesse** [comment]
Not at all. #174 is about actual documentation. Like man pages or web sites. This is about a 1-3 line description that will be used when listing the script. This is about a description (not usage) while #174 is all about usage / full docs. #174 Assumes the docs to be external while the important part here is that the description is included in the file, that the script is auto-descriptive.

**Comment by maxandersen** [comment]
Ah ok. 

I get the idea; wondering if we can include grabbing picocli doc/description attribute as a fallback to avoid duplication?

**Comment by quintesse** [comment]
We can certainly try.
