### ISSUE TITLE
Make Jbang able to bootstrap itself without Java

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#197]
This is about being able to download and run Jbang without having Java installed, The idea is that if no Java is installed we'd download it from AdoptOpenJDK similar to #133.

This issue is not exactly the same as #135 because that goes a step further with Jbang itself possibly not being installed. But this issue would probably make solving that issue easier.

Possible solutions:

 1. Make the current Linux/Mac/Windows Jbang bootstrap scripts download Java and install according to the same system introduced by #133 
 2. Create a native bootstrap script (Quarkus or Graal native for example)
 3. Make Jbang entirely native (also using Quarkus or Graal native)

(The problem with 1. is that doing on that for Windows will be far from trivial)

**Comment by quintesse** [comment]
Once we have this Jbang will be perfect ;-)

**Comment by quintesse** [comment]
Just did a quick test for 3. and I noticed at least one thing: the final result is about 13MB. It's a non-working version so perhaps it's not the real size it would be if it would work, but it an indication at least.

**Comment by maxandersen** [comment]
3 times but with no jdk needed is fair. 

My issue is that we'll have to start distributing three different binaries where now it's one thing fits all plus it's "hackable" in-place :)

**Comment by quintesse** [comment]
Distributing yes, but hopefully each OS juist gets a copy of their binary, not all 3. (At least in the bootstrap case).

Not sure what you mean by "hackable in place" though 🤔

**Comment by maxandersen** [comment]
Three distrais will greatly increase builttime / pr checks and the install mechanism needed in all the scripts needs customization now rather than "just work" and we would still need a plain java one as I don't believe the same Linux binary will run everywhere ...and OS X will eventually mess it up ;)

Hackable in place - I can tweak the bat/cmd scripts :)

**Comment by quintesse** [comment]
Ok, for now I'm looking into 1. to see how much work it would be. Btw, are `wget` or `curl` always installed on Mac?

**Comment by maxandersen** [comment]
curl

**Comment by quintesse** [comment]
On Linux:

```
$ jbang version
Downloading JDK 11...
Installing JDK 11...
0.33.0.67
```
