### ISSUE TITLE
jbang alias add should allow adding to local jbang-catalog.json

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#201]
usecase is to make it easy to maintain jbang-catalog.json outside of the ~/.jbang.

optimally `jbang alias add` would add to "nearest" jbang-catalog.json especially when we implement #180

**Comment by quintesse** [comment]
Yeah, this is definitely needed.

**Comment by quintesse** [comment]
I wonder if we should do something automagical, or that we should just be explicit when we want to add the alias to anything but the user's aliases in `~/.jbang/jbang-catalog.json`. For example by using an optional `--file <output-file>` flag or something.

**Comment by quintesse** [comment]
Or we try to do it as automatic as possible with flags to override, eg: `jbang alias add --user foo bar` would force the current behaviour. Still for "nearest" it might be difficult to make a coherent decision. Do we create a `.jbang/jbang-catalog.json` if none exists? Or do we add it to some parent folder if we happen to find one there? But then what if the user actually wanted it in the current folder? Etc etc. Seems easier to be explicit, but if we can come up with an easy to understand protocol we can implement that.

**Comment by maxandersen** [comment]
I would to the automagically one.

Logic being:
if `--global` use `~/.jbang/jbang-catalog.json`
if `--file xyz` use `xyz`
otherwise search from current dir onto root of file system for `jbang-catalog.json`

thus `jbang alias add` will default to --global but if you to `touch jbang-catalog.json;jbang alias add....` it should operate on the file found in local dir.

**Comment by maxandersen** [comment]
was done in #299
