### ISSUE TITLE
jbang creates files that don't compile if you specify an invalid class name

### ISSUE THREAD

**Issue by mjg123** [jbangdev/jbang#214]
Maybe you'd classify this as "user error", but.... For example, `jbang init send-sms.java` creates a java file with `class send-sms { ....` but `send-sms` isn't a valid class name in Java. Maybe jbang should refuse to create a file with an invalid classname?

**Comment by maxandersen** [comment]
We do some transformation already I believed. Just need to add this case.

**Comment by maxandersen** [comment]
this was actually fixed just forgot to close this one.

It will now error in this case:

```
jbang init send-sms.java
[jbang] [ERROR] 'send-sms' is not a valid class name in java. Remove the special charcters
[jbang] Run with --verbose for more details
```

@all-contributors please add @mjg123  for bugs
