### ISSUE TITLE
Add "projects" and "scripts" to cache clear

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#218]
Forgot to add the above mentioned cache categories.

Also means that we need to store the scripts in a folder called `scripts`, not `script_cache_xxxxxxx`.

Edit: and there's a third one: `stdins`

**Comment by quintesse** [comment]
Btw, IMO we shouldn't add `projects` to the default list of categories that will be cleared when just running `cache clear` because it seriously messes up projects open in IDEs if you're not careful. Wdyt @maxandersen ?

**Comment by maxandersen** [comment]
+1 on moving script to folder
and +1 on not nuking projects by default.

they get regenerated everytime edit is called anyway
