### ISSUE TITLE
Make Jbang work just with the startup script (zero install)

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#219]
Meaning that if no .jar is found the latest version will be downloaded and unpacked in $JBANG_CACHE_DIR.

**Comment by quintesse** [comment]
Was it your intention to close this? The PR hasn't been merged yet afterall...

**Comment by quintesse** [comment]
Oh wait, you did... but without actually merging the PR? Weird.

**Comment by maxandersen** [comment]
Did it manually as it was marked as draft

**Comment by quintesse** [comment]
Ok, that was just because we were still waiting for those DNS names :-)

**Comment by quintesse** [comment]
Btw, if we can agree on which ones we're going to use I can already update those scripts... the suggestion was to use `ps.jbang.dev` and `sh.jbang..dev`, right? Do you agree with that?

**Comment by maxandersen** [comment]
I needed the files to be there to do the setup. 

Yes those are the urls I'm setting up. 

Note: they will be redirects so need to follow them. Ie. Curl -L

**Comment by quintesse** [comment]
Here it is, let me know what you think: https://github.com/jbangdev/jbang/pull/395
