### ISSUE TITLE
Early access builds of OpenJDK have funky versions

### ISSUE THREAD

**Issue by headius** [jbangdev/jbang#223]
Parsing issue with 14-ea:

```
$ jbang run@jruby -e 1
[jbang] Resolving dependencies...
[jbang]     Resolving org.jruby:jruby-complete:9.2.12.0...Done
[jbang] Dependencies resolved
[jbang] java.lang.NumberFormatException: For input string: "14-ea"
[jbang] Run with --verbose for more details
```

**Comment by maxandersen** [comment]
Isn't 14 enough for you ?

**Comment by headius** [comment]
It is, but I thought you might like to know 😀

**Comment by maxandersen** [comment]
:)

For now we just ask adoptooenjdk about latest relase of major version. 

For now feeling if you want some more precise version then you are Better of using SDK man or similar packaging tool. 

Might change in future if enough usecases require it.

**Comment by maxandersen** [comment]
Oooh wait. You are running with java 14-ea on the path already and that is failing ! 

Gotcha. Yeah that is a bug that should be fixed. We should be résiliant here. 

@quintesse one for you?

**Comment by quintesse** [comment]
Wait, what? You want me to actually _maintain_ the stuff I write? Pfff 🤣

**Comment by quintesse** [comment]
@headius could you perhaps do me a favor and give me the output of `java -version` and `javac -version`? (I have tested with 15ea, just want to makes sure that it behaves the same as 14eu)

**Comment by quintesse** [comment]
FMI:

```
$ javac -version
openjdk version "15-ea" 2020-09-15
OpenJDK Runtime Environment (build 15-ea+33-1546)
OpenJDK 64-Bit Server VM (build 15-ea+33-1546, mixed mode, sharing)
$ javac -version
javac 15-ea
```

**Comment by headius** [comment]
```
$ java -version
openjdk version "14-ea" 2020-03-17
OpenJDK Runtime Environment (build 14-ea+33-1439)
OpenJDK 64-Bit Server VM (build 14-ea+33-1439, mixed mode, sharing)

$ javac -version
javac 14-ea
```
