### ISSUE TITLE
Incorrect info about completion in help

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#239]
$ **jbang --help**
Usage: jbang [-h] [--verbose] [COMMAND]
Compiles and runs .java/.jsh scripts.
  -h, --help      Display help/info
      --verbose   jbang will be verbose on what it does.
Commands:
  run         Compile and run provided .java/.jsh script.
  build       Build .java/.jsh script without running. Use for caching
                dependencies.
  edit        Edit a .java/.jsh script.
  init        Initialize a .java/.jsh script.
  alias       Manage aliases.
  catalog     Manage catalogs.
  trust       Manage trust domains.
  cache       Cache management.
  completion  Output auto-completion script for bash/zsh.
              Usage: source <(**jbang --completion**)
  version     Display version info.

When issuing:

$ **jbang --completion**
Unknown option: '--completion'
Usage: jbang [-h] [--verbose] [COMMAND]
Compiles and runs .java/.jsh scripts.
  -h, --help      Display help/info
      --verbose   jbang will be verbose on what it does.
...
 
The command to call is:

$ **jbang completion**

Tested with version 0.36.1

**Comment by maxandersen** [comment]
thanks - already fixed in master; will go out with the next version.
