### ISSUE TITLE
File changes in live editing mode are not recognized by WatchService on Windows

### ISSUE THREAD

**Issue by OLibutzki** [jbangdev/jbang#246]
If I edit the java file which is referenced by a symlink in live editing mode, the change does not trigger a WatchEvent.

I have to navigate to the physical file location in the Windows Explorer and select to file in order to trigger the event.

**Comment by maxandersen** [comment]
Hmm - hadn't noticed that. Is this all on the same drive ?

**Comment by OLibutzki** [comment]
I can't reproduce the issue. Closing...
