### ISSUE TITLE
Consider handling SIGPIPE by default for piped output to work fully

### ISSUE THREAD

**Issue by klaeufer** [jbangdev/jbang#247]
Here is a simple incremental line counter:

```
import java.util.Scanner;
import sun.misc.Signal;

public class ilc {

    public static void main(final String[] args) {
	int count = 0;
	final var input = new Scanner(System.in);
	while (input.hasNextLine()) {
	    input.nextLine();
	    count += 1;
	    System.out.println(count);
	}
        input.close();
    }
}
```

This won't work like other command-line utilities when the output is piped. For example, this hangs with the upstream Java process hogging the CPU as it is writing to the closed downstream input pipe:

```
yes jbang | jbang ilc.java | head -n 5
1
2
3
4
5
<--- pipeline hangs here
```

To get it to work as expected, one has to handle SIGPIPE explicitly at the beginning of `main`:

```
	if (!"Windows".equals(System.getProperty("os.name"))) {
	    Signal.handle(new Signal("PIPE"), (final Signal sig) -> System.exit(1));
	}
```

Given the stated purpose of jbang and the importance of piping, I'm of the opinion that this kind of handler should be set by default on Unix-like systems so that the script developer doesn't have to worry about it.

**Comment by maxandersen** [comment]
was hoping to add something to the docs and sees that when compiling using Signal you get warnings like:

```ilc.java:3: warning: Signal is internal proprietary API and may be removed in a future release```

...your output don't show that - did you find a way around that ?

**Comment by maxandersen** [comment]
seems in java 8 you can use `@SuppressWarnings("restriction")` but that does not work on Java 9+ ;/

for now I've documented this in readme.adoc; but due to this being internal api i'm not (yet) willing to bet on it working across all java's thus prefer to document it over depending on it.

**Comment by maxandersen** [comment]
Thanks for the info and reporting it!

@all-contributors please add @klaeufer for ideas
