### ISSUE TITLE
Option to retrieve or set built JAR file path

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#265]
Right now the JAR file that gets generated for a `build` or `run` is pretty hard to find. It would be nice to have an easy way to add a Jbang JAR file to the class path of a follow-up run (either Jbang or Java). I was thinking of several options:

 1. Add a `-o` / `--output` option that would write the JAR file to the given path. (But this has several practical problems which can only be solved by making arbitrary design decisions. Not a fan)
 2. Add an option like `--show-jar-path` that would output the path to the JAR during `build`
 3. Add a new command `jar <sourcefile>` that given a file name would only return the path (but what if the JAR doesn't exist yet? Would it work like `build`? If so option 2 seems to make more sense)
 4. Add a new sub-command to `cache`, eg `cache get <sourcefile>` that does the same as option 3 (but in that case definitely without building the JAR if it doesn't exist)

The advantage of options 3 and 4 is that you could perhaps more easily use them in a script, eg: `java -cp $(jbang jar mysource.java) something something`. But perhaps the same thing could be achieved by adding a `--quiet` option to Jbang.

Edit: added option 4.

**Comment by abelsromero** [comment]
Just a thoutgh...
I find the line between a *script-compiler-runner-wrapper* and a package manager is blurring in jbang with time.
Not a bad thing, but makes me think that maybe cache and catalog features should eventually unify with commands that allow exploring installation paths and install/uninstall individual scripts. Sort of how go or npm work, but without the dependency management.

**Comment by quintesse** [comment]
Btw, personally I think for the easiest usage within scripts or even in CLI one-liners is option 2.

**Comment by quintesse** [comment]
@abelsromero that might be a good subject for a discussion: https://github.com/jbangdev/jbang/discussions :-)

**Comment by maxandersen** [comment]
how about a `jbang info` command that would build if needed but not run? 


```$ jbang info myapp.java
jar: /Users/max/.jbang/cache/jar/weasdfewlrwrkjjrw32234/myapp.jar
buildtime: 1985-11-26 01:24 (3 decades a ago)
dependencies: <GAV1, GAV2, GAV3, ...>
...
```

```$ jbang info -q --jar myapp.java
/Users/max/.jbang/cache/jar/weasdfewlrwrkjjrw32234/myapp.jar
```

`-q` for quiet :)

or make `--jar`, `--buildtime`, `--dependencies` mutually exclusive so only can can specified...

would that be useful ?

**Comment by maxandersen** [comment]
> @abelsromero that might be a good subject for a discussion: [jbangdev/jbang/discussions](https://github.com/jbangdev/jbang/discussions) :-)

agreed - would love to hear more @abelsromero!

**Comment by quintesse** [comment]
Hmmm, thing is that having a command like that with a not really unimportant "side effect" like building the JAR feels somewhat wrong to me. That's why I didn't really like option 3. But option 4 is just less useful (because you'd still need to build first, so it would be 2 steps instead of 1).

So personally it seems more "obvious" that what I'm doing is building the JAR and the "side-effect" is that I want to know the path to the resulting JAR. That way I can also pass any other arguments that `build` allows (eg. the new `--cp` and `--deps`) that would be strange to add to `info`. (I think this last argument is the killer)

**Comment by maxandersen** [comment]
What you are basically saying that the output of jar could just as well be the resuting jar name ?

Much like edit is the output of the project prepared for it ?

**Comment by quintesse** [comment]
Not sure I understand you completely, What I'm suggesting is this:

````
$ jbang build --show-jar-path fubar.java
/home/jdoe/.jbang/cache/jars/ghjgjh4g35hj4g6hj4jhg_fubar.jar
```

Although now that I think about it some more... most of the time you'd need the dependencies as well. So perhaps the output would have to be:

````
$ jbang build --show-jar-path-and-deps fubar.java
/home/jdoe/.jbang/cache/jars/ghjgjh4g35hj4g6hj4jhg_fubar.jar:/home/jdoe/.m2/etc/etc/etc:/home/jdoe/.m2/etc/etc/etc:/home/jdoe/.m2/etc/etc/etc
```

(Btw the option names are not the ones I'm actually suggesting ;-) )

**Comment by maxandersen** [comment]
So you want the full class path ?

Ie. 'jbang build --show-class-path foo.java'

Could have '--show-jar' too

Just have to be careful on what usecase it's targeting since if just for info ..the fine all good. 

But if for being able to reuse classpath then this has a few challenges: won't work on windows and what happens when list is long and worse; what happens with conflicting/duplicated classpath entries -who wins?

Maybe as "cheap" initial version of the --deps proposal but to properly work it needs more thought / tighter integration.

**Comment by quintesse** [comment]
Well no, I was specifically targeting it to be able to do something like `java -cp $(jbang build --show-class-path fubar.java)`, but I'm already seeing more problems. To be able to do this you'd probably have to multiple calls: one to get the class path and at least another one to get either the name of the JAR or the name of the Main class.

So this definitely needs some more thought, agreed.

**Comment by quintesse** [comment]
This was already implemented a long time ago with `jbang info`. Closing.
