### ISSUE TITLE
brew install now requires /usr/local/opt/jbang/bin instead of /usr/local

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#274]
makes brew install not working out of box.
﻿

**Comment by arpit-mehra** [comment]
hey, I am trying to use brew install and it does not seem to be working. Is this the cause of the issue ? I'd really appreciate any workarounds (or even any help you need) fixing it.

**Comment by maxandersen** [comment]
what error are you getting ?

**Comment by maxandersen** [comment]
this issue is just about that for reasons I haven't understood yet I get: 

"jbang is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula."

and you have to run `brew link --force jbang`

**Comment by maxandersen** [comment]
related https://github.com/Homebrew/homebrew-core/issues/63512

**Comment by maxandersen** [comment]
fixed in master
