### ISSUE TITLE
sdkman release notes contain dead links

### ISSUE THREAD

**Issue by bmuskalla** [jbangdev/jbang#277]
Using SDKMAN shows news about the latest releases.
```
==== BROADCAST =================================================================
* 2020-09-02: jbang 0.43.0 @jbangdev https://git.io/JUqfJ
* 2020-09-02: jbang 0.42.1 @jbangdev https://git.io/JUqfJ
* 2020-08-25: Gradle 6.6.1 released on SDKMAN! #gradle
================================================================================
```

The links for jbang are broken as they point to `https://github.com/jbangdev/jbang/releases/tag/$%7Bjbang_version%7D`. Looks like some placeholder is not properly replaced.

**Comment by maxandersen** [comment]
hmm - weird...checking!

**Comment by maxandersen** [comment]
should be fixed in #ea8535

**Comment by maxandersen** [comment]
@all-contributors please add @bmuskalla for infra
