### ISSUE TITLE
[question] Unclear use `--live`defaults

### ISSUE THREAD

**Issue by abelsromero** [jbangdev/jbang#278]
The `Live Editing` section in the docs states:

```
The editor used will be what is specified as argument to --live 
or default to $JBANG_EDITOR, $VISUAL or $EDITOR in that order.
```

But when I run `jbang edit --live minimal.jsh` I get the output below, which makes me think that life requires always to set something.

```
Missing required parameter: '<scriptOrFile>'
Usage: jbang edit [-ho] [--insecure] [--verbose] [--live=<liveeditor>]
                  <scriptOrFile> [<userParams>...]
Setup a temporary project to edit script in an IDE.
      <scriptOrFile>        A file with java code or if named .jsh will be run
                              with jshell
      [<userParams>...]     Parameters to pass on to the script
  -h, --help                Display help/info
      --insecure            Enable insecure trust of all SSL certificates.
      --live=<liveeditor>   Setup temporary project, launch editor and
                              regenerate project on dependency changes.
  -o, --offline             Work offline. Fail-fast if dependencies are missing.
      --verbose             jbang will be verbose on what it does.
```

**Comment by maxandersen** [comment]
What is the value of those fallback env variables when you run it ?

**Comment by abelsromero** [comment]
I only have EDITOR set to `/usr/bin/vim`, but vim is not supported and using it explicitely causes the shell to block. But also tried setting to code and code full path.
But I think the problem is in the command parsing.
Seems to me life valur is mandatory and maybe is interpreting the script file as the value for -"-live".

**Comment by maxandersen** [comment]
you are right - pretty sure this worked at some point but can't see how ;) need to filter out actual files/http ...

**Comment by maxandersen** [comment]
i think with recent edit/live changes this should work as follows:

`jbang edit x.java` -> generates project
`jbang edit --live x.java` -> generates project, monitors for file changes and will regenerate
`jbang edit --open= x.java` -> generates project, opens it up in default editor
`jbangn edit --live --open=code x.java` -> generates projects, opens it up using `code`, monitors for file changes and will regenerate`

does this work as you expect @abelsromero ?

**Comment by abelsromero** [comment]
All work as expected but there's a thing, files set in `//SOURCES` do not seem to be monitored for changes.

**Comment by maxandersen** [comment]
Good point - missing feature :) i'll open separate issue for that one.
