### ISSUE TITLE
javac fails badly when just a jre installed and it does not honor //JAVA or --java

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#283]
i installed fedora workstation 32. it comes with jre 1.8 (sigh) by default which confuses jbang ;) 

it errors hard as no javac present; that would be kinda okey if it wasn't so that when using `jbang --java 11 properties@jbangdev` then it still fails with javac missing albeit java 11 just got downloaded.

something mixed up with used paths or so.

**Comment by benoitf** [comment]
Could you use Eclipse Java Compiler (instead of javac) ? so it could run on pure JRE

**Comment by maxandersen** [comment]
Not really an advantage to use eclipse Javac. We could do it on theory but it would increase size and we really just need to detect it's a jre and get jdk when needed.

**Comment by quintesse** [comment]
@maxandersen we did test before if we had a `javac` and it makes startup of Jbang about .5s slower :-(

**Comment by quintesse** [comment]
Still... it's weird because we _do_ check that the `javac` command at least _exists_. So I wonder why it fails...

**Comment by maxandersen** [comment]
Could we wait until we actually need javac ? A better error message would at least help

**Comment by quintesse** [comment]
Is there some easy way to reproduce this? Don't want to install Fedora workstation 32 just to test this :-D

Perhaps some kind of Docker image?

**Comment by benoitf** [comment]
```
$ docker run --rm -it fedora:32

[root@257d5085e57c /]# curl -sSL https://github.com/jbangdev/jbang/releases/download/v0.45.0/jbang-0.45.0.tar -o jbang.tar
[root@257d5085e57c /]# tar xf jbang.tar
[root@257d5085e57c /]# ./jbang-0.45.0/bin/jbang --java 11 properties@jbangdev
Downloading JDK 11. Be patient, this can take several minutes...
Installing JDK 11...
[jbang] Resolving dependencies...
[jbang]     Resolving info.picocli:picocli:4.2.0...Done
[jbang]     Resolving de.vandermeer:asciitable:0.3.2...Done
[jbang]     Resolving org.jline:jline:3.16.0...Done
[jbang] Dependencies resolved
[jbang] Building jar...
[jbang] java.io.IOException: Cannot run program "javac": error=2, No such file or directory
[jbang] Run with --verbose for more details
```

**Comment by quintesse** [comment]
Thanks @benoitf !

It's weird, if I try to reproduce this locally by removing Java completely from my PATH it works fine.

**Comment by quintesse** [comment]
Also the JDK downloaded by Jbang works fine too. So it isn't a problem with the auto-installation of the JDK either.

**Comment by quintesse** [comment]
So running with `--verbose` it seems that Jbang somehow decided it doesn't know where Java is installed and goes with the fallback of using plain `javac` and assuming it's available on the user's PATH.

**Comment by quintesse** [comment]
`JAVA_HOME` gets set correctly too, so that's not it either.

Only if I add the downloaded JDK to the user's path do things start to work.

Aha! @maxandersen were you testing with `root` too perhaps?

If I switch to `root` on my local system:

```
[root@rhlaptop ~]# /home/tschotan/.sdkman/candidates/jbang/current/bin/jbang properties@jbangdev
[jbang] Resolving dependencies...
[jbang]     Resolving info.picocli:picocli:4.2.0...Done
[jbang]     Resolving de.vandermeer:asciitable:0.3.2...Done
[jbang]     Resolving org.jline:jline:3.16.0...Done
[jbang] Dependencies resolved
[jbang] Building jar...
[jbang] java.io.IOException: Cannot run program "javac": error=2, No such file or directory
[jbang] Run with --verbose for more details
```
