### ISSUE TITLE
Fail to install/update with brew on macOS 

### ISSUE THREAD

**Issue by skabashnyuk** [jbangdev/jbang#305]
```
brew install maxandersen/tap/jbang
==> Installing jbang from maxandersen/tap
==> Downloading https://github.com/jbangdev/jbang/releases/download/v0.45.0/jbang-0.45.0.zip
Already downloaded: /Users/skabashn/Library/Caches/Homebrew/downloads/5ab2016b7cf9273b686d0c89be3300ac0e65bff7b290dd0a78c5598edfba0cb4--jbang-0.45.0.zip
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
/usr/local/Cellar/jbang/0.45.0/libexec/bin/jbang:
  expected replacement of /^jarPath=.*/ with "jarPath=/usr/local/Cellar/jbang/0.45.0/libexec/bin/jbang.jar"

```
macOS 10.15.5
jbang 0.45.0

**Comment by maxandersen** [comment]
hmm - same issue reported at https://github.com/jbangdev/homebrew-tap/issues/2

very weird - this haven't changed in ages. testing.

**Comment by maxandersen** [comment]
okey, reproduced! 

btw. where do you see `brew install maxandersen/tap/jbang` ? the right one since some months is `brew install jbangdev/tap/jbang`

**Comment by maxandersen** [comment]
hmm - this looks like a brew dependent change....the jbang formula haven't changed strucuture for 6+ months. just updated the shas and jar location.

**Comment by maxandersen** [comment]
ok, bug found - caused by a recent change in jbang script that changed a variable the formula was dependent on. please try again - should now work.
