### ISSUE TITLE
Init command output suggests wrong edit command

### ISSUE THREAD

**Issue by Bananeweizen** [jbangdev/jbang#310]
Using the init command on Windows gives this output in 045.0:
```
jbang init hello.java
[jbang] File initialized. You can now run it with 'jbang hello.java' or edit it using 'code `jbang edit hello.java`'
```
That last suggestion for editing is not valid syntax on Windows (there is no support for nested evaluation of \`foobar\`). Piping output from jbang to code would look more like
```
jbang edit hello.java | code
```
But also that doesn't work. Not sure if this is caused simply by the newline at the end of the output generated by the edit command.

**Comment by maxandersen** [comment]
i think doing #271 might be best option then `jbang edit --open=code hello.java` could be used and would work on all platforms.

**Comment by maxandersen** [comment]
#271 is fixed but still relevant to update the description/info message to use `jbang edit --open=code hello.java`
