### ISSUE TITLE
Allow aliases in catalogs to set the Java version?

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#311]
Suggested here: https://github.com/moditect/layrry/issues/28

We could add an option that would allow for something like:

```
{
  "aliases": {
    "foo": {
      "script-ref": "foo.java",
      "java-version": "14+"
    },
```

**Comment by maxandersen** [comment]
should we have a more open-ended one of setting other flags (basically to change the defaults but users can still override them ?)

i.e. -D, --deps etc. could be relevant too ?

**Comment by maxandersen** [comment]
basically....allow `jbang alias add blah --java 14 -Dxyz.blah="hey yo" foo.java`

`jbang blah` -> jbang --java 14 -Dxyz.blah="hey yo" foo.java`
`jbang --java 15 -Dxyz.blah="test" blah` -> jbang --java 15 -Dxyz.blah="test" foo.java`

wdyt? questio is how multivalue args would work (like `--deps`); but probably just as addition.

**Comment by quintesse** [comment]
Well the problem would be in figuring out which arguments would be for Jbang and which would be for the script.

**Comment by maxandersen** [comment]
hmm - not if you declare all the jbang arguments explicitly on `alias add` ...

**Comment by quintesse** [comment]
We'd have to take into account that those arguments might conflict with arguments for the script, so we'd have to design it like `run`: the jbang arguments would have to come before the fixed parameters, and all arguments after that will just be taken as arguments for the script.
