### ISSUE TITLE
@Path("/{number}") is translated in the qmetrics template

### ISSUE THREAD

**Issue by kalaspuffar** [jbangdev/jbang#317]
I was trying the different templates that have been defined in the resource directory and the qmetrics template did not work directly because {number} was changed to NOT_FOUND which is understandable as that is a template variable. 

Perhaps you could implement the template to require multiple {{name}} for instance as you do in mustache.

Keep up the great work.

**Comment by maxandersen** [comment]
ah - I missed that! thanks - let me get that fixed!

**Comment by maxandersen** [comment]
will be in next release!

@all-contributors please add @xyz for bug

**Comment by maxandersen** [comment]
@all-contributors please add @kalaspuffar for bug
