### ISSUE TITLE
Shell interpreter Windows 7 MSYS2 or MINGW64

### ISSUE THREAD

**Issue by kalaspuffar** [jbangdev/jbang#341]
Hi. 

I've tried to get the shell interpreter working but in both MSYS2 and MINGW64, I get the following message.

./TestCli.java: line 1: //usr/bin/env: No such file or directory

If I try to run the command without the extra slash I work in MINGW64 and shows the jbang instruction set but in MSYS2 I get the error:

Unsupported Operating System: MSYS_NT-6.1-7601

Best regards
Daniel

**Comment by maxandersen** [comment]
hmm very weird - I could have sworn this worked before - but i'm getting this now too.

its weird as it `/usr/bin/env` exits but for some reason the bash shell doens't treat `//usr/bin/env` as same as `/usr/bin/env` as it should.

**Comment by maxandersen** [comment]
@quintesse do i remember wrong that this worked before ?

**Comment by quintesse** [comment]
I had never actually tried it myself on Windows before, sorry. I can only confirm that I get the same error.

Same if I just type `ls //usr/bin` while that works fine on Linux.

**Comment by maxandersen** [comment]
thats a shame ;/

**Comment by quintesse** [comment]
I'm wondering if this is a compatibility issue we could open on those projects? I know it sounds somewhat far fetched, but it's an obvious example of something that doesn't work as expected.

**Comment by quintesse** [comment]
Argh, just looked at the docs for path handling and on Windows they of course have to contend with the fact that double slashes signify network access :-(
https://www.cygwin.com/cygwin-ug-net/using.html#cygdrive

**Comment by quintesse** [comment]
@maxandersen I might have found the way to fix this... but you might not like it ;-)

It's using 3(!) slashes:

```
///usr/bin/env jbang "$0" "$@" ; exit $?
```

It's nice to have a solution, but a bummer to have to update all the info out there (not counting the ones we probably can't update).

**Comment by maxandersen** [comment]
wth....well its already a hack so adding another / to please windows bash users isn't that bad. At least it is forward compatible ;)

**Comment by quintesse** [comment]
Yeah, imagine they were backslashes, then we'd only be backward compatible! 😅
