### ISSUE TITLE
gradle plugin for running jbang as part of build

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#342]
as discussed in #231 would be nice with easy use of jbang in gradle (and mvn builds)

we now have github.com/jbangdev/jbang-maven-plugin, would be great to have a github.com/jbangdev/jbang-gradle-plugin too.

/cc @aalmiray challenge accepted ? :)

**Comment by aalmiray** [comment]
Come at me bro.

**Comment by maxandersen** [comment]
this was done! yay!
