### ISSUE TITLE
Run jbang from a pom.xml file

### ISSUE THREAD

**Issue by davsclaus** [jbangdev/jbang#352]
Just a whacky thought. 

If you build a java project that is a little bit more than a basic script, then you may use a maven project layout.
And then to make it easy to execute via jbang, then you can create a main class and have DEPS in the top, but  then you may repeat yourself as you have dependencies in maven pom.xml also.

And if you also in the pom.xml setup which main class to run via maven-jar-plugin and its `mainClass` option, then you essentially have information how to run this `pom.xml` file.

Then you could run it via

    jbang pom.xml

I hacked a little project at https://github.com/davsclaus/camel-visual
It has the DEPS in my main class source code at: https://github.com/davsclaus/camel-visual/blob/master/src/main/java/org/apache/camel/visual/VisualRouteMain.java#L2

And the readme in the root folder have instructions how to run it currently via jbang.

**Comment by maxandersen** [comment]
Not sure I grok what you see as the benefit here ? So jbang would parse pom.xml ignore its dep info to find the main class then use what is on the main class ?

**Comment by davsclaus** [comment]
Yeah the catalog trick you showed me in the camel-visual is really great. Much better than this ticket so closing it.
