### ISSUE TITLE
Add refresh cache flag for jbang run

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#360]
I have some useful jbang scripts on  my github repository, such as  linux-china/jbang-catalog.  
Now I run the jbang script like following:

```
$ jbang HelloWorld@linux-china
```

A question now, I changed some code in HelloWorld.java and push it to github,  and I should clear cache and run jbang command again. 

```
$ jbang cache clear --url
$ jbang HelloWorld@linux-china
```

Any plan to add --reload to refresh cache for url?   "jbang cache clear --url"  will clean cache for all urls. 

```
$ jbang --reload HelloWorld@linux-china
```

**Comment by maxandersen** [comment]
Yeah we should. I'm wondering if we shouldn't at lost to a HEAD request to check if updated; though in many cases that probably will be as slow as fetching the real content. Now with //source support being able to always get latest this is more and more important.


@quintesse remind me why we don't flip it and have a --no-refresh option and make it so runs of http always get the latest ?

**Comment by quintesse** [comment]
Well it's a fight we always have :-)
Personally I don't think a tool, especially a developer-oriented tool, should do anything automatically that might change the behaviour of what I'm trying to run if I don't explicitly tell it to.

If you want the latest version it's easy enough to add that `--refresh` option while on the other hand it's too easy to forget the opposite option (`--no-refresh`) and suddenly find yourself in a situation that basically impossible to fix (there's no way to get an old version back).

If you really want you can do that HEAD check and show a message like: "The script you're running is out-of-date, run with `--refresh` to run the latest version".

**Comment by maxandersen** [comment]
this was actually added in #495 

@all-contributors please add @linux-china  for idea
