### ISSUE TITLE
Permission denied after installing via snap

### ISSUE THREAD

**Issue by abstratt** [jbangdev/jbang#361]
```
$ sudo snap install jbang --edge
```

Opened another terminal:

```
$ jbang --help
/snap/jbang/1/bin/jbang: line 130: /home/rafael/dev/jdk/bin/java: Permission denied
:~ [20:30:49] >>>
$ /home/rafael/dev/jdk/bin/java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
:~ [20:30:52] >>>
$ ls -l /home/rafael/dev/jdk
lrwxrwxrwx 1 rafael rafael 12 May 23 23:44 /home/rafael/dev/jdk -> jdk1.8.0_251
:~ [20:30:54] >>>
$ 

```

**Comment by abstratt** [comment]
Installing via sdkman worked fine.

**Comment by maxandersen** [comment]
Okey - so the snap doesn't get access to use the Java you have preinstalled.... that makes it quite useless :)

**Comment by maxandersen** [comment]
Can you try run jbang without Java accessible in path and see if it will at least fetch Java in that case ?

**Comment by maxandersen** [comment]
Btw. Looks like I would need to request classic permissions for jbang as it would need to launch processes (ie. Java and javac from users system) 

I wonder why it ran for me though. Will check tomorrow.

**Comment by abstratt** [comment]
> Can you try run jbang without Java accessible in path and see if it will at least fetch Java in that case ?

For some reason, it cannot download the JDK. I opened #364 so there a reason should be reported in case an error happens downloading the JDK with curl or wget.

In order to try to debug the issue, I run instead:

```bash -x /snap/jbang/current/bin/jbang```

but then instead of failing, it works fine. :man_shrugging: 

```
$ /snap/jbang/current/bin/jbang version
0.47.1
$ jbang version
Downloading JDK 11. Be patient, this can take several minutes...
Error downloading JDK
$ whereis jbang
jbang: /snap/bin/jbang
```

**Comment by abstratt** [comment]
Also, if I enable my local JDK again, this works:

```
/snap/jbang/current/bin/jbang
```

whereas just  ```jbang``` results in:

```
$ jbang 
Downloading JDK 11. Be patient, this can take several minutes...
Error downloading JDK
```

**Comment by abstratt** [comment]
Hmm, I think this my be the reason:

```$ sudo snap install --edge jbang
jbang (edge) 0.47.1 from Max Rydahl Andersen (maxandersen) installed
$ whereis jbang
jbang: /snap/bin/jbang
$ ls -la /snap/bin/jbang 
lrwxrwxrwx 1 root root 13 Sep 27 21:01 /snap/bin/jbang -> /usr/bin/snap
```

**Comment by abstratt** [comment]
Hmm, never mind, other links in the same dir all look like that (point to /usr/bin/snap), and they do work fine somehow (I guess the snap program figures out what application to call based on the path used to execute itself).

**Comment by maxandersen** [comment]
I think the errors you are seeing is caused by the sandbox snaps run in by default. 

I've now found that similar tools runs with 'classic' so I've requested same access. Needs specific approval to be deployed so awaiting answer to that at https://forum.snapcraft.io/t/classic-request-for-jbang/20216

Once that comes I should be able to post one that runs without the sandbox requirements.

**Comment by maxandersen** [comment]
finally got approval. considering this fixed. let me know if it works for you @abstratt
