### ISSUE TITLE
Error downloading JDK with no reason given

### ISSUE THREAD

**Issue by abstratt** [jbangdev/jbang#364]
This is a bug report about serviceability rather than about the failure itself.

```sudo snap install --edge jbang```

```
jbang --version
Downloading JDK 11. Be patient, this can take several minutes...
Error downloading JDK
```
It seems there is an error invoking curl or wget, but no information is given to the user. 

Maybe jbang should run curl and wget in verbose mode?

**Comment by maxandersen** [comment]
please try latest https://snapcraft.io/jbang - finally got approved to have jbang in classic mode so it can use external tools.
