### ISSUE TITLE
Add default imports similar to Groovy

### ISSUE THREAD

**Issue by helpermethod** [jbangdev/jbang#370]
Hi!

I use `Groovy` for scripting and one thing which really helps to iterate quickly is that `Groovy` by default adds the following imports

```
import java.lang.*
import java.util.*
import java.io.*
import java.net.*
import groovy.lang.*
import groovy.util.*
import java.math.BigInteger
import java.math.BigDecimal
```

It would be great if `jbang` could add

```
import java.lang.*
import java.util.*
import java.io.*
```

by default.

What do you think?

**Comment by maxandersen** [comment]
For .Java , .jsh or both ?

For .jsh That could work. If they aren't actually already there. 

For .Java I'm fine adding them to the initial template(s) but not fan of implicitly add them as a) I would have to modify the files in temporary location b) IDES wouldn't see them.

**Comment by helpermethod** [comment]
Implicitly for `.jsh` would be fine I think. It adds a little bit of magic, though.

**Comment by maxandersen** [comment]
We already add magic for jsh to support arguments and properties so it's not that far fetched :)

**Comment by harrison-nc** [comment]
Hi, 
to supplement this can you also add print* (print, println, printf, e.t.c) methods to .jsh?
I know jshell has support for this through PRINTING script
But I noticed that start time increases noticeably when executing
a script file using either jbang or jshell like so: `jbang file.jsh` or `jshell file.jsh`
and running the command `/open PRINTING` inside the script file.

I wondering whether adding this useful methods in jbang would have less impact on
start time.

Thanks.

**Comment by maxandersen** [comment]
@harrison-nc sorry - i missed your comment. I can't reproduce the start time increasing noticably when adding `/open PRINTING` - can you provide some steps to reproduce and some numbers what you see as significant ?

**Comment by maxandersen** [comment]
@helpermethod i've added default imports for all the ones groovy did (except the groovy specific one) 

@harrison-nc we could also add printing but I would like to hear what issue it is you saw before doing so. Can you open new issue describing what didn't work for you ? 

@all-contributors please add @helpermethod  for idea
