### ISSUE TITLE
support --javaagent=<file|GAV|jbangscript>[=options]

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#373]
to allow usecases like:

`java -javaagent:com.github.phillip-kruger.julset:julset:master-38ae41f7b5-1 -Djul.com.github.phillipkruger.myapp=FINEST -jar com.github.phillip-kruger.julset:julset-test:master-38ae41f7b5-1` 

or even more "crazy":

`java -javaagent:julset.java -Djul.com.github.phillipkruger.myapp=FINEST myapp.java`

the latter would require #130 or similar to work

**Comment by phillip-kruger** [comment]
Second option would be cool !!

**Comment by maxandersen** [comment]
this is all there now since #377 was fixed. thus closing
