### ISSUE TITLE
alias add -f directory should create jbang-catalog.json in that directory

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#374]
would be nice to just go:

`jbang alias -f . xyz path/to/xyz.java`

instead of having to spell out jbang-catalog.json.

right now the above gives: `[jbang] [WARN] Unable to add alias: /Users/max/code/camel-visual/.: Is a directory`

**Comment by chrsblck** [comment]
Hi @maxandersen - can I work on this?

**Comment by maxandersen** [comment]
go ahead @chrsblck 👍

**Comment by maxandersen** [comment]
I merged this, but had to revert it before release as I found a few issues:

[ ] `jbang alias list` results in a NPE as catalogfile in that case is null.
[ ] if there is a `.jbang/jbang-catalog.json` that is not picked up resulting in both a `.jbang/jbang-catalog.json` AND `jbang-catalog.json` being created. It should use the one already there.
[ ] suprised how the NPE above aren't catched by any test :)

**Comment by chrsblck** [comment]
I'll fix this, sorry. I think it's because there was the addition to the ticket, rightly so, that this was for all `alias` commands and not just `add`. I should have added test for all the other sub-commands. I'll get to this in the next day or so.

**Comment by maxandersen** [comment]
Dont be sorry. We should have had the tests to catch it :)

Thanks for looking into making it better!

**Comment by quintesse** [comment]
> jbang alias list results in a NPE as catalogfile in that case is null.

Ah yes, `null` is a perfectly valid value for `catalogfile `.

> if there is a .jbang/jbang-catalog.json that is not picked up resulting in both a .jbang/jbang-catalog.json AND jbang-catalog.json being created. It should use the one already there.

@maxandersen I'm not sure what you're trying to say here. What is the behaviour you're expecting here? That if the user passes `-f some/folder` that the code should check if either `some/folder/jbang-catalog.json` or `some/folder/.jbang/jbang-catalog.json` exists and return the existing one?

In that case what should be done if none of them exist? Should `some/folder/jbang-catalog.json` or `some/folder/.jbang/jbang-catalog.json` be returned?

**Comment by maxandersen** [comment]
Which one do our code look for first in case of local and remote catalog look up? That one :)

**Comment by quintesse** [comment]
Ok 👍 (it would be `some/folder/jbang-catalog.json`)

**Comment by chrsblck** [comment]
I have a couple questions here.

1. Should `alias list -f some/folder` create a new catalog file if one doesn't exist? Based on quote below.
> But in that case what should be done if none of them exist? Should some/folder/jbang-catalog.json or some/folder/.jbang/jbang-catalog.json be used?

2. `alias add` is working as expected?

3. Are there other sub-commands that need to be checked?

**Comment by quintesse** [comment]
@chrsblck No, no files should be created. Only `alias add` should ever do that. Honestly I'd just put a check in that `getCatalog()` method that throws a usage error (`IllegalArgumentException`) when the file doesn't exist.

**Comment by chrsblck** [comment]
Awesome, thanks @quintesse. I'll get to this today

**Comment by maxandersen** [comment]
Wouldn't list -f some/dir not just go look up "nearest" catalog from that dir?

**Comment by chrsblck** [comment]
You mean go looking for catalog files? That sounds kind of confusing for the end user. 

I could see a similar, but slightly different use case for an `alias list --all` or something like that.

**Comment by quintesse** [comment]
I tend to agree with @chrsblck here, this sounds a bit like that "magical" behaviour you didn't like before :-)
The `-f` points to an explicit file. Now we allow the user to be a bit more lazy by allowing a folder.

But with nearest it almost becomes a search option. It would be the same as simply running `alias list` from that folder. (Which is actually an option I'd like to add at some point, a generic top level `--cwd` option that you can use to set Jbang's current working directory. Very useful in scripts and tests but obviously that's an entirely different (GH-)issue).

**Comment by maxandersen** [comment]
Makes sense. Good call. Let's keep it simple and error in list case

**Comment by chrsblck** [comment]
@quintesse Are you sure it's best to throw the illegal arg exception from `getCatalog`? 

I ask because `AliasAdd` uses this, which is obviously fine. Seems messy if `getCatalog` needs some conditional logic when to throw based on the caller. 

If it's not handled it `getCatalog`, it's just `AliasList` that needs to check the return value. `AliasRemove` already handles this (using the nearest logic mentioned early 😄 )

```java
if (getCatalog() != null) {
	AliasUtil.removeAlias(getCatalog(), name);
} else {
	AliasUtil.removeNearestAlias(null, name);
}
```

**Comment by quintesse** [comment]
@chrsblck no fallbacks , otherwise the behaviour would be really surprising.

And about the exception: yes, I'm sure :-) But no conditional logic, it should throw the exception for _all_ callers. It just means that if the user types: `alias xxx -f file/that/does/not/exist.json` it will always show en error, regardless of the command.

**Comment by chrsblck** [comment]
Hmm, okay. It's worth noting that `alias add -f new-catalog-file.json foo Foo.java` will create the file: `new-catalog-file.json`.

This means that `alias add -f . foo Foo.java` will create a new catalog file `./jbang-catalog.json`. It seems nice to keep this functionality, which is why I mentioned the callers of `getCatalog`.

 So just to be clear, you want to change the current behavior for `alias add -f ...` to not create the specified file anymore?

**Comment by quintesse** [comment]
Sorry @chrsblck for suggesting solutions that won't work :-).

Throwing the exception would obviously break things fort the case of `alias add` as you already pointed out.
So let it do in such a way that `getCatalog()` just returns the Path, either the one that actually exists or the "default" one if it doesn't. And then check if the final result exists in the commands `list`and `remove and throw that error if it doesn't.

Does that make sense?

Another option is to pass a `boolean strict` option to `getCatalog()` that would throw the error if set to `true`. (Which is what you suggested before that it would work differently depending on the caller, so `add` would pass `true`, the others `false`).

Just use the solution you like best, they're both fine by me.
