### ISSUE TITLE
add version.txt to see what latest refer to

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#388]

**Comment by aalmiray** [comment]
A versions.txt file at a fixed URL. 
A version.txt file inside jbang.zip

**Comment by maxandersen** [comment]
you want both ?

**Comment by aalmiray** [comment]
Yes. You need both to corroborate local with remote.

**Comment by maxandersen** [comment]
hmm....i guess so. that will have to be in next-next release then :)

**Comment by aalmiray** [comment]
Yes, I meant `version.txt` inside zip and a `version.txt` with just latest number at a fixed URL

**Comment by maxandersen** [comment]
this is now finally in the released artifacts - first one had a 0 byte file which github releaser did not fail on...just ignored. now fixed.
