### ISSUE TITLE
allow for additional source files

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#39]
in some cases libraries just need full public classes and with default jbang you can only have one.

would be interesting to allow for something like:

```
//FRIENDS Person.java Order.java
```

that would add these to the java compile source files list. This would also be possible to work with url based by simply fetching them relative to url location.

could even allow for 
```
//FRIENDS *.java
```

but that would NOT work in the url case so i'm hesitant to include eit.

**Comment by maxandersen** [comment]
The separation is there because of what you suggested in the chat - to allow adding .java without having them compiled :)

**Comment by quintesse** [comment]
AHa, didn't remember that :-)

**Comment by quintesse** [comment]
Btw, we could perhaps do the following:

 - `//FILES <file>` for resource files. They also need to be able to be renamed/moved, eg:
 - `//FILES <asfile>=<file>` so we can do `//ADD META-INF/services/some.spi.definition=spi-file`
 - `//SOURCES <source-file>` adds the selected file to the compilation phase
 - `//DEPS <source-file>` which means the targeted source file get built (if needed) and its JAR file gets added to the class path

**Comment by quintesse** [comment]
Although `//DEPS <source-file>` might need a different name. I chose it because it's basically another way of adding a JAR, but perhaps it's difficult to distinguish between direct references to JAR files and references to source files that fist have to be compiled. Of course perhaps looking at the file name would be enough. Wdyt?

**Comment by maxandersen** [comment]
`//FILES <file>` is trivial in latest master and immediately useful.
`//FILES <file>=<mountpoint>` I understand the value but it makes `jbang edit` much more complicated...thus it might get added later once we worked with basic files first and see how far we can push it; we might not need it.
`//SOURCES source-file` +100; the current code is thought *not* ready for this...doable but requires unwinding things.
`//DEPS source-file` ...this is outside the scope of this issue, discussed in #266

**Comment by maxandersen** [comment]
master now has support for:

```
//FILES <file> for resource files. They also need to be able to be renamed/moved, eg:
//FILES <asfile>=<file> so we can do //ADD META-INF/services/some.spi.definition=spi-file
```

**Comment by quintesse** [comment]
Ok, although my assumption was to have the "destination name" be the first one? A bit like if it was an alias (`alias list=ls -als`). Doesn't that seem slightly more intuitive to you?

**Comment by maxandersen** [comment]
Copy from to
Mv from to

Was my thinking...

**Comment by maxandersen** [comment]
I' might be convinced it works better your way if we ever add globbing patterns. 

'//FILES META-INF/resources=*.html'

'//FILES *.html=META-INF/resources'

...and when you start having multiple files it's kinda to just sort by destination which I would say is the important one. 

...want me to do a 0.41.1 ? :)

**Comment by maxandersen** [comment]
you are right; just tried it - it feels better this way. doing a 0.42.0 just to be nice as it does change behavior.."slightly"

**Comment by quintesse** [comment]
I understand but copy and move are verbs. Files is a definition and uses a `=`, so that's why swapped it seemed more intuitive. Also the "important" value for the code being compiled and run is the first one, which might make it _slightly_ easier to read.

**Comment by quintesse** [comment]
Ok, cool, going to try it out once it's up :-)

**Comment by maxandersen** [comment]
done. 0.42 released and rolling out the various places.

**Comment by quintesse** [comment]
Btw, how do you see `//SOURCES` work? Because the simplest would be to only allow for regular valid Java files, but I'm guessing you'd want to allow files that have their own `//DEPS` and such? And maybe allow .jsh files too? But perhaps we could just start with the basic functionality and see how that works?

**Comment by maxandersen** [comment]
`.jsh` files I can't currently imagine how that would work on `//SOURCES` - they could in theory `//SOURCES` but not sure...

And yes for `//SOURCES` with `//DEPS` I see them simply be added to the set of dependencies to resolve together with the main app.

**Comment by maxandersen** [comment]
for //SOURCES we probably need to change the resolution from incrementally one at a time to everything together + figure out how to handle ambiguity (i.e. same artifact, different version) as overlap is going to occur more often and more naturally.

**Comment by maxandersen** [comment]
master now has basic support for https on //FILES usage; meaning you can use a absolute url that does not need swizzling (i.e. gist urls wont work, but githubusercontent will)

**Comment by maxandersen** [comment]
//SOURCES is there too now. thus closing.
