### ISSUE TITLE
remote powershell fails to run java.exe or not download at all

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#397]
```
PS Z:\> iex "& { $(iwr https://ps.jbang.dev) } test.java"
& : The term '^C:\Users\max\scoop\apps\graalvm\current\bin\java.exe^' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:3
+ & ^"C:\Users\max\scoop\apps\graalvm\current\bin\java.exe^" -classpath ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (^C:\Users\max\s...t\bin\java.exe^:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

I thought maybe it was an issue i'm running from Z:\ so tried from C:\ and I get this:
```
PS C:\Users\max> iex "& { $(iwr https://ps.jbang.dev) } version"
Downloading JBang...
Error downloading JBang
PS C:\Users\max>
```

**Comment by maxandersen** [comment]
adding some error logging and I get: 

```
Downloading JBang...
DEBUG:   48+      >>>> New-Item -ItemType Directory -Force -Path "$TDIR\jars" >$null 2>&1
DEBUG:   49+      >>>> $jburl="https://github.com/jbangdev/jbang/releases/latest/download/jbang.zip"
DEBUG:   50+     try {  >>>> Invoke-WebRequest "$jburl" -OutFile "$TDIR\jbang.zip"; $ok=$? } catch {
DEBUG:   51+        >>>> $ok=$false
DEBUG:   52+        >>>> $error=$_
DEBUG:   54+     if ( >>>> -not ($ok)) {
DEBUG:   55+        >>>> [Console]::Error.WriteLine("Error downloading JBang from $jburl to $TDIR\jbang.zip")
Error downloading JBang from https://github.com/jbangdev/jbang/releases/latest/download/jbang.zip to \jbang.zip
DEBUG:   56+        >>>> [Console]::Error.WriteLine($error)
Access to the path 'C:\jbang.zip' is denied.
DEBUG:   57+        >>>> break
```

for some reason $TDIR is empty..

**Comment by quintesse** [comment]
THis part is weird: " The term '^C:\Users\max\scoop\apps\graalvm\current\bin\java.exe^' is not recognized"

It's as if the `JBANG_USES_POWERSHELL` isn't being set (on Windows it determines if it does CMD or PowerShell escaping)

**Comment by maxandersen** [comment]
im running it in powershell terminal if that mattters.

my java env might be weird so i'm more concerned about not downloading jbang...

**Comment by maxandersen** [comment]
so if I print out $JBIDR and $TDIR I get:

jbdir=Z:\jbangwin
tdir=

so tdir is for some reason blank ?

**Comment by quintesse** [comment]
What's "powershell terminal"?

And if you could figure out why your TDIR doesn't get set that would be really helpful, because of course It Works Here (tm)

**Comment by maxandersen** [comment]
line 37 in ps1 forgets to set TDIR :)

**Comment by quintesse** [comment]
> bdir=Z:\jbangwin

But are you setting`JBANG_DIR` or something? Because that's also a weird value

**Comment by maxandersen** [comment]
i think it works because you have full access to c:\

**Comment by maxandersen** [comment]
think I found it - let me submit a PR :)

**Comment by quintesse** [comment]
YEah, that's a bug in line 37, it should be TDIR, not JBDIR in the else

**Comment by maxandersen** [comment]
the java issue is because the latest download doesn't have the powershell flag logic.
