### ISSUE TITLE
Implement local catalog indices

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#406]
Just as we implemented local alias catalogs, with the concept of looking up an alias in the "nearest" catalog, we now want to extend that to the catalog index '~/.jbang/catalogs.json' as well.

The original idea was:

1. rename the file to `jbang-catalogs.json` for consistency
2. stay backward compatible with the old '~/.jbang/catalogs.json' (for now)
3. factor out the generic "find nearest" code so we don't duplicate it
4. add options to the catalog commands to explicitly set the catalogs file to use (like we do for alias)
5. split out the implicit catalogs to a different file (eg '~/.jbang/jbang-catalogs-implicit.json')

But the new idea is to:

1. store catalogs together with aliases in the same `jbang-catalog.json` file
2. either stay backward compatible with the old '~/.jbang/catalogs.json' or import it on first use
3. not needed anymore
4. stays the same
5. stays the same

Edit: updated description to better reflect the latest ideas

**Comment by maxandersen** [comment]
What would that file in #5 actually be used for ? Avoid iterating GitHub, girl AB, bitbucket locations ?

**Comment by quintesse** [comment]
Yeah, like I explained earlier, it could easily take 6-89 requests in worst case scenarios. That seems a bit excessive, right?
It's also easier to fit into the current system. Doing it without that file would require a more extensive rewrite.

**Comment by maxandersen** [comment]
so... `~/.jbang/cache/implicit-catalogs.json` ?
