### ISSUE TITLE
Allow specifying JVM flags

### ISSUE THREAD

**Issue by alblue** [jbangdev/jbang#418]
It would be good if you could also specify JVM flags when launching the script from JBang, such as `jbang --XX:+UseShenandoahGC` that would be passed to the JVM itself. You have this somewhat with the `-D` and `--jfr` flags, but they're specific for those two use cases. For some common options, like shenandoah, you could even map those flags directly to a --gc shenandoah flag.

**Comment by maxandersen** [comment]
We have support for that In the Java file using javac_options and Java_options - would make sense to to expose on cli but for now I've been holding back as haven't found a way to nicely separate javac vs java target flags.

**Comment by maxandersen** [comment]
Maybe just a raw --javac-options and --java-options option to mimick what you can do in the file would work. They would need splitting to be appended to the command line arguments.

**Comment by quintesse** [comment]
As just noticed while talking here https://github.com/jbangdev/jbang/discussions/988 it's strange that we can now set runtime options at least using aliases but we can still not do so with `jbang run`. Perhaps we should just use the same `--runopts` flag? And a `--buildopts` as well for good measure?

**Comment by quintesse** [comment]
Btw, it also shows that we should perhaps take another look at that `--runopt` name on `alias add`. It's abbreviated and not even in plural.

**Comment by maxandersen** [comment]
hmm - I honestly missed that :/ it should not be `--runopt` and most definitely should be availabe using jbang directly not just alias.

it should be the same setting/property/key we use across.

So `--java-options` and `--javac-options` would be the right names - wanna make a PR to fix that for 0.80th release?

**Comment by quintesse** [comment]
Sure, no problem!

**Comment by brunoborges** [comment]
I'd rather prefer `--jvm-options` to remove ambiguity with `--javac-options`, and the risk of failing due to a missing `c`.

**Comment by quintesse** [comment]
> I'd rather prefer `--jvm-options` to remove ambiguity with `--javac-options`, and the risk of failing due to a missing `c`.

Hmmm true. Wdyt @maxandersen ? It would mean that we're not using the same name as used in the code: `//JAVA_OPTIONS`. But perhaps this is something we could still change before 1.0? We could leave `//JAVA_OPTIONS` as an alias for `//JVM_OPTIONS` for a while before deprecating it.

**Comment by quintesse** [comment]
(Also is we'd ever want to consider supporting other languages perhaps we shouldn't use "JAVA" at all but more generic `RUN_OPTIONS` and `BUILD_OPTIONS`)

**Comment by grumpyf0x48** [comment]
> > I'd rather prefer `--jvm-options` to remove ambiguity with `--javac-options`, and the risk of failing due to a missing `c`.
> 
> Hmmm true. Wdyt @maxandersen ? It would mean that we're not using the same name as used in the code: `//JAVA_OPTIONS`. But perhaps this is something we could still change before 1.0? We could leave `//JAVA_OPTIONS` as an alias for `//JVM_OPTIONS` for a while before deprecating it.

Would be good to add a GRAALVM_OPTIONS at the same time (See https://github.com/jbangdev/jbang/issues/973) or before 1.0.

**Comment by brunoborges** [comment]
> (Also is we'd ever want to consider supporting other languages perhaps we shouldn't use "JAVA" at all but more generic `RUN_OPTIONS` and `BUILD_OPTIONS`, but admittedly that's very theoretical and far in the future if ever)

RUN_OPTIONS seems a bit of overkill, as you are unlikely to have different runtimes supporting the same parameters.

If user will run jbang with GraalVM, they should use GRAALVM_OPTIONS or --graalvm-options. Otherwise, it's a JVM.

**Comment by quintesse** [comment]
@brunoborges well @grumpyf0x48 just mentioned another runtime. So I'm not sure if it wouldn't just be simpler to have a single `--run-options`? The values are passed on to the runtime as-is, no parsing is done on them whatsoever and Jbang has no knowledge of what they mean.

**Comment by grumpyf0x48** [comment]
@quintesse regarding GraalVM, if i remember well, what is missing is adding parameters to `native_image` command which is used at compile stage not runtime.

**Comment by quintesse** [comment]
@grumpyf0x48 aha, makes sense of course. Then I retract what I just said. :-)

**Comment by maxandersen** [comment]
not disagreeing with the comments but I would for now at least stick with existing names (JAVAC_OPTIONS -> --javac-options and JAVA_OPTIONS -> --java-options) so we are consistent.

with respect to native-image it would be NATIVE_IMAGE_OPTIONS and --native-image-options

**Comment by brunoborges** [comment]
> not disagreeing with the comments but

Blasfemy!

**Comment by quintesse** [comment]
Created PR #989 for the `--java-options`, not for `--native-image-options` which needs a bit more work.

**Comment by maxandersen** [comment]
available in 0.80
