### ISSUE TITLE
windows testing broken since ps1 introduced

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#421]
not sure what is going on but since https://github.com/jbangdev/jbang/actions/runs/293033067 windows integration tests fails (silently) with:

```
D:\a\jbang\jbang\itests>jbang karate.java -o ..\build\karate *.feature 
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
```

meaning since 0.49 we haven't had a clean windows test build.

**Comment by maxandersen** [comment]
@quintesse any idea ?

**Comment by hbrands** [comment]
A small hint:
I observe the same problem on Windows executing jbang.cmd.
It seems to me that the cache directory (TDIR) is not created always.

When I add the following line
if not exist "%TDIR%" ( mkdir "%TDIR%" )
after the two lines
if "%JBANG_DIR%"=="" (set JBDIR=%userprofile%\.jbang) else (set JBDIR=%JBANG_DIR%)
if "%JBANG_CACHE_DIR%"=="" (set TDIR=%JBDIR%\cache) else (set TDIR=%JBANG_CACHE_DIR%)
the script seems to run.
But please verify.

**Comment by hbrands** [comment]
Earlier versions of the file contained the line
if not exist "%TDIR%\jdks" ( mkdir "%TDIR%\jdks" )
But that was moved to another location I think.

**Comment by quintesse** [comment]
That was indeed the main problem @hbrands , nice catch.

**Comment by quintesse** [comment]
Btw, the reason that it works outside the tests is because normally a user already has a `cache` folder so it doesn''t need to be created. But in the clean environments of the tests it would fail.
