### ISSUE TITLE
Invoke-Expression occured with jbang build

### ISSUE THREAD

**Issue by nodamushi** [jbangdev/jbang#427]
# Environment

- OS: `Windows 10 (1909)`
- PowerShell Version: `7.0.0` or `5.1.18362.752`
  - installer : `Scoop`
- jbang Version: `0.51.0`
- java/javac command version:  `AdoptOpenJDK 11.0.6.10`
- $env:JAVA_HOME:  64bit JDK 1.8.0_162  (Oracle JDK)

# Issue

An expression occured when I try to use `build` command.

![image](https://user-images.githubusercontent.com/581955/95734208-27717a80-0cbe-11eb-8d24-1e84b16a9fcb.png)

`$output` variable is empty.

![image](https://user-images.githubusercontent.com/581955/95736058-ab2c6680-0cc0-11eb-80e2-5fbffcd18161.png)

**Comment by maxandersen** [comment]
okey, reproduced with 0.51 - it might be fixed in master...checking

**Comment by maxandersen** [comment]
this is fixed in master - will be in 0.51.1 which is currently building. will be released in a few minutes.
