### ISSUE TITLE
run Maven artifacts directly

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#45]
Explore the possibility to do something like `jbang org.groupid:artifactid` or `jbang org.groupid:artifactid org.groupid.artifactid.MyMainClass` where the first argument would be the name of a Maven artifact to run.

The first form would be for a Maven artifact that has a `Main-Class` set in their `MANIFEST`, the second form would be for those that haven't.

@maxandersen suggested to use the form  `jbang mvn://org.groupid:artifactid` which would work too (although we could/should perhaps drop the 2 slashes)

**Comment by maxandersen** [comment]
reason for mvn:// would be its then a url which has special treatment anyway.

ultimately the logic would be something like this:

```
jbang <file>
if file.contents().startsWith("PK") {
   metadata = findMetadatafromurl(filepath); // here if mvn:// then use resolver to fetch dependencies as it’s a mvn location
   if metadata==null
      metadata = findMetadataInJar(filepath); // use what might be embedded in the jar pom.xml etc.
  lanch(filepath, metadata);
} else {
  doAsUsual();
}
```

then this could be used on a .jar directly.

**Comment by maxandersen** [comment]
thinking more of this it could just be:

`jbang org.groupid:artifactid:2.1` that is unique enough pattern to recognize as artifact.

for no main better to have it be:
`jbang org.groupid:artifactid:2.1#org.mymain.App` or similar. # is problematic for shells as its a comment thus maybe some other character

**Comment by quintesse** [comment]
We could perhaps do: `jbang org.groupid:artifactid:2.1/org.mymain.App`. Having several ´:´s is probably still enough to distinguish it from a URL.

**Comment by quintesse** [comment]
Btw, do you think there would be a way to leave out the version so it would use the "latest"? Or is that a concept that doesn't exist in Maven?

**Comment by maxandersen** [comment]
There are ways to look it up. Not sure which shrink-wraps support but we can figure ways around thst

**Comment by maxandersen** [comment]
in mvn 3 they removed the notion of latest and release as considered bad for repeatable builds. 

But mechanism to calculate it is still there used in mvn versions plugin (see https://www.baeldung.com/com maven-dependency-latest-version) we should be able to mimick whatever it does. 

I assume it's fetching metadata.xml and finding the highest versionin there.

**Comment by maxandersen** [comment]
considering #148 it would make sense that `jbang -jar <jar ref>` would be way to invoke this.

`<jar ref>` could be a file, url or a GAV - when -jar run mode is active the first arg are treated as a main classname instead of .java file to run.

ie.

`jbang -jar com.github.intuit.karate:karate-netty:e2882c4 com.intuit.karate.Main` 

then there is no ambiguity of when its "run this java/class" or "run this jar using optionally this class name"

**Comment by quintesse** [comment]
We'd still want to be able to detect it as much as possible, right? I mean `com.github.intuit.karate:karate-netty:e2882c4` is obviously a GAV, it can't be anything else. And anything that ends in `.jar` would be another good candidate.

**Comment by maxandersen** [comment]
well a GAV could be a jar or a pom.xml and technically it could be any kind of artifact.

**Comment by maxandersen** [comment]
committed support for resolving GAV's similar to how we do it for urls + now if file ends in .jar it will be launched directly. Thus in theory you could publish a .jsh or .java file and it would work too.

**Comment by maxandersen** [comment]
there is currently not a way to specify a alternate main class - once someone come up with an actual usecase and opens issue it should be fairly trivial to add...but struggling to see when you have a jar but no main class specified...

**Comment by quintesse** [comment]
> but struggling to see when you have a jar but no main class specified...

Well, it might be out of your control. For example PicoCli has an artifact for generating Graal configs. But it doesn't specify a Main CLass so you have to specify the main class explicitly (from their docs: https://picocli.info/man/gen-reflect-config.html)

We have the same in one of the Launcher artifacts. It has a utility class for doing some validations for files that people have to edit manually. But because it's not the main function of that artifact (which is just a library meant to be used by others) it's not specified as a Main Class.

Sure, both these examples are pretty esoteric (again that word :-) ), but I didn't even have to think hard about coming up with examples, so there must be many more :-)

**Comment by maxandersen** [comment]
If you got a GAV and related main class do share. 

My main gaf to implement it was having to actually setup a test case - thus if you got’em showem :)

**Comment by quintesse** [comment]
Won't that Picocli example I linked work?

**Comment by maxandersen** [comment]
That isn’t deployed to a Repo. Do you have the launcher gavs?

**Comment by quintesse** [comment]
It should be because this is how I use it:

```
import picocli.codegen.aot.graalvm.ReflectionConfigGenerator;

//usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS info.picocli:picocli:4.2.0
//DEPS info.picocli:picocli-codegen:4.2.0

class picocliCodegen {

    public static void main(String... args) {
        ReflectionConfigGenerator.main(args);
    }
}
```

**Comment by maxandersen** [comment]
okey okey, master now supports `jbang info.picocli:picocli-codegen:4.2.0/picocli.codegen.aot.graalvm.ReflectionConfigGenerator` - happy ? :)

**Comment by quintesse** [comment]
Interesting solution... will you be able to do this for URLs to JAR files as well? Seems like it could be difficult to determine where the URL ends and the main class name starts?

**Comment by maxandersen** [comment]
Well it was your idea to use / :)

And no it fails on urls and file paths thus why we went for -m/—main to set it explicitly.

**Comment by quintesse** [comment]
> Well it was your idea to use / :)

Even I can have bad ideas :-D

Actually I don't think we were thinking about JARs back then, so I only thought of a way to distinguish it from URLs to Scripts. But now that we URLs to JARs as well as Scripts my original idea just doesn't work anymore.
