### ISSUE TITLE
JBang start script gives an error when used with MSYS2

### ISSUE THREAD

**Issue by kjjaeger** [jbangdev/jbang#452]
I get this error when trying to run JBang on Windows using MSYS2 (https://www.msys2.org/) 
Unsupported Operating System: MSYS_NT-10.0-19041

I was able to solve the issue by editing the start script src/main/scripts/jbang replacing line 49
  CYGWIN*|MINGW*)
with
  CYGWIN*|MINGW*|MSYS*)

I may be making this into a pull request shortly.

**Comment by maxandersen** [comment]
this was merged
