### ISSUE TITLE
Support wildcard inclusion of sources

### ISSUE THREAD

**Issue by lincolnthree** [jbangdev/jbang#464]
```
//SOURCES MyClass.java
```

This works for super simple projects, but really doesn't allow you to easily expand/refactor into something more organized, as one quickly needs to create multiple files for interfaces, classes, etc.

Java is still Java, and I think it's important to respect the fact that Java loves to have a file for each type definition.

We really need:

```
//SOURCES src/api/*.java
//SOURCES src/impl/*.java
//SOURCES src/model/*.java
```

Or even just the following, to add a directory to the classpath. Then Java could do its normal classpath resolution of sources:
```
//SOURCE_DIR src/main/java
```
Should support the following file structure:

```
src/main/java/com/example/foo/Foo.java
src/main/java/com/example/foo/Bar.java
```

**Comment by maxandersen** [comment]
They wouldn't have src/ as the file is already in the src folder. 

Otherwise yeah. I was thinking to use traditional ant matching rules which seem to be the standard in most. So **/*.java would work or just .

**Comment by lincolnthree** [comment]
Details ;) Yeah that would work. Just need something to make multi-source projects possible. 

I had to ditch and use Maven for the time being because I'm up to 15 files now and it was getting ... and without the ability to move/rename/create files in the IDE, and without the ability to point the IDE at the actual project directory, it was just a bit too much to manage with JBang.

**Comment by maxandersen** [comment]
just for my own reference: https://github.com/azagniotov/ant-style-path-matcher

**Comment by quintesse** [comment]
@maxandersen isn't the default Java PathMatcher sufficient? That might be a more efficient option than adding another library: https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-

**Comment by maxandersen** [comment]
Wasn't aware of that class - nice!

but that one seem to do OS specific matching (i.e. \ and / behaves differently).
we need a OS neutral format that works the same on both Linux/OSX and Windows.

**Comment by quintesse** [comment]
That would be unfortunate. But the messages I read while searching for this issue seem conflicted. Some say the UNIX version works on Windows too while other suggest to just replace any forward slashes with the necessary platform one using `File.separator`.

Although in the case of the glob matcher you have to do double backslashes on Windows, so probably just easier to do:

```java
String pattern = ...
if (Util.isWindows()) {
   pattern = pattern.replace("/", "\\\\");
}
```

**Comment by lincolnthree** [comment]
Don't forget Windows drive letters... :/

https://github.com/forge/core/blob/master/resources/api/src/main/java/org/jboss/forge/addon/resource/util/ResourcePathResolver.java

**Comment by maxandersen** [comment]
Absolute paths should be verboten anyway...I think.

**Comment by quintesse** [comment]
I don't think drive letters would cause problems, but yeah absolute paths aren't very useful I think. Still, don't think we need to forbid them either.

**Comment by quintesse** [comment]
Ok, on the one hand I understand. Perhaps limiting sources to relative paths that don't escape from the "root" of the primary including source file would be a good idea.  On the other hand you're already trusting the source, otherwise you couldn't even execute it. So why add a second layer of security on top of that?

**Comment by lincolnthree** [comment]
Yeah there's nothing stopping someone from doing that anyway.

**Comment by maxandersen** [comment]
good news - below works equally well afaics on windows and osx thus JDK PathMatcher it is.

```
///usr/bin/env jbang "$0" "$@" ; exit $?
// //DEPS <dependency1> <dependency2>

import static java.lang.System.*;

import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.FileVisitResult;
import java.nio.file.FileVisitor;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;

public class test {

    public static void main(String... args) throws IOException {
        out.println("Hello World");

        var matcher = FileSystems.getDefault().getPathMatcher("glob:**/jbang/**/*.java");

        Path startDir = Path.of(".");
        
        FileVisitor<Path> matcherVisitor = new SimpleFileVisitor<Path>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attribs) {
                if (matcher.matches(file)) {
                    System.out.print(String.format("Found matched file: '%s'.%n", file));
                }
                return FileVisitResult.CONTINUE;
            }
        };
        Files.walkFileTree(startDir, matcherVisitor);
    }
}

```

**Comment by maxandersen** [comment]
gah....but it won't allow `myfolder/*.java` it insists on `**/myfolder/*.java` ...that isn't nice.

**Comment by quintesse** [comment]
Are you sure? That would seem like a totally ridiculous requirement.

**Comment by maxandersen** [comment]
never mind - I was matching against full path rather than the relative one ;)

**Comment by lincolnthree** [comment]
@maxandersen Is this in a branch we could try? :)

**Comment by lincolnthree** [comment]
Gotcha :) I did manage to get jbang working to install java if and exec my compiled executable jar, though, so all is not lost!

**Comment by maxandersen** [comment]
so while hooking this in I just realized javac is smart and we probably don't need `//SOURCES **/*.java` or even `//SOURCE xyz.java` support; at least not for the trivial cases.

javac will actually include sources that are resolvable based on package name (incl. default).

So, if you have:

````
myscript.java
otherscript.java
nested/A.java
nested/B.java
````

And `myscript.java` has `otherscript` or `nested.A` references then `jbang myscript` actually already work today. Pretty darn nice!

@lincolnthree should "just work" for you example!

Pretty fun I and well we all  missed this just works :) 

/cc @tivrfoa fyi

**Comment by maxandersen** [comment]
note, javac does have limits, thus `//SOURCES <pattern>` does have usages:

1) as a source of files to define what needs to be available for `jbang edit`
2) remote files won't be able to resolve sibling sources
3) if you want to include classes that are not necessarily all interconnected (i.e. in libraries/apis)
4) when using sibling packages javac is not smart enough

**Comment by tivrfoa** [comment]
Very nice! :)

```shell
no-source$ tree
.
├── A.java
├── B.java
└── pkg1
    └── C.java

1 directory, 3 files
leandro:no-source$ jbang A.java 
I'm B
I'm C
leandro:no-source$ cat A.java 
public class A {
    
    public static void main(String args[]) {
        B.say();
		pkg1.C.say();
    }
}
```
Just to mention that then any `//SOURCES` and `//DEPS` will *only* be scanned in the first file (main). In your example `myscript`.

**Comment by tivrfoa** [comment]
>     4\. when using sibling packages javac is not smart enough

Could you give an example, please?

**Comment by tivrfoa** [comment]
> > ```
> > 4\. when using sibling packages javac is not smart enough
> > ```
> 
> Could you give an example, please?

This works:
```shell
jbang A.java 
[jbang] Building jar...
I'm B
I'm C
I'm D
leandro:no-source$ tree
.
├── A.java
├── B.java
├── pkg1
│   └── C.java
└── pkg2
    └── D.java

2 directories, 4 files
leandro:no-source$ cat A.java 
public class A {
    
    public static void main(String args[]) {
        B.say();
		pkg1.C.say();
		pkg2.D.say();
    }
}
```

**Comment by maxandersen** [comment]
Yes, root can find children. But try have `pkg1.C` refer to to `pkg2.D` (i.e. its sibling package) that fails.

**Comment by tivrfoa** [comment]
> Yes, root can find children. But try have `pkg1.C` refer to to `pkg2.D` (i.e. its sibling package) that fails.

It worked for me! :open_mouth: :blush:

```java
package pkg1;

public class C {
    
    public static void say() {
		System.out.println("I'm C");
		System.out.print("Can you hear me D? ");
		pkg2.D.say();
    }
}
```

**Comment by maxandersen** [comment]
Remove the default package class and try again.

**Comment by tivrfoa** [comment]
> Remove the default package class and try again.

If jbang is run from the project root folder it works, javac finds all classes.
But if the main script is in a package and the jbang is not run from root folder, then it doesn't find classes in other packages.
eg: Main.java is in `package a;`
this works: jbang a/Main.java
but this doesn't: jbang Main.java

Although it should be easy to fix.
We should set `--source-path`.
eg: /home/user/jbang/scripts/a/Main.java
`--source-path /home/user/jbang/scripts`

I tried the following and it works:
```sh
javac --source-path /home/leandro/dev/java/jbang/no-source/ /home/leandro/dev/java/jbang/no-source/a/A.java
```
Although jbang complains, and I don't why:
**error: invalid flag: --source-path /home/leandro/dev/java/jbang/no-source/**

```sh
./jbang/bin/jbang --verbose /home/leandro/dev/java/jbang/no-source/a/A.java
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] Building jar...
[jbang] compile: /usr/lib/jvm/java-11-openjdk-amd64/bin/javac -d /home/leandro/.jbang/cache/jars/A.java.d1d0e20c53b0177439a2a5ffbeb37dcdb4c9f136d61064199a29fda3d577a9c6 --source-path /home/leandro/dev/java/jbang/no-source/ /home/leandro/dev/java/jbang/no-source/a/A.java
error: invalid flag: --source-path /home/leandro/dev/java/jbang/no-source/
Usage: javac <options> <source files>
use --help for a list of possible options
[jbang] [ERROR] Error during compile
dev.jbang.ExitException: Error during compile
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:177)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:64)
	at dev.jbang.cli.Run.doCall(Run.java:53)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)
```

**Comment by maxandersen** [comment]
looks like you passed "--source-path home/leandro/dev/java/jbang/no-source/" to command line arguments instead of "--source-path", "home/leandro/dev/java/jbang/no-source/".

**Comment by maxandersen** [comment]
Was released
