### ISSUE TITLE
jbang cache clear does not nuke dependency cache

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#475]
run jbang cache clear and ~/.jbang/cache/depcache* still exist and has content. It should be empty.﻿

**Comment by quintesse** [comment]
Empty? Or deleted?

And do we want to create a cache "category" for that? Or should it just always be cleared? Or should we make it part of one of the existing categories? (Eg. the `jars` one)

**Comment by maxandersen** [comment]
its a separate one.
