### ISSUE TITLE
Dependency cache can be wrong

### ISSUE THREAD

**Issue by dmlloyd** [jbangdev/jbang#478]
Sometimes, particularly when handling snapshots, the dependency cache can be aggressively out of date.  It should compare timestamps or something to ensure that the cached dependency set still makes sense.

In conjunction with #475 this can cause some awkwardness.

The workaround is, if classpaths are coming up wrong, `rm ~/.jbang/cache/dependency_cache.json`.  Once #475 is fixed, `jbang cache clear` should do the job.

**Comment by quintesse** [comment]
I also think a `--rebuild` option or something similar is still useful. The cache clear is bit of a scattergun approach.

**Comment by maxandersen** [comment]
'jbang --fresh run' was my thinking to indicate to not do cache lookups but still cache the result. 

Instead of 'jbang --no-cache ...'

**Comment by quintesse** [comment]
Fixed by https://github.com/jbangdev/jbang/pull/699
