### ISSUE TITLE
Suggestion: structure the Readme.md into separate web pages

### ISSUE THREAD

**Issue by nmcl** [jbangdev/jbang#501]
Having a single (and large) web page covering everything from into to installation and beyond is so ... 1980s :)

**Comment by tivrfoa** [comment]
Yes. It's useful but can be a little frightening for some users. =)
People first want to know what they are able to do with Jbang, why would they use it.
A Installation.md with just one link (not collapsed) from readme would already reduce the size significantly.

**Comment by quintesse** [comment]
True @nmcl , but it would mean having to introduce some kind of search functionality because CTRL+F will become mostly useless. I think we're somewhat influenced by projects like [PicoCli](https://picocli.info/) :-)

**Comment by maxandersen** [comment]
I kinda wanted for a while to move docs to something a bit more suitable to host on jbang.dev/docs and then make the readme on GitHub simpler. 

Just wanted to find a way to avoid moving the docs away from the code but still have it pushed automatically. Probably just need a bit of.github action magic.

**Comment by maxandersen** [comment]
github action magic + a bit of antora magic dust and this is now done. 

for now split up just in "raw" form from index.adoc - structure can be improved but now the mecahnics are in place including search.
