### ISSUE TITLE
Trusted URL not working?

### ISSUE THREAD

**Issue by nmcl** [jbangdev/jbang#503]
In the Readme.md ...

"For safety reasons jbang will not run arbitrary urls before you indicated you trust their source. "

Yet I was able to run "jbang https://github.com/jbangdev/jbang/blob/master/examples/helloworld.java" without adding the GitHub repo to a trusted domain. In fact trusted-sources.json doesn't even exist at this stage.

**Comment by quintesse** [comment]
IIRC jbangdev is pre-trusted, so to speak ([yup](https://github.com/jbangdev/jbang/blob/master/src/main/java/dev/jbang/TrustedSources.java#L128)). But that should probably be mentioned in the docs.

**Comment by nmcl** [comment]
Yeah, definitely not clear in the doc when that URL is used to illustrate an untrusted site ;) Maybe make it clear and use a different (untrusted) URL?

**Comment by maxandersen** [comment]
thanks, fixed - now using https://gist.github.com/maxandersen/f43b4c52dfcfc42dcd59a04e49acf6ec as example instead.
