### ISSUE TITLE
jsh not cached

### ISSUE THREAD

**Issue by vorburger** [jbangdev/jbang#506]
Looks like `.jsh` (https://github.com/jbangdev/jbang#using-jsh-for-jshell) are not yet cached? Probably just didn't get to it yet, not intentional?

This demonstrates what I mean, notice that the second invocations take roughly the same time as the initial one:

```shell
$ echo 'System.out.println("Hello World");' >first.jsh

$ time ./jbang first.jsh
Hello World

real    0m3.612s
user    0m9.165s
sys     0m0.429s

$ time ./jbang first.jsh
Hello World

real    0m3.543s
user    0m8.959s
sys     0m0.402s

$ time ./jbang first.jsh
Hello World

real    0m3.485s
user    0m8.902s
sys     0m0.437s
```

Whereas `.java` clearly are cached (https://github.com/jbangdev/jbang#caching):

```shell
$ ./jbang init first.java
[jbang] File initialized. You can now run it with 'jbang first.java' or edit it using 'jbang edit --open=netbeans first.java`'

$ time ./jbang first.java
[jbang] Building jar...
Hello World

real    0m2.004s
user    0m4.366s
sys     0m0.256s

$ time ./jbang first.java
Hello World

real    0m0.798s
user    0m1.633s
sys     0m0.128s

$ time ./jbang first.java
Hello World

real    0m0.869s
user    0m1.790s
sys     0m0.140s
```

**Comment by quintesse** [comment]
Somebody correct me if I'm wrong, but AFAIK that's because .jsh files don't get compiled, they are always interpreted and therefore always as fast/slow as the first time.

**Comment by vorburger** [comment]
> that's because .jsh files don't get compiled, they are always interpreted and therefore always as fast/slow as the first time.

If that's the case (and won't change any time soon?), shall we add a line about it to https://github.com/jbangdev/jbang#using-jsh-for-jshell, and then close this as "working as intended, and now documented"?

**Comment by maxandersen** [comment]
Correct. Jsh can't be cached. +1 for Clarifying in docs
