### ISSUE TITLE
jbang install

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#514]
we should have a `jbang install` that would make the app/script available on the users path. kinda like `go install`.

i.e. `jbang install myscript.java`  would put a `myscript` script or `myscript.cmd` in `~/.jbang/bin` 

the `jbang/bin` gets added by some setup in users env/shell files.

**Comment by quintesse** [comment]
We can close this issue, right?

**Comment by maxandersen** [comment]
spring cleaning!
