### ISSUE TITLE
.env support?

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#515]
Most tools support to load  loads .env files,  and make it easy to populate environment variables.   

jbang could load .env file of current directory, and add them as env variables for jbang scripts.  it's very useful to customize the settings to execute script, such as database jdbc url, username, passwod etc.

**Comment by linux-china** [comment]
sorry, maybe I should consider to use https://github.com/cdimascio/dotenv-java to load env variables.

**Comment by maxandersen** [comment]
yeah, if you are looking for your script to have env vars made available its better to do that with your own dependency as jbang is not active when your script/app runs.

**Comment by maxandersen** [comment]
closing this as better done by apps on their own.
