### ISSUE TITLE
have util.info use logging via static global to have logging honor verbose

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#52]

**Comment by AtharvaThorve** [comment]
Would you please provide more information on this issue?

**Comment by maxandersen** [comment]
util.info() can't know if the user provided verbose info flag atm, thus can't know if okey to print details about exception or not.

issue here is about getting that logging configured/handled better.

**Comment by AtharvaThorve** [comment]
Okay, so a new verbose flag is needed to be added here right which will decide whether to print complete info about the message or just the highlights?
Also, this flag will be provided by the user?

**Comment by maxandersen** [comment]
there already are a flag (--verbose) its just that not all parts of the logging code actually honors or even have access to the flag.

**Comment by AtharvaThorve** [comment]
verbose flag is only available in BaseCommand.java file and all the references are non-static while all the references in Util.java file are static so it is not able to access it.<br>
Is there a workaround for this?

**Comment by maxandersen** [comment]
thats what this issue is about - picking a workaround ;) 

probably a static global verbose which --verbose sets.

**Comment by maxandersen** [comment]
fixed this by adding global static verbose boolean to util.java

not great; but works for now.

**Comment by AtharvaThorve** [comment]
We can also do this by making a class that handles and stores information of all the flags right and just use that class static variables wherever needed.

**Comment by AtharvaThorve** [comment]
> fixed this by adding global static verbose boolean to util.java
> 
> not great; but works for now.

Even I was working on a similar approach but had a little issue with time management 😅.
