### ISSUE TITLE
use of //FILES relative to a github.com swizzled file breaks

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#537]
try out jbang https://github.com/maxandersen/javafx-basic-animation/blob/files/JBangLogoBouncingAnimation.java﻿

it works locally but not via swizzled url.

nonswizzled works jbang --fresh https://raw.githubusercontent.com/maxandersen/javafx-basic-animation/files/JBangLogoBouncingAnimation.java

**Comment by quintesse** [comment]
@maxandersen isn't this a dup of https://github.com/jbangdev/jbang/issues/534 ?

**Comment by maxandersen** [comment]
One is swizzle the other is alias location messing with resolve. Related but not duplicate.

**Comment by quintesse** [comment]
Well, actually it might be a duplicate anyway. The fix for #534 seems to fix this as well :-)
(Needs more testing)

**Comment by maxandersen** [comment]
true - and it might just be enough as the fix implicitly makes the relative resolve work in this case as with the fix it is resolved relatively against an already swizzled url. Makes sense then so I think we are good.
