### ISSUE TITLE
jbang setup

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#539]
This is the last part of the "zero install" initiative, a command that will add Jbang to the user's PATH.

Although it can be run by any copy of Jbang (installed in whatever way available) the setup command will always use the version of Jbang installed in `~/.jbang/bin`. If that doesn't exist Jbang will be downloaded and installed there just like that startup scripts do.

It's especially useful when doing: `curl -Ls https://sh.jbang.dev | bash -s - setup` , this will not only download and run Jbang, but it will also install it permanently into the user's PATH.

This issue is also the first step in implementing #514

**Comment by maxandersen** [comment]
One thing to note is that we should be able to do jbang install without requiring jbang setup to have run. 

I assume that is feasible but just wanted to state that explicitly as we need to be sure we don't rely on jbang being in specific bin folder.

**Comment by quintesse** [comment]
> One thing to note is that we should be able to do jbang install without requiring jbang setup to have run.
> 
> I assume that is feasible but just wanted to state that explicitly as we need to be sure we don't rely on jbang being in specific bin folder.

You're right. Perhaps we shouldn't automatically assume we want Jbang to be downloaded and installed when we run `jbang setup`. Maybe add a `--with-jbang` just like there's a `--with-java`? Without that we only add `~/.jbang/bin` to the user's PATH (regardless if jbang is in there or not). That way the code can simply be re-used by `install`.

**Comment by fbricon** [comment]
I'm using zsh, jbang doesn't like me missing .bashrc:

<img width="889" alt="Screenshot 2020-11-26 at 13 05 18" src="https://user-images.githubusercontent.com/148698/100349161-4ca91680-2fe8-11eb-81fa-4ebcf3ae00cc.png">

**Comment by fbricon** [comment]
also latest jbang is already installed (I'm running it!), "[jbang] Downloading and installing Jbang..." is confusing

**Comment by quintesse** [comment]
@fbricon yeah, that' still gonna change. You can actually run jbang and not have it installed, so that'w where that comes form. But it is something we want to change. Soon.

**Comment by maxandersen** [comment]
this is done. improvements/bugs goes to other issue(s)
