### ISSUE TITLE
jbang bouncinglogo@jbangdev fails to copy images

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#541]
similar to #534 

`❯ jbang --verbose --fresh bouncinglogo@jbangdev
[jbang] Reading aliases from /Users/max/.jbang/implicit-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/quarkusio/jbang-catalog/master/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/quarkusio/jbang-catalog/blob/master/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/cache/urls/c79114b08f217b977a92049e80c21d920728b32cbc0944906eb8c616b32bda71/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/zemiak/javakarel/master/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/zemiak/javakarel/blob/master/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/cache/urls/4b822aa749af0c178d2ebf105a515ac0c216bf976939b2d879aaf9e8bc2adc0e/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/jruby/jbang-catalog/master/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/jruby/jbang-catalog/blob/master/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/cache/urls/23afa01792d8488c13620869b43c9b882d6a771e60564100ad69c40a03288f93/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/maxandersen/jbang-catalog/master/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/maxandersen/jbang-catalog/blob/master/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/cache/urls/12cee842a085318cb370d234493f93def3225bf51f011de2d691f643e5f1d75a/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/jacoco/jbang-catalog/main/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/jacoco/jbang-catalog/blob/main/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/cache/urls/ab08c62cd98c3ec7a71e132fe0bb7e536db7ee98387adf5c00bb546ad54f71f5/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/jacoco/jbang-catalog/HEAD/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/jacoco/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/cache/urls/f95e1762ebee995668e90d0709f1e2e530695f2d1b06d45befc5bf1c29a5d81f/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/linux-china/jbang-catalog/HEAD/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/linux-china/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/cache/urls/639c6b25c4ccbe4c3e35692c026de0db6e3dfd4d86e2eaa04ce4dd8fb996c816/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/jbangdev/jbang-catalog/master/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/jbangdev/jbang-catalog/blob/master/jbang-catalog.json
[jbang] Reading aliases from /Users/max/.jbang/cache/urls/22276b0e71b9dc0e466e9158ad103a5d9175aaadaed34eeb3bb6c8b25b80ddde/jbang-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/jbangdev/jbang-catalog/master/jbang-catalog.json = /Users/max/.jbang/cache/urls/22276b0e71b9dc0e466e9158ad103a5d9175aaadaed34eeb3bb6c8b25b80ddde/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/jbangdev/jbang-catalog/blob/master/jbang-catalog.json
[jbang] Reading aliases from /Users/max/code/personal/jbang/jbang-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/jbangdev/jbang-catalog/master/jbang-catalog.json = /Users/max/.jbang/cache/urls/22276b0e71b9dc0e466e9158ad103a5d9175aaadaed34eeb3bb6c8b25b80ddde/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/jbangdev/jbang-catalog/blob/master/jbang-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/jbangdev/jbang-catalog/master/jbang-catalog.json = /Users/max/.jbang/cache/urls/22276b0e71b9dc0e466e9158ad103a5d9175aaadaed34eeb3bb6c8b25b80ddde/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/jbangdev/jbang-catalog/blob/master/jbang-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/jbangdev/jbang-catalog/master/jbang-catalog.json = /Users/max/.jbang/cache/urls/22276b0e71b9dc0e466e9158ad103a5d9175aaadaed34eeb3bb6c8b25b80ddde/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/jbangdev/jbang-catalog/blob/master/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/jbangdev/jbang-catalog/master/bouncinglogo.java
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] Resolving dependencies...
[jbang]     Resolving org.openjfx:javafx-controls:11.0.2:mac...Done
[jbang]     Resolving org.openjfx:javafx-graphics:11.0.2:mac...Done
[jbang] Dependencies resolved
[jbang] Copying https:/raw.githubusercontent.com/jbangdev/jbang-catalog/master/images/jbang-icon.png to /Users/max/.jbang/cache/jars/bouncinglogo.java.4d3567eda5cfc4d6217a11b57f140bdb647e2aacc91fe9fade734ce44eec18b4/images/jbang-icon.png
[jbang] Deleting /Users/max/.jbang/cache/jars/bouncinglogo.java.4d3567eda5cfc4d6217a11b57f140bdb647e2aacc91fe9fade734ce44eec18b4
[jbang] [ERROR] Could not copy https:/raw.githubusercontent.com/jbangdev/jbang-catalog/master/images/jbang-icon.png to /Users/max/.jbang/cache/jars/bouncinglogo.java.4d3567eda5cfc4d6217a11b57f140bdb647e2aacc91fe9fade734ce44eec18b4/images/jbang-icon.png
dev.jbang.ExitException: Could not copy https:/raw.githubusercontent.com/jbangdev/jbang-catalog/master/images/jbang-icon.png to /Users/max/.jbang/cache/jars/bouncinglogo.java.4d3567eda5cfc4d6217a11b57f140bdb647e2aacc91fe9fade734ce44eec18b4/images/jbang-icon.png
	at dev.jbang.FileRef.copy(FileRef.java:68)
	at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:172)
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:129)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:70)
	at dev.jbang.cli.Run.doCall(Run.java:59)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.nio.file.NoSuchFileException: https:/raw.githubusercontent.com/jbangdev/jbang-catalog/master/images/jbang-icon.png
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
	at java.base/java.nio.file.Files.copy(Files.java:1294)
	at dev.jbang.FileRef.copy(FileRef.java:66)
	... 14 more
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```


...notice its treating the url as a file not url.


another weirdness...why is it contacting that many catalogs?

**Comment by quintesse** [comment]
> another weirdness...why is it contacting that many catalogs?

Possibly because you've specified `--fresh`, it's trying to find the alias and it just happens to be in the last one.
Perhaps "fresh" shouldn't be cascaded down into getting the catalogs, but it wouldn't surprise if that's how it works now.

**Comment by maxandersen** [comment]
Since I'm specifying specific catalog it shouldn't have to load them all. 

And --fresh must reload catalogs too as it's just broken UX we have without it imo.

**Comment by quintesse** [comment]
> Since I'm specifying specific catalog it shouldn't have to load them all.

True, most likely the code doesn't take that into account.
