### ISSUE TITLE
How to jbang URLs from Trusted Sources via Proxy?

### ISSUE THREAD

**Issue by cleverpig** [jbangdev/jbang#547]
I can't connect gist directly, So How to get URLs from Trusted Sources via Proxy?
Setting JAVA_OPTION?

![image](https://user-images.githubusercontent.com/580435/100309258-62690c80-2fe5-11eb-8d82-147ece5acaf7.png)

**Comment by maxandersen** [comment]
That should work - we use standard java http connection to get those.

**Comment by cleverpig** [comment]
> That should work - we use standard java http connection to get those.

It works!
set JAVA_TOOL_OPTIONS="-Djava.net.useSystemProxies=true"

refer from: https://github.com/jbangdev/jbang#debug-jbang-itself
