### ISSUE TITLE
confusing message for first time user

### ISSUE THREAD

**Issue by gavinking** [jbangdev/jbang#551]
You can now run it with 'jbang test.java' or edit it using 'jbang edit --open=code test.java`'

1. You don't explain what "code" is here.
2. It's actually not the best syntax to use for Unix.
3. There's a weird unmatched backtick.

JBang should know it's running on Unix, and suggest me the best syntax for me. Also, it should clarify what "code" means.

Note that this is only a problem the *very first* time you use jbang.

**Comment by quintesse** [comment]
> It's actually not the best syntax to use for Unix.

What are you referring to exactly?

Agreed on 1 and 3 (of course)

**Comment by gavinking** [comment]
I mean I prefer 

    idea `jbang edit test.java` 

Or whatever, I forget because I'm posting from my phone.

**Comment by quintesse** [comment]
Aha, I understand. I'm guessing this might be because there's also a "live" option that will re-generate project files on-the-fly. Perhaps also so you can clean up after you're done. But @maxandersen can give more info.

**Comment by maxandersen** [comment]
Yeah - I used that format earlier but had issues. Ie. The syntax shown works equally well on all platforms, works with --live option and it doesn't require a US keyboard layout to write fairly easily. We could add the second option but gets long. 

About explaining what code is I guess we could add more text it will be even longer though. Suggestion for something good but short ?

**Comment by gavinking** [comment]
> The syntax shown works equally well on all platforms, works with --live option and it doesn't require a US keyboard layout to write fairly easily. We could add the second option but gets long.

Well it's pretty easy to check that I'm on a Unix.

The keyboard layout thing I'm not sure about but perhaps even that's accessible somewhere....

**Comment by gavinking** [comment]
Suggestion for something good but short ?

    'jbang edit --open=[ide] test.java` where [ide] is your IDE command

**Comment by gavinking** [comment]
> The keyboard layout thing I'm not sure about but perhaps even that's accessible somewhere....

Seems to be `InputContext.getInstance().getLocale()`

**Comment by quintesse** [comment]
I think what Max refers to is that back-quotes can get somewhat difficult on certain keyboards.... now where did I hear people complain about that, loudly, before? Hmmm.... :-)

**Comment by gavinking** [comment]
Hahah yeah and my opinion remains that professional programmers who are silly enough to use a non-USA keyboard for coding pretty much deserve what they get 🤣🤣

But seriously, that AWT thingy seems to be a way to detect that the user has a US keyboard.

(*Whatever*, it is the approach you suggest in the JBang documentation.)

**Comment by gavinking** [comment]
> Hahah yeah and my opinion remains that professional programmers who are silly enough to use a non-USA keyboard for coding pretty much deserve what they get 🤣🤣


It's possible I'm just mad about there being no such thing as an Australian keyboard layout.

**Comment by gavinking** [comment]
On zsh, `idea $(j! edit test)` is another option.

**Comment by gavinking** [comment]
Or, alternatively, and probably even better, you could let me set up my editor once:

    j! set editor=idea

And then I could use the even shorter syntax

    j! edit test.java

**Comment by maxandersen** [comment]
> It's possible I'm just mad about there being no such thing as an Australian keyboard layout.

Isn't that where all the keys are upside down ?

**Comment by maxandersen** [comment]
> ```
> j! set editor=idea
> ```

from https://github.com/jbangdev/jbang#editing

"The editor used will be what is specified as the argument to --open or default to $JBANG_EDITOR, $VISUAL or $EDITOR in that order."

so that is already supported - just that picocli has a bug/feature where `jbang --open test.java` isn't doing what you expect so for now you need to do `jbang --open=. test.java`

once next version of picocli is out we can make it shorter and use defaults more natural.

**Comment by maxandersen** [comment]
made pr #555 to try improve...not sure if too long..
