### ISSUE TITLE
// commands should ignore content after //

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#567]
while writing a blog I realized it is not possible to use asciidoc markers on //DEPS lines.

this fails:

//DEPS info.picocli:picocli:4.5.0  // <.>
//DEPS org.zeroturnaround:zt-exec:1.12 // <.>
//DEPS commons-codec:commons-codec:1.15 // <.>
//DEPS org.slf4j:slf4j-nop:1.7.30 // <.>﻿

wondering if we can just strip out // contents before parsing ?

**Comment by quintesse** [comment]
Well... we do allow URLs there so double slashes are legal. Perhaps by requiring that they are preceded by a space at least?

**Comment by maxandersen** [comment]
yeah basically strip off anything after ' // ' before splitting the string
