### ISSUE TITLE
have --version error message include hint about version

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#601]
got more than a few comments on that `jbang --version` does not work. I really don't want it to be default nor visible but I also understand it is a common way to check if sometihng installed.

I suggest we either catch the error or make a `--version` hidden flag which would output somethin like:

```
Unknown option: '--version'
Possible solutions: version
Please use 'jbang version' instead but just to be nice here is the version:
0.56.0
```

**Comment by jmini** [comment]
I just tried `jbang --version` and was also expecting a result instead of:

```
$ jbang --version
Unknown option: '--version'
Possible solutions: --verbose
```

FYI: the next command I tried was `jbang -v`

**Comment by maxandersen** [comment]
added `-V` and `--version` as basic command that prints the version.

you can/should still use `jbang --verbose version` if you want more detailed info about the installation/setup.

**Comment by maxandersen** [comment]
@all-contributors please add @jmini for bug
@all-contributors please add @ge0ffrey for bug

**Comment by maxandersen** [comment]
@all-contributors please add @jmini for bug

**Comment by maxandersen** [comment]
@all-contributors please add @ge0ffrey for bug
