### ISSUE TITLE
jbang export UX

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#609]
`jbang export` to existing path gives:

```
[jbang] [ERROR] /Users/max/code/personal/jbang-minecraft/mods/ExamplePlugin.jar
[jbang] Run with --verbose for more details
```

1) should not have to do `--verbose` to be told it is because existing file
2) should have way to force overwrite, i.e. `--force` / `-f`

**Comment by quintesse** [comment]
You want it like that or should we just always overwrite? (I didn't implement it with the intention to have it fail when the file already exists TBH)

**Comment by maxandersen** [comment]
Since it's "outside" jbangs controlled dirs I lean towards requiring --force.
