### ISSUE TITLE
add `--repos` support

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#611]
would be nice not having to have intermediate `.java` file and instead just do:

``` jbang --repo https://repo.spongepowered.org/maven org.spongepowered.spongevanilla:spongevanilla:1.12.2-7.3.1-RC395```

**Comment by quintesse** [comment]
We didn't have this issue yet? Tsk tsk

**Comment by maxandersen** [comment]
I think we did but a search didn't find it so I created one :)

**Comment by quintesse** [comment]
Finally finished this code and opened a PR for it. I think this is something we can add to 1.0.

**Comment by quintesse** [comment]
Was don ein PR https://github.com/jbangdev/jbang/pull/1081. Closing.
