### ISSUE TITLE
remove examples folder from distribution 

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#617]
for a while we've had both jbang/examples and jbang-examples - i think its time to just kill jbang/examples leaving just a pointer to jbang-examples except for any examples that leaked into tests.

﻿

**Comment by quintesse** [comment]
+1

Btw in several cases I needed example scripts for my tests I just copied them to the itests folder. We could prehaps do that instead of leaving some scripts in the examples folder?

**Comment by maxandersen** [comment]
Yes - it's a "bug" examples leaked into tests.

**Comment by maxandersen** [comment]
and poof - they are gone and moved to jbang-examples.

fixed in #624
