### ISSUE TITLE
Jbang edit is too fast at installing default editor

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#641]
Should give user choice before downloading.

**Comment by maxandersen** [comment]
from #638:

If you really really want this I'd suggest something like:

```
$ jbang edit --open xxx
You didn't specify an editor and no default editor was set.
The following editors were found on your system, make a choice:
 1. IntelliJ IDEA (/opt/idea/bin/idea)
 2. Eclipse (/usr/bin/eclipse)
 3. Visual Studio Code (~/bin/code)
 4. Download and install Visual Studio Codium
Type selection: 2
How do you want to use Eclipse?
 1. Only this time?
 2. Use and set as default for the future
Type selection: 2
Setting Eclipse as default editor.
... 
```

**Comment by grumpyf0x48** [comment]
It would be nice to have the same feature for downloading the JDK when no Java is available.

**Comment by maxandersen** [comment]
I don't want to add a interactive question for the main flow of jbang - in that case we are checking if the only viable option (i.e. `java`) are available in the PATH ...for edit which is more like a secondary flow of jbang we can't do an exhaustive search as there could be many different ides/editors available.
