### ISSUE TITLE
Java on new Mac is broken and jbang keeps trying to use it

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#642]
/user/bin/java is broken on OS X. 

Jbang keeps picking it up but fails so doesn't even try install other option.

**Comment by quintesse** [comment]
Broken in what way?

There was a time in the beginning that the startup script would check that the installed Java actually worked, but that made the whole startup a lot slower.

**Comment by maxandersen** [comment]
Mac default Java is not a Java. 

Any commmand will print out a live like "Java not installed. Requesting install" which then shows a dialog box that sometimes lead you to oracle jdk other times to Adobe flash. 

It's just very broken and best if we just ignore that one OS X :)

**Comment by maxandersen** [comment]
Basically means I can't install jbang on my wife's laptop to do actual work :)

**Comment by quintesse** [comment]
But should we ignore _any_ system-installed JDKs on Macs? Doesn't that seem a bit radical? It would make Jbang act quite a bit differently on Mac than on other OSes.

Perhaps there's some other solution? Is there a way to use the `javac` command to check if it's the "real" one or the "fake" one?

**Comment by maxandersen** [comment]
I can see in my own MacBook the usr/Bin/Java is proper working. 

So can't ignore it completely. 

The only thing I can spot at the moment is that the size of the binary is different. 

So maybe use that is indicator ?

**Comment by quintesse** [comment]
I was thinking that there's perhaps a way to run it that determines the difference? A way to run the "fake" version that results in an error (and not in a pop-up for the user) that we can detect perhaps?

**Comment by maxandersen** [comment]
I haven’t found a way to run it without having the pop up.

**Comment by quintesse** [comment]
This might be interesting: https://stackoverflow.com/a/44158166/2889926

> `/usr/bin/java_home tool returns 1 if java not installed.`
>
> So you can check if java is installed by the next way:
>
> `/usr/libexec/java_home &> /dev/null && echo "installed" || echo  "not installed"`

**Comment by galderz** [comment]
```
```
❯ l /usr/bin | grep java
-rwxr-xr-x     1 root   wheel   136K 18 Oct 05:30 java
-rwxr-xr-x     1 root   wheel   136K 18 Oct 05:30 javac
-rwxr-xr-x     1 root   wheel   136K 18 Oct 05:30 javadoc
-rwxr-xr-x     1 root   wheel   136K 18 Oct 05:30 javah
-rwxr-xr-x     1 root   wheel   136K 18 Oct 05:30 javap
-rwxr-xr-x     1 root   wheel   136K 18 Oct 05:30 javapackager
-rwxr-xr-x     1 root   wheel   136K 18 Oct 05:30 javaws
```

**Comment by maxandersen** [comment]
Are they the exact same binary !? What does 'diff java javac' give ?

**Comment by galderz** [comment]
Yup, the same:

```
$ diff /usr/bin/java /usr/bin/javac

$```

**Comment by galderz** [comment]
```
$ /usr/bin/java --version
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

$ /usr/bin/javac --version
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

```

**Comment by quintesse** [comment]
Does executing that set an error code @galderz ? (`echo $?`)

**Comment by quintesse** [comment]
And did any of you test what I wrote 2 weeks ago? ☝️ 

I don't have a Mac so I can't test it.

```
/usr/libexec/java_home &> /dev/null && echo "installed" || echo "not installed"
```

**Comment by galderz** [comment]
Yeah it throws an error:

```
$ /usr/libexec/java_home &> /dev/null && echo "installed" || echo "not installed"
not installed
```

**Comment by quintesse** [comment]
Well that seems like the perfect test then. We should add that to the startup script.

**Comment by quintesse** [comment]
I created this PR: https://github.com/jbangdev/jbang/pull/1095

Can you guys test to see if it works correctly? @maxandersen @galderz

**Comment by maxandersen** [comment]
#1095 didn't seem to fix it though :/

```
ash-3.2$ curl -Ls https://sh.jbang.dev | bash -s - app setup
Downloading JBang...
Installing JBang...
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

bash-3.2$ echo $JAVA_HOME

bash-3.2$ ls -l `which java`
-rwxr-xr-x  1 root  wheel  138880 Jan  1  2020 /usr/bin/java
```

this is tested on https://github.com/maxandersen/ghplayground/actions/workflows/tmate.yaml

**Comment by quintesse** [comment]
There is indeed a `!` where there shouldn't be, but it still wouldn't work until a release has been created. The zero-install always runs the `jbang` script from the downloaded Jbang release.

**Comment by quintesse** [comment]
Created a one-character PR that fixes the condition. Tested it on that action of yours, so I think it should work this time.
Remember, it won't work unless a release has been made.

**Comment by maxandersen** [comment]
the curl fetches from main branch the initial script does it not ?

**Comment by quintesse** [comment]
Yes, but that script is only used until Jbang itself gets downloaded, then it defers to the downloaded script.
