### ISSUE TITLE
Add support for macOS arm64

### ISSUE THREAD

**Issue by syhily** [jbangdev/jbang#650]
![image](https://user-images.githubusercontent.com/1761698/103540805-47879300-4ed5-11eb-97b7-499ca6ddf3c8.png)

**Comment by quintesse** [comment]
@maxandersen you're going to need to get one of those newfangled M2 Macs now :-)

**Comment by maxandersen** [comment]
Btw. We should not print unsupported as only thing. User should still be able to run just fine if install own version of Java. 

It's just auto download that is having troubles here.

**Comment by quintesse** [comment]
> User should still be able to run just fine if install own version of Java.

But doesn't that conflict with https://github.com/jbangdev/jbang/issues/642 ?

**Comment by maxandersen** [comment]
No - if user installed a working Java using brew/oracle/sdkman then Arm64 would just work.

**Comment by quintesse** [comment]
I mean, doesn't the problem that you have with not being able to detect a valid system Java also affect this? It seems that having "a working Java using brew/oracle/sdkman" conflicts with "Any command will print out a line like "Java not installed. Requesting install" which then shows a dialog box that sometimes lead you to oracle jdk other times to Adobe flash." (from #642).

Isn't the problem that we don't have a foolproof way on MacOs to detect if you have a valid Java installed?

**Comment by maxandersen** [comment]
It is a problem yes. But in this case of report on m1 jbang already decided it needs to download.  So Java not present at all is my guess.

**Comment by quintesse** [comment]
True. Just goes to show we do still need to be able to use already installed JDKs on Mac. We "just" need a way to detect if we have a proper Java or not.

**Comment by maxandersen** [comment]
@syhily can you let me know if you have java installed or not in this case?

jbang should not fail if you have java installed that would be a major bug.

**Comment by syhily** [comment]
@maxandersen I install the JDK by directly installing the PKG install file which downloaded from zulu.
And I don't set the `JAVA_HOME` environment variable.

**Comment by maxandersen** [comment]
okey @syhily - thanks for confirming. so the fix in the linked issues should fix that. at least it will use what is in your JAVA_HOME / path - will be in next release.

**Comment by gavinking** [comment]
> @maxandersen you're going to need to get one of those newfangled M2 Macs now :-)

My daughters have them.

**Comment by quintesse** [comment]
> My daughters have them.

That means you're drafted to test Gavin :-)

**Comment by maxandersen** [comment]
this is now in master in a way so it should not fail anymore.

can't add support for automatic downloading of java yet as no such build available yet via adoptopenjdk afaics.

**Comment by quintesse** [comment]
>  as no such build available yet via adoptopenjdk afaics.

Re-checked right now and no, only x64

**Comment by gavinking** [comment]
> > My daughters have them.
> 
> 
> 
> That means you're drafted to test Gavin :-)

yeah, that's what I was afraid of
