### ISSUE TITLE
jbang edit download UX

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#655]
```
Do you want jbang to download VSCodium for you into /home/tschotan/.jbang/editor/vscodium ? 

0) Yes, please.

Any other response will result in exit.

[jbang] Type in your choice (0) and hit enter. Times out after 10 seconds.

[jbang] [ERROR] Could not parse answer as a number. Aborting
[jbang] [ERROR] No default editor configured and automatic download not accepted.
```

I just hit ENTER here, so I want to suggest 2 small improvements:

1. Accept ENTER, even if it's not a number, but that ERROR should not happen when you say "any other result will result in exit".
2. I think the message "No default editor configured and automatic download not accepted." should be infomrative and not an ERROR.

All those ERRORs make it seem as if something went wrong while it's expected behavior IMO.

**Comment by maxandersen** [comment]
just to be clear I understand your suggestion you no entry of a number or character + ENTER to result in installation happening ? 

Meaning there should be something like:

```
Do you want jbang to download VSCodium for you into /home/tschotan/.jbang/editor/vscodium ? 

0 or enter) Yes, please.
1) No thanks.

[jbang] Type in your choice (0) and hit enter. Times out after 10 seconds.
```

do I get that right? 

if yes, sure - that is closer to what I want (have it "just work" :)

**Comment by quintesse** [comment]
Well no, I just wanted ENTER to not give an error like it does now. :-)

**Comment by quintesse** [comment]
Much better now. Closing.
