### ISSUE TITLE
Introduce shortcut `./quarkusrest.java --native` instead of `jbang --native quarkusrest.java`

### ISSUE THREAD

**Issue by rsvoboda** [jbangdev/jbang#680]
Documentation say that `jbang --native quarkusrest.java` is the way.

I personally find `./quarkusrest.java --native` more convenient.

If possible, introduce shortcut `./quarkusrest.java --native` instead of `jbang --native quarkusrest.java`
There are of course some challenges like in the case of cli based applications which expect arguments.

**Comment by quintesse** [comment]
Indeed, many Jbang scripts accept options and currently there's no easy way that I can think of where we could allow Jbang options _after_ the script name that wouldn't cause conflicts with those scripts. But we're always open to ideas :-)

**Comment by rsvoboda** [comment]
The easiest way to have native build is probably to adjust the first line of the file to `//usr/bin/env jbang --native "$0" "$@" ; exit $?` and go just with `./quarkusrest.java`. If there are no changes to the file it is cached and no native-image compilation gets triggered.

Allowing JBang options after the script name - I was thinking about just few blessed options like `--native`.
From technical perspective this would be about reading the args when bootstrapping and filtering out and setting JBang options and passing further the adjusted set of args. Don't know the internals to say how complicated that would be to implement. Thorntail something like this to support `java -jar ...jar -Dswarm...`.

**Comment by quintesse** [comment]
> The easiest way

That's certainly an option.

> I was thinking about just few blessed options like --native

It's not about complexity but about that fact that we'd make it impossible for scripts to have a `--native` option themselves. I don't think that's something we want to do.

**Comment by maxandersen** [comment]
I understand that it feels "natural" to do it but it would require crossing some abstraction boundaries that just isn't worth breaking. 

When you call the script directly you are basically testing it as if jbang does not exist. 

And if we do it for native why not also for debug, or -D etc. 

And every thing we add a special case for becomes impossible for the scrips to have as their own flag/argument. 

Also, a jbang script/app could be a GaV with a jar which we have zero influence on and would have to start handling some of this in the script around it. 

And what does --native mean when you already have a native file ?

Thus I will have to reject this ask. 

In case you don't know you can do:

jbang app install --native your app.java


Then ./app will effectively to what you ask for.

**Comment by quintesse** [comment]
> Then ./app will effectively to what you ask for.

I think you mean "typing `your` will effectively do what you ask for.", right?

**Comment by maxandersen** [comment]
Ah should have been 'your app'

**Comment by quintesse** [comment]
Aha, so just to avoid confusion:

After running:

```
jbang app install --native your_app.java
```

You can simply run your app by typing:

```
your_app
```
