### ISSUE TITLE
is having a preexisting jdk a hard requirement to install jbang?

### ISSUE THREAD

**Issue by jmlucjav** [jbangdev/jbang#690]
hi,

Sorry if I am being obtuse, but from the instructions, it is not totally clear to me if installing a jdk is needed first, to be able to run jbang or not. I am on windows.

> To use jbang Java 8 is the minimum required version, however Java 11 or higher is recommended.

this (and the choco install jdk before installing jbang) makes it sound like you need a jdk first.

> The simplest way to install jbang is using Jbang itself. This method has no other requirements (besides curl on Linux/OSX).

but  this makes it sound like you don't need it?

My ideal scenario would be:

1. install jbang (with no existing jdks on the machine)
2. use jbang to install (and manage) some jdks

If an 'external' jdk is needed for jbang to be installed/run, then that jdk is not managed by jbang right? and it is a bit out of place regarding the jdks you install with jbang?

**Comment by maxandersen** [comment]
A jdk is not a hard requirement - so yes you can install using the first listed method via curl and jbang will fetch a jdk if there is not other system jdk available. Hope that explains it.

**Comment by jmlucjav** [comment]
excellent, thanks!
