### ISSUE TITLE
//Q:CONFIG  doesn't support custom properties

### ISSUE THREAD

**Issue by pjgg** [jbangdev/jbang#717]
## Description

When I load some known properties as `quarkus.http.port` works well, but when I add a new application property as `//Q:CONFIG app.selected.db=test` the application property is not loaded.

I have double check if the property is on the `ConfigProvider` but is not. 

Example

```
//Q:CONFIG app.selected.db=test

.
.
.

@ApplicationScoped
public class stockCryptoCurrency {

public static void main(String... args) {
        Quarkus.run(args);
    }

 @PostConstruct
    void initialize() {
        System.out.println("loading properties...");
        Config conf = ConfigProvider.getConfig();
        conf.getPropertyNames().forEach(c -> System.out.println(c));
        System.out.println("loading properties END");
}
```

Also If you use an annotation in order to retrieve your property, doesn't work

```
    @ConfigProperty(name = "app.selected.db")
   String simpleProperty;
```

Would be great  not only be able to load custom property, but also load it from a file. For example an `application.properties`

**Comment by maxandersen** [comment]
hmm - does sound like a bug - will need to check.

for `application.properties` you can add it next to the script and this:

`//FILES META-INF/application.properties=application.properties`

**Comment by pjgg** [comment]
:) Is also not an issue!. 

If you load the properties file as you told me:

`//FILES application.properties=application.properties`

Then the required property is retrieved. 

```
  @ConfigProperty(name = "app.selected.db")
   String simpleProperty;
```

Thank you @maxandersen
