### ISSUE TITLE
Running Java files in fish shell fails

### ISSUE THREAD

**Issue by timmattison** [jbangdev/jbang#732]
I am using fish shell - https://fishshell.com/ - and when I try to run the examples in the documentation I get an exec format error like this:

```
~/temp> ./hellocli.java
Failed to execute process './hellocli.java'. Reason:
exec: Exec format error
The file './hellocli.java' is marked as an executable but could not be run by the operating system.
```

If I switch to bash or zsh it works perfectly. Is there any fix to get it to work with fish shell?

**Comment by maxandersen** [comment]
Hmm. I'm not a fishshell expert but my first guess is that maybe fishshell enforces that the preamble have to be #! And don't allow the /// trick?

**Comment by quintesse** [comment]
That's indeed the case. And reading this case I doubt they'll ever support it, they consider it "a dangerous practice": https://github.com/fish-shell/fish-shell/issues/1281#issuecomment-265788224

**Comment by quintesse** [comment]
And this is even clearer: https://github.com/fish-shell/fish-shell/issues/2723

Doesn't look like they'd be open to implementing this feature.

**Comment by quintesse** [comment]
So I'm afraid that while using fish shell you'll have to use `jbang hellocli.java`.
Closing as "wontfix".

**Comment by maxandersen** [comment]
It actually turns out that Fish in 2021(!) added better (imo) heuristics so this is allowed and works. time to try fish :)

**Comment by maxandersen** [comment]
just reopen/close to mark as working :)
