### ISSUE TITLE
Instructions for using jbang to install jbang don't work on Windows

### ISSUE THREAD

**Issue by scottkurz** [jbangdev/jbang#746]
From Git Bash on Windows, following these instructions:  https://github.com/jbangdev/jbang#using-jbang 

> curl -Ls https://sh.jbang.dev | bash -s - app setup

it fails with:
> bash: line 70: <....home...>/jbang.cmd: No such file or directory

which seems to make sense... I haven't installed jbang yet.      

There's a bunch of other ways to install that work, but since this was called out as the simplest, probably worth fixing.

**Comment by quintesse** [comment]
Confirmed, the fix should be easy enough. Just need to figure out what the best fix will be.

**Comment by quintesse** [comment]
This should be fixed now, can you confirm @scottkurz ?

**Comment by scottkurz** [comment]
> This should be fixed now, can you confirm @scottkurz ?

@quintesse  works for me now..thanks !

**Comment by quintesse** [comment]
Perfect, thanks for your feedback!
