### ISSUE TITLE
jbang cache clear does not clear temporary projects

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#762]
$ jbang cache --help
Unknown option: '--help'
Usage: jbang cache -o [--fresh] --quiet --verbose [COMMAND]
Manage compiled scripts in the local cache.
      --fresh     Make sure we use fresh (i.e. non-cached) resources.
  -o, --offline   Work offline. Fail-fast if dependencies are missing. No
                    connections will be attempted
      --quiet     jbang will be quiet, only print when error occurs.
      --verbose   jbang will be verbose on what it does.
Commands:
  clear  Clear cache of dependency list and **temporary projects**. By default this
           will clear the JAR, script, stdin and URL caches

$ jbang cache clear 
[jbang] Clearing cache for urls
[jbang] Clearing cache for jars
[jbang] Clearing cache for scripts
[jbang] Clearing cache for stdins
[jbang] Clearing cache for deps

$ ls -l .jbang/cache/projects/
total 8
drwxrwxr-x 3 pyfourmond pyfourmond 4096 mars   3 18:27 GitClone.java_jbang_331346861e0e6fa9d9d17c875bab7469086b26fd4cf07adb665eaf8e87fbdeb2
drwxrwxr-x 3 pyfourmond pyfourmond 4096 mars   3 18:24 GitGet.java_jbang_6d0d971728f4420e24d7917a651927113594a83a20453f1b7e9bba1e41ffe892

**Comment by quintesse** [comment]
Yes, that's by design. If you want to clear the projects you can use `jbang cache clear --project` or `jbang cache clear --all`. HTH.

**Comment by quintesse** [comment]
Btw the reason for `cache clear` not clearing all caches is that some are considered somewhat "dangerous". Clearing the projects cache while a project is still open in an IDE or editor might cause all kinds of problems. The same is true for the JDKs downloaded by Jbang. So we make it slightly more difficult to clear those caches so people won't clear them by accident.

**Comment by maxandersen** [comment]
ive made an update that makes the help text a bit more explicit:
"Clear the various caches used by jbang. By default this will clear the JAR,
script, stdin and URL caches. To clear other caches list them explicitly i.e.
'--project' for temporary projects."

**Comment by quintesse** [comment]
Good idea
