### ISSUE TITLE
Brew install seems broken

### ISSUE THREAD

**Issue by tqvarnst** [jbangdev/jbang#772]
When trying to install brew (upgrade didn't work when I installed Mac OS Big Sur so I removed it and tried to install it again) I get the following issue:

```sh
$ brew install jbang
==> Installing jbang from jbangdev/tap
==> Downloading https://github.com/jbangdev/jbang/releases/download/v0.67.1/jban
==> Downloading from https://github-releases.githubusercontent.com/230011262/8b6
######################################################################## 100.0%
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
/usr/local/Cellar/jbang/0.67.1/libexec/bin/jbang:
  expected replacement of /^abs_jbang_path=.*/ with "abs_jbang_path=/usr/local/Cellar/jbang/0.67.1/libexec/bin/jbang.jar"
```

**Comment by maxandersen** [comment]
okey, so now there are two reporting this https://github.com/jbangdev/homebrew-tap/issues/5

things haven't changed on jbang side in months here so i'm wondering if recent brew updates broken it....will take a look.

until then you can use:

```
curl -Ls https://sh.jbang.dev | bash -s - app install jbang
```

**Comment by maxandersen** [comment]
found the culprit - https://github.com/jbangdev/jbang/pull/747 removed abs_jbang_path making brew tap fail.

@quintesse why was that change needed :)

**Comment by quintesse** [comment]
Not needed, but each time I read that name I had to check if it was the path to jbang itself or its folder, so I decided to change its name. Very unexpected external dependencies like this should be documented with large letters in the code IMO :-)
