### ISSUE TITLE
jbang docker install fail ....not sure why

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#773]
```
docker run -it -p 8080:80 ellerbrock/alpine-bash-curl-ssl bash
curl -Ls https://sh.jbang.dev | bash -s - app install --name qs cli@quarkusio
Downloading JBang...
Installing JBang...
Downloading JDK 11. Be patient, this can take several minutes...
Installing JDK 11...
/home/download/.jbang/bin/jbang: line 168: /home/download/.jbang/cache/jdks/11/bin/java: No such file or directory
/home/download/.jbang/bin/jbang: line 177: /home/download/.jbang/cache/jdks/11/bin/java: No such file or directory
```

the files are there but some reason cant run them...

**Comment by quintesse** [comment]
I think it's because alpine either has missing or wrong .so dependencies.
If I run something like: `find /home/download/.jbang/cache/jdks/11/lib -name '*.so' -exec ldd {} \;` I see loads and loads of errors.

**Comment by quintesse** [comment]
For example see [this official Dockerfile](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/8/jdk/alpine/Dockerfile.hotspot.releases.slim) for AdoptOpenJDK on Alpine and the amount of work they have to do to make it work.

**Comment by maxandersen** [comment]
Damn

**Comment by quintesse** [comment]
There are some alpine images that have glibc that seem to work (not all of them, I tried one that gave a SEGFAULT):

```
$ docker run -it --rm nimmis/alpine-glibc sh
# apk add curl bash
# curl -Ls https://sh.jbang.dev | bash -s - app setup
# bash
# jbang version
```

**Comment by maxandersen** [comment]
okey - so im closing this one as a know issue - not jbangs job to fix all missing deps at the core os level :)
