### ISSUE TITLE
Terminal input not working on ZSH 

### ISSUE THREAD

**Issue by brunoborges** [jbangdev/jbang#779]
In `zsh`, when I get asked for confirming whether I trust a site or not, the process does not register the input.

```
[jbang] Type in your choice (0 or 1) and hit enter. Times out after 10 seconds.
...
[jbang] [ERROR] Could not parse answer as a number. Aborting
```

**Comment by quintesse** [comment]
Hmm that's weird, I'm using `zsh` too without any problems

**Comment by brunoborges** [comment]
Oh... I know why... Duh... I am running with Docker, but not enabling -ti... 

Urgh!
