### ISSUE TITLE
ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature

### ISSUE THREAD

**Issue by lburgazzoli** [jbangdev/jbang#783]
I have a jbang script to set up a simple web service using quarkus-resteasy:

```java
//usr/bin/env jbang "$0" "$@" ; exit $?
//
//DEPS io.quarkus:quarkus-resteasy-jackson:1.12.1.Final
//
//JAVAC_OPTIONS -parameters
//JAVA_OPTIONS -Djava.util.logging.manager=org.jboss.logmanager.LogManager
//
//Q:CONFIG quarkus.banner.enabled=false
//Q:CONFIG quarkus.http.port=9090
//Q:CONFIG quarkus.log.console.format=%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n
//

import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@ApplicationScoped
@Path("/api")
public class example {
    @GET
    @Path("/hello")
    @Produces(MediaType.APPLICATION_JSON)
    public JsonNode get() {
        return new ObjectMapper().createObjectNode().put("messahe", "hello");
    }

    public static void main(String[] args) {
        io.quarkus.runtime.Quarkus.run(args);
    }
}
```

running this script leads to

```
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 53 more
```

A workaround is to explicit add a dependnecy on `com.fasterxml.jackson.core:jackson-core:2.12.1`  

I don't know if this is an issue related to jbang or quarkus, is there a way to get the full dependency tree resolved by jbang ?

**Comment by quintesse** [comment]
You can get a _list_ of resolved dependencies by running `jbang info classpath <yourscript>` or `jbang info tools <yourscript>`

**Comment by quintesse** [comment]
Btw I have almost no experience with Quarkus so @maxandersen can probably answer this much better than me, but looking at some of our Quarkus examples I see [this line here](https://github.com/jbangdev/jbang-examples/blob/c77164eccd9e44b81b0ca7373b7597f058c949e8/examples/resteasyclient.java#L5) which seems to suggest you have to explicitly add a provider.

**Comment by lburgazzoli** [comment]
mh, looks like it is a bad dependency tree on quarkus as jackson-core is effectively on the classpath even if not explicit added to the dependencies but the version is `2.11.1`: 

    /home/lburgazz/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.1/jackson-core-2.11.1.jar

When I add `//DEPS com.fasterxml.jackson.core:jackson-core:2.11.1`, then it resolve to the right version:

    /home/lburgazz/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.jar

**Comment by lburgazzoli** [comment]
will report to quarkus

**Comment by maxandersen** [comment]
afaics this is expected as deps in quarkus -jackson is open ended - the bom is required to get it working properly.

closing until proven otherwise :)
