### ISSUE TITLE
Jbang can't run editor with space in it path or name under Windows 10

### ISSUE THREAD

**Issue by piradix** [jbangdev/jbang#798]
Jbang can't run editor with space in it path or name under Windows 10, like "C:\appli\dev\Microsoft VS Code\Code.exe" !
because it call  :
`cmd /c C:\appli\dev\Microsoft VS Code\Code.exe  .....`

insert double quote before and after name, resolve this issue :
`cmd /c "C:\appli\dev\Microsoft VS Code\Code.exe"  .....`

or in java /c++ use a parameters call like :
`new ProcessBuilder("cmd","\\c", editorPathFile, .... ).start();`

**Comment by maxandersen** [comment]
@quintesse your magic `Run::escapeArgument` should handle that, right?

**Comment by maxandersen** [comment]
@piradix if you can try out the jbang.jar https://github.com/jbangdev/jbang/pull/800/checks will provide as an artifact and test it works for you that would be great!

**Comment by maxandersen** [comment]
@all-contributors please add @piradix  for issue

**Comment by maxandersen** [comment]
@all-contributors please add @piradix  for bug

**Comment by piradix** [comment]
I 'll try it tomorow 


Piradix




From:   "Max Rydahl Andersen" ***@***.***>
To:     "jbangdev/jbang" ***@***.***>
Cc:     "piradix" ***@***.***>, "Mention" 
***@***.***>
Date:   22/03/2021 22:16
Subject:        Re: [jbangdev/jbang] Jbang can't run editor with space in 
it path or name under Windows 10 (#798)



@piradix if you can try out the jbang.jar 
https://github.com/jbangdev/jbang/pull/800/checks will provide as an 
artifact and test it works for you that would be great!

**Comment by piradix** [comment]
It is OK.
I'd try this 2 lines:

 `jbang edit --open="c:\Program Files\Microsoft VS Code\Code.exe" Hello`
 `jbang edit "--open=c:\Program Files\Microsoft VS Code\Code.exe" Hello`

all are perfect 

thanks, 🥇

**Comment by maxandersen** [comment]
Thanks for confirming. Keeping open until merge happens (sometime later today)
