### ISSUE TITLE
--deps do not allow multiple dependencies

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#815]
jbang --deps only handles one dep at the time, it should allow same style as //DEPS so you can do:

`curl -Ls https://sh.jbang.dev | bash -s -  --deps org.hsqldb:hsqldb:2.5.0,net.hydromatic:foodmart-data-hsqldb:0.4 sqlline`

instead of requiring two --deps

**Comment by grumpyf0x48** [comment]
It works with one `--deps` and no comma:

`curl -Ls https://sh.jbang.dev | bash -s - --verbose --deps org.hsqldb:hsqldb:2.5.0 net.hydromatic:foodmart-data-hsqldb:0.4 sqlline.java`

It is declared like this in the code:

```
@CommandLine.Option(names = { "--deps" }, description = "Add additional dependencies.")
List<String> dependencies;
```

Am i missing something ?

**Comment by grumpyf0x48** [comment]
OK got it.

Dependencies are parsed but main class is not (probably included in the dependencies list and ignored as a dependency):

```
[jbang] jbang version 0.81.0
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] [ERROR] no main class deduced, specified nor found in a manifest
dev.jbang.cli.ExitException: no main class deduced, specified nor found in a manifest
```

**Comment by maxandersen** [comment]
We basically just need it to have a delimiter defined then it should work without having to write --deps every time.

**Comment by grumpyf0x48** [comment]
Can be closed
