### ISSUE TITLE
Always wants to download the JDK on Windows

### ISSUE THREAD

**Issue by sigzero** [jbangdev/jbang#820]
I have a few JDKs on my system for work. I downloaded openjdk11 from `https://adoptopenjdk.net/` and extracted it into C:\jdk11.

I created a setenv.bat file and put it into the same bin directory as jbang (`C:\jbang\bin`). On the first run I get the following:

```
Downloading JDK 11. Be patient, this can take several minutes...
```

If I immediately try again I get:

```
JAVA_HOME is set but does not seem to point to a valid Java JDK
Downloading JDK 11. Be patient, this can take several minutes...
```

So it doesn't seem to like my setenv.bat which only contains the following:

```
set "JAVA_HOME=C:\jdk11"
exit /b 0
```

The JDK is valid. I run a `-version` and I get the following:

```
PS C:\jdk11\bin> .\java.exe -version                                                                                    openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
PS C:\jdk11\bin>  
```

**Comment by quintesse** [comment]
Just a couple of questions:

 1. what's the version of Jbang you're using, and
 2. you can also run `javac` from `c:\jdk11\bin`, right?

**Comment by sigzero** [comment]
I downloaded `jbang-0.69.2.zip` and yes I can run `javac` and it compiles and I can run `c:\jdk11\bin\java.exe` on the created file and it works. I have tried both CMD and PS since there is a script for both in the bin directory.

Looking at the jbang.cmd file I see nowhere were it calls setenv.bat.

**Comment by quintesse** [comment]
Hmm just to be sure but can you paste the output of `%JAVA_HOME%\bin\javac -version`?

**Comment by sigzero** [comment]
I have no JAVA_HOME set.

```
The system cannot find the path specified.
```
Which is what I would expect.

**Comment by quintesse** [comment]
Thing is that according to the jbang script JAVA_HOME _is_ set, that's why.
Can you check that typing `echo %JAVA_HOME%` returns "%JAVA_HOME%"?

**Comment by sigzero** [comment]
That's exactly what it returns. It isn't set.

**Comment by quintesse** [comment]
Very weird. Can we try something else? Because I'm unable to reproduce this locally.
Could you edit the `jbang.cmd` script and edit the first line, changing the word "off" to "on" and then re-run the command you're trying to run and post the output?

**Comment by sigzero** [comment]
Attached.

[jbang-0.69.2.txt](https://github.com/jbangdev/jbang/files/6230150/jbang-0.69.2.txt)

 After I ran that, I set the JAVA_HOME manually from the command line using `set JAVA_HOME=c:\jdk11`. The `echo %JAVA_HOME%` works and I ran `jbang -?`  again and it works. So very odd.

**Comment by sigzero** [comment]
Just a thought...if I set JAVA_HOME in the cmd script it works. But if the cmd script is supposed to check for a setenv.bat file it does not. It's nowhere in the script. There should be an if statement that runs a call command to get anything defined in setenv.bat.

Something like:

```
if exist "%JBDIR%\bin\setenv.bat" call "%JBDIR%\bin\setenv.bat"
```
Or something. I am basing that off a Tomcat script that does use setenv.bat. If jbang doesn't use a setenv then ignore this.

**Comment by sigzero** [comment]
Ah I see. You RUN the setenv.bat, you don't call it from the cmd script. Okay. I missed that. When I do it that way it runs.

**Comment by quintesse** [comment]
Well in general I wasn't sure why you wrote a setenv.bat :-)
Are you following some kind of instructions?

**Comment by sigzero** [comment]
From the main Github page:

Instead of copying and pasting lines you could also redirect the output to a .bat file and execute that instead:

> jbang jdk java-env > setenv.bat
> setenv

I use a setenv.bat for my Tomcat stuff (and I like this way) and it confused me is all.

**Comment by quintesse** [comment]
Aha, I had forgotten we had that in there. But yeah, that only works if you also run `jbang jdk java-env > setenv.bat` first.

**Comment by quintesse** [comment]
So things are okay now? This issue can be closed?

**Comment by sigzero** [comment]
Yeah. I have the following in the cmd script to run my setenv.bat so I am good. Thanks for the help.

```
rem Get the directory jbang.cmd is in to check for the setenv.bat
set JCMD_DIR="%~dp0"
if exist "%JCMD_DIR%\setenv.bat" call "%JCMD_DIR%\setenv.bat"
```
