### ISSUE TITLE
Jbang update fails on Windows

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#823]
When you do `jbang version --update` or `jbang app install --force jbang` you'll get an:

```
[jbang] Downloading and installing jbang...
[jbang] [ERROR] Could not copy jbang.jar
[jbang] Run with --verbose for more details
```

Which is because you can't overwrite the `jbang.jar` while it's in use. (I thought I tested that and that it was possible to do so, but obviously I tested wrong somehow).

**Comment by maxandersen** [comment]
do you have a fix/workarond ? kinda nasty bug :/

**Comment by quintesse** [comment]
I have an idea for a fix :-)

**Comment by quintesse** [comment]
Still doesn't work correctly. Re-opened. (PR provided)

**Comment by maxandersen** [comment]
4th time is the charm ? :) :)

**Comment by quintesse** [comment]
I sure hope so! 🙈
