### ISSUE TITLE
Works with ubuntu but NOT working for Alpine when building docker image

### ISSUE THREAD

**Issue by flashflexpro** [jbangdev/jbang#826]
>
    FROM alpine
    RUN set -eux && \
        apk add --clean-protected --no-cache \
                curl \
                bash && \
        curl -Ls https://sh.jbang.dev | bash -s - app setup
  
When build:

> 

      11.37 Installing JDK 11...
      14.36 /root/.jbang/bin/jbang: line 168: /root/.jbang/cache/jdks/11/bin/java: No such file or directory
      14.36 /root/.jbang/bin/jbang: line 177: /root/.jbang/cache/jdks/11/bin/java: No such file or directory
      ------
      executor failed running [/bin/sh -c set -eux &&     apk add --clean-protected --no-cache             curl             bash &&     curl -Ls https://sh.jbang.dev | bash -s - app setup]: exit code: 127

**Comment by maxandersen** [comment]
Yes, it's an unfortunate known issue that base alpine does not have a working base set of libraries to run Java. 

See https://github.com/jbangdev/jbang/issues/773 for details/examples. 

If anyone has some idea on how we can detect/handle this case better I'm all ears.

**Comment by quintesse** [comment]
I think Oracle is planning Alpine support from Java 16 onwards: https://openjdk.java.net/jeps/386

**Comment by quintesse** [comment]
Or you can use (non official) Alpine + glibc base images like https://hub.docker.com/r/frolvlad/alpine-glibc/ but then you're losing the main size advantage (the image goes from 5MB to 12MB).

**Comment by maxandersen** [comment]
12 MB is still light :)

**Comment by maxandersen** [comment]
closing as duplicate and we dont have a good answer to handle  it better as its the container not being able to run java :/

**Comment by quintesse** [comment]
Alpine support is now implemented, so once this PR gets merged you should be good to go @flashflexpro ! See #839
