### ISSUE TITLE
`jbang info tools` should expose more info

### ISSUE THREAD

**Issue by fbricon** [jbangdev/jbang#833]
Would be nice if `jbang info tools`  could return
- The Java version
- potential path to JDK to use
- Java options to apply
- associated sources (//SOURCES)
- associated files (//FILES)

Ideally, the position where an error is detected (eg. bad dependency).

See https://github.com/fbricon/jbang.eclipse/blob/master/jbang.eclipse.core/src/main/java/io/jbang/eclipse/core/internal/process/JBangExecution.java#L90 for context

**Comment by fbricon** [comment]
Demo:
https://user-images.githubusercontent.com/148698/114422920-fca5a780-9bb6-11eb-9f45-8f821d8586c7.mp4

**Comment by quintesse** [comment]
The items in the list are easy enough to do. The error probably not. The `info` command doesn't require actual compilation, it's all just information extracted from the source code. The only thing I could imagine is perhaps being able to detect unresolvable dependencies.

**Comment by quintesse** [comment]
@fbricon see this PR: https://github.com/jbangdev/jbang/pull/859

Is that what you're looking for?
