### ISSUE TITLE
jbang doesn't detect changes to included //FILES or //SOURCES

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#842]
We should probably include those files in the hash we calculate for scripts

**Comment by maxandersen** [comment]
yes - or at least their size+utctimestamp to avoid having to do shasum for all files...but not sure at what point doing checksum of content > getting size/timestamp...for small set of files checksum might be just as fast..

**Comment by quintesse** [comment]
Fixed by #1272
