### ISSUE TITLE
Plugin execution not covered by lifecycle configuration: `dev.jbang:jbang-maven-plugin:0.0.6:run` (execution: `generate-build-item-doc`, phase: `process-resources`)

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang#847]
When using the `jbang-maven-plugin` in a project inside Eclipse, I get the following error:

```
Plugin execution not covered by lifecycle configuration: dev.jbang:jbang-maven-plugin:0.0.6:run (execution: generate-build-item-doc, phase: process-resources)
```

I can choose to ignore it, but it would be nice to have the m2e connector provided in the Eclipse Marketplace.

**Comment by maxandersen** [comment]
Not following? Shouldn't it not be enough to add .m2 metadata to the plug-in. ?

**Comment by gastaldi** [comment]
What .m2 metadata are you referring to? The one that makes eclipse ignore the warning?

**Comment by maxandersen** [comment]
yes - a maven plugin can add `META-INF/m2e/lifecycle-mapping-metadata.xml` to have default configuration for the plugin.

docs here: https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html

**Comment by gastaldi** [comment]
Oh, didn't know of that. I'll provide a PR ASAP
