### ISSUE TITLE
Make `catalog` commands more like `alias`

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#854]
The two commands have "grown apart" somewhat:

- [x] Right now the `catalog add` command still requires 2 arguments, a name and a url or path, but `alias add` was changed to use an optional `--name` flag. We should do the same for `catalog add`.
- [x] `catalog list` doesn't have a `--show-origin` flag like `alias list` has. It would perhaps be nice if it did.
- [x] `catalog list` also doesn't have colored output
- [x] docs

**Comment by maxandersen** [comment]
+ for alignment
