### ISSUE TITLE
Jbang "app install" creates .bat and .ps1 instead of .sh file

### ISSUE THREAD

**Issue by knutwannheden** [jbangdev/jbang#864]
I am running on Windows 10 using Windows Terminal Preview (version 1.8.1032.0) and Git bash (i.e. Windows Terminal executes `"<GIT_HOME>\usr\bin\bash.exe" --login -i`). I have Jbang 0.70.0 installed and when I delete all files in `~/.jbang/bin` and then run `jbang app install gavsearch@jbangdev` it creates `gavsearch.cmd` and `gavsearch.ps1` but no `jbang.sh`:

```shell
knutw@WIN10-KNUT MSYS /c/dev/git
$ rm ~/.jbang/bin/*

knutw@WIN10-KNUT MSYS /c/dev/git
$ jbang app install gavsearch@jbangdev
[jbang] Command installed: gavsearch

knutw@WIN10-KNUT MSYS /c/dev/git
$ ls -l ~/.jbang/bin/
total 2
-rw-r--r-- 1 knutw 197609 44 May 10 08:47 gavsearch.cmd
-rw-r--r-- 1 knutw 197609 36 May 10 08:47 gavsearch.ps1
```

It looks like Jbang doesn't properly detect my Git Bash environment and decides to execute the Windows launcher scripts instead of a shell script.

**Comment by quintesse** [comment]
Thanks for the issue @knutwannheden !

It's not that Jbang doesn't detect the environment but that we thought it would be enough to just install the Windows files. Your issue made us realize we were wrong, so we need to install the Shell script as well. :-)

**Comment by maxandersen** [comment]
would be `gavsearch` not `gavsearch.sh` I reckon?

@knutwannheden you should be able to use `gavsearch.cmd` as a temporar workaround.

but yeah, feels like for windows we should be better of generating all three of them ....a bit crazy but that would make it work "everywhere"

**Comment by knutwannheden** [comment]
> would be `gavsearch` not `gavsearch.sh` I reckon?

Of course, yes.

> @knutwannheden you should be able to use `gavsearch.cmd` as a temporar workaround.

Yes, that indeed works.

**Comment by yamashita-ki** [comment]
Is this issue still open?

**Comment by maxandersen** [comment]
I think it's fixed but I don't have a windows vm to test on atm. If you can try out with latest jbang version and give update here that would be great!

**Comment by yamashita-ki** [comment]
gavsearch is installed, so it seems like already fixed.

```

[kiyo@DESKTOP-950MM36 MINGW64 ~/.jbang/bin
$ ls
jbang  jbang.cmd  jbang.jar  jbang.ps1

kiyo@DESKTOP-950MM36 MINGW64 ~/.jbang/bin
$ jbang app install gavsearch@jbangdev
[jbang] Command installed: gavsearch

kiyo@DESKTOP-950MM36 MINGW64 ~/.jbang/bin
$ ls
gavsearch  gavsearch.cmd  gavsearch.ps1  jbang  jbang.cmd  jbang.jar  jbang.ps1

kiyo@DESKTOP-950MM36 MINGW64 ~/.jbang/bin
$ jbang --version
0.110.1
```

**Comment by maxandersen** [comment]
Thanks for verifying.
