### ISSUE TITLE
Support multiple boms at the starting DEPS

### ISSUE THREAD

**Issue by tadayosi** [jbangdev/jbang#877]
Sometimes we might want to use multiple boms in a single script...

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.vertx:vertx-stack-depchain:4.0.3@pom
//DEPS org.apache.camel:camel-bom:3.9.0@pom
//DEPS io.vertx:vertx-core
//DEPS org.apache.camel:camel-core
//DEPS org.apache.camel:camel-stream
//DEPS org.apache.camel:camel-vertx
//DEPS org.slf4j:slf4j-simple:1.7.30
...
```

```console
$ jbang camel-vertx.java 
[jbang] Resolving dependencies...
[jbang] Loading MavenCoordinate [io.vertx:vertx-stack-depchain:pom:4.0.3]
[jbang] [ERROR] POM imports as found in org.apache.camel:camel-bom:3.9.0@pom is only supported as the first import.
[jbang] Run with --verbose for more details
```

**Comment by maxandersen** [comment]
Yeah. It's a bit annoying to do because of limits in shrinkwrap but definitely should. 

We would either need to generate a bom Pom that includes the dependencies to have resolution work with shrinkwrap or drop shrinkwrap and use aether directly.

**Comment by maxandersen** [comment]
@tadayosi  if you have a chance and can try out the jbang attached to #1173 and tell if it works as you expect multiple boms should work that would be great.

**Comment by tadayosi** [comment]
@maxandersen I confirmed it with my example. Great enhancement. Thank you!
