### ISSUE TITLE
SNAPSHOT //DEPS

### ISSUE THREAD

**Issue by chhex** [jbangdev/jbang#902]
JBang is really a great addition in the Java landscape.... it addresses a great void there. 

This may not be an issues , but just me missing information: 

//DEPS resolves Maven Dependencies, but it's not to honor the SNAPSHOT logic of Maven? 
Scenario: i  have a snapshot dependencies , which has been updated , but JBang seems to stick with the already resolved version.

**Comment by quintesse** [comment]
Could you give some more details as to the exact problem you are experiencing? Preferably some exact steps to reproduce.

(Jbang definitely supports -SNAPSHOT artifacts and normally detects when they have been updated and that a new build should be done, but perhaps there's still some corner case we didn't take into account)

**Comment by maxandersen** [comment]
As @quintesse outlines snapshot should work. Would be good to know what you see not working ? Maybe it's about remote snapshots then you might wanna use 'jbang --fresh xyz.java'?

**Comment by chhex** [comment]
@quintesse  Ahhh  ok. Probably then on my side. 

Maybe what is "special" in my scenario is that i am working against the local File System respectively Local Maven Repository:
```

///usr/bin/env jbang "$0" "$@" ; exit $?
//REPOS local=file:///Users/chhex/maven/testrepo
//DEPS com.apgsga.testing.sample:api-testing-sample-client:0.5.1-SNAPSHOT
//DEPS org.junit.jupiter:junit-jupiter-api:5.5.2
//FILES logback.xml ./logback.xml

```

I am using the local=file parameter, because i have my Maven Repo in a non standard location and i think that is not yet supported by Jbang , respectively in the pipeline?

I will also try with the "--fresh" option. 

Great thanks

**Comment by chhex** [comment]
The "--fresh" option doesn't help. It's seems to be my specific scenario.

**Comment by chhex** [comment]
I can confirm: working against a proper remote maven remote repository, this works fine. 
But with "only" a REPO which points to a local maven directory, it seems not to refresh

**Comment by chhex** [comment]
I have done some more testing.  I think this is related to the problem of the none standard mavenLocal repository location.

**Comment by maxandersen** [comment]
Try set JBANG_REPO environment variable to your repo location and remove the repo line in the file and say if it makes a diff. 

It should pick up new snapshots locally at least.

**Comment by chhex** [comment]
@maxandersen that works perfect , also in combination with a proper maven repo repository! Great thanks. 

So it's basically just the in another issues mentioned problem of picking up the 
` <localRepository>someRepoPath <localRepository/>`
non standard repo location from settings.xml 

But this works for so i can close this issue?

**Comment by maxandersen** [comment]
Sounds good - thanks!
