### ISSUE TITLE
Support literate programming via Mark down and asciidoc

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#904]
Inspired by https://github.com/google/zx/blob/2.1.0/examples/markdown.md

Have super trivial extraction of code blocks in md and adoc files and run as jshell input.

Edit: The linked document was removed from later versions. I've updated the link to point to a much older version of the repo. -quintesse

**Comment by quintesse** [comment]
Would each block be seen as a separate script to be run?

**Comment by maxandersen** [comment]
All merged was my thinking.
