### ISSUE TITLE
jbang app setup not handling bashrc properly on osx

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#930]
see #928, summary is that osx with default terminal app wont run .bashrc but runs bash_profile so wont ever see the path jbang configures.

**Comment by quintesse** [comment]
I'm still not sure how exactly we can fix this. Does the terminal you use on MacOS also parse bash_profile? Because how else do we know what file to change?

Btw, on my Fedora system bash_profile sources the bashrc file. Even so, my bash_profile doesn't seem to get parsed at any time, so bashrc does seem to be the correct option on Linux (using either bash or zsh).

**Comment by edeandrea** [comment]
`.bash_profile` and not `.bashrc` is sourced by the macOS Terminap.app. `.bash_profile` does not source `.bashrc` unless someone specifically goes into `.bash_profile` and adds it (like I did to solve the problem).

I'm not sure if this is something weird just on my machine or if it's a macOS standard.

I have 2 other macbooks (both running macOS 11.4) that I can test this on if you'd like. One is an older (2015) 15" macbook pro and the other a 2020 MacBook air M1.

**Comment by quintesse** [comment]
It would be interesting to know what is considered "the standard" on MacOS. Because if iterm2 also parses bash_profile (besides bashrc) then we can just add the lines to the bash_profile on MacOS and call it a day. But if iterm2 parses bashrc and the default Mac terminal app parses bash_profile then we have somewhat of a problem, because how do we know which file to change?

**Comment by edeandrea** [comment]
Another thing I will test today - the built-in terminals in IntelliJ and VSCode. I _think_ the source `.bash_profile'.

I found this: https://scriptingosx.com/2017/04/about-bash_profile-and-bashrc-on-macos/

**Comment by quintesse** [comment]
Aha, so supposedly the best solution is what I see (by default) on my Fedora system: put the lines in bashrc and make sure that file gets sourced by bash_profile. The question is how can we make sure to do that without messing up people's existing setups? :-)

**Comment by edeandrea** [comment]
I also noticed that when I installed SDKman it put stuff in `.bash_profile` and not `.bashrc`

Maybe you check for the current OS. If macOS, then check for the presence of `.bash_profile`. If found, add it there. Otherwise put it in `.bashrc`?

**Comment by quintesse** [comment]
A possible solution would be to do something like:

1. if on MacOS check if ~/bash_profile exists
2. if so, check if it contains any line containing "/.bashrc"
3. If not, add `[ -r ~/.bashrc ] && . ~/.bashrc` to the and of that file

**Comment by edeandrea** [comment]
And then what about z shell (the default on macOS since 10.15)? I think there is are similar profile & rc files.

**Comment by quintesse** [comment]
> And then what about z shell 

We do the same for Zsh: we add the lines to .zshrc

**Comment by edeandrea** [comment]
> We do the same for Zsh: we add the lines to .zshrc

Right but I think you have the same problem where it isn't picked up because `.zshrc` isn't sourced.

**Comment by edeandrea** [comment]
> I have 2 other macbooks (both running macOS 11.4) that I can test this on if you'd like. One is an older (2015) 15" macbook pro and the other a 2020 MacBook air M1.

I tested with both of these macbooks. Neither one of them even had a `.bashrc` file - only a `.bash_profile`.

**Comment by quintesse** [comment]
> but I think you have the same problem

According from what I read the Zsh should always read the zshrc, even on MacOS.

Another way we could fix this is to make sure that the setup code can be run multiple times without problems, like this:

```
[[ ":$PATH:" != *":/path/to/add:"* ]] && PATH="/path/to/add:${PATH}"
```

The problem I see with this is that I don't see anybody else doing that. Other apps that added lines to my bashrc or zshrc jsut do a plain `PATH=$PATH:/path/to/add`.

SDKMAN does add their init code to all files it can find. But they run a very complex setup script.

So I'm still not sure what the best solution is.

Can any Mac user test if iterm2 parses bash_profile? That would at least simplify the problem somewhat.

**Comment by edeandrea** [comment]
iterm2 does parse `.bash_profile`. I just installed it and when bringing up a terminal all my aliases that I have defined in `.bash_profile` are available.

I didn't test VSCode, but the built-in terminal/console within IntelliJ also parses `.bash_profile` and not `.bashrc`.

**Comment by edeandrea** [comment]
so maybe the logic should be

```java
if ((os == "macOS") && .bash_profile.exists()) {
  add to .bash_profile
}
else {
  add to .bashrc
}
```

?

**Comment by quintesse** [comment]
That does seem like the simplest solution, yes.

**Comment by ebullient** [comment]
I think my favorite is `rvm`, which allows me to install it without updating ANY of my shell files for me, so I can put it where I want.
(I use zsh, but have moved all of my stuff around to my liking, which means jbang and sdkman et al are all putting things in files that aren't used)

**Comment by maxandersen** [comment]
Well it put it somewhere...if it does not change the path setup it would need root access which doesn't sound better?

**Comment by ebullient** [comment]
I'm just saying.. if you're going to change where it writes, an option to have it not write at all would be excellent.

**Comment by maxandersen** [comment]
Sure - but it needs to write the bootstrap and script *somewhere* :)

Sure we can have it just run the quarkus script but it will be darn slow every time.

**Comment by ebullient** [comment]
Just to be clear: if I use that option, I have to make the update. That simple. But that means I put it where I want it, rather than you trying to guess.

**Comment by maxandersen** [comment]
@ebullient im sorry but I just don't understand what you are suggesting. If jbang setup does not add `~/.jbang/bin` to the path how are you suggesting any of its script (and it self when not installed with a package manager) will work ?

**Comment by maxandersen** [comment]
oh i get it now (Sorry for being slow) - you are asking for ANOTHER feature of just not touching dot files. that is different feature and i'm fine to entertain it but that should be a separate issue.

**Comment by quintesse** [comment]
I still don't get it. Isn't that the same as simply _not_ running `jbang app setup`? That way _you_ decide how you want to set up your environment.

**Comment by maxandersen** [comment]
> I still don't get it. Isn't that the same as simply _not_ running `jbang app setup`? That way _you_ decide how you want to set up your environment.

you are probably right but lets take that on #966
