### ISSUE TITLE
--javaagent with jolokia-jvm.jar doesn't work

### ISSUE THREAD

**Issue by tadayosi** [jbangdev/jbang#931]
I am sure jolokia-jvm.jar is a valid java agent but why doesn't this work?
```
$ jbang run --javaagent=org.jolokia:jolokia-jvm:1.6.2 hello.java
Failed to find Premain-Class manifest attribute in /home/tasato/.m2/repository/org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

hello.java:
```java
///usr/bin/env jbang "$0" "$@" ; exit $?
// //DEPS <dependency1> <dependency2>

import static java.lang.System.*;

public class hello {

    public static void main(String... args) throws Exception {
        out.println("Hello World");
        Thread.sleep(60000);
    }
}
```

**Comment by quintesse** [comment]
@tadayosi this might be related to: https://github.com/rhuss/jolokia/issues/128

**Comment by tadayosi** [comment]
@quintesse Yes, you're right. Thanks!  So this works:
```
jbang run --javaagent=https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar hello.java
```
The only thing I miss is the usage of GAV form for the jolokia-agent.jar but it's a problem of jolokia.
Thanks again!

**Comment by maxandersen** [comment]
`jbang run --javaagent=org.jolokia:jolokia-jvm:1.6.2:agent hello.java` works if you prefer GAV syntax :)

**Comment by tadayosi** [comment]
Yes... I thought there should be something like this. It's even more awesome!!! Thanks!
