### ISSUE TITLE
Dead links in dependencies documentation

### ISSUE THREAD

**Issue by lukaseder** [jbangdev/jbang#933]
At the bottom of:
https://www.jbang.dev/documentation/guide/latest/dependencies.html

There are two links:

> See [examples/jfx.java](https://www.jbang.dev/documentation/guide/latest/examples/jfx.java) and [examples/jfxtiles.java](https://www.jbang.dev/documentation/guide/latest/examples/jfxtiles.java) for examples of this.

... which don't work anymore

**Comment by lukaseder** [comment]
I didn't check other links, there might be more examples, in case stuff has been moved, of course...

**Comment by maxandersen** [comment]
thanks! was missed when moving examples out. 

@all-contributors please add @lukaseder  for docs
