### ISSUE TITLE
Move CLI to proper command structure

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#94]
Right now there are a variety of actions the jbang command is capable of performing by passing flags on the command line. But this leads to a situation where you can have combinations of flags that don't really make a lot of sense.

It would be nice to move to a proper command structure where each action would be its own (sub) command of the jbang main command. Eg. `jbang edit` vs `jbang --edit` and `jbang alias remove` instead of `jbang --remove-alias`.

The only special case we have to consider is the most often used one where the user just wants to run some code. The requirement is that this should still be possible without having to use a command (eg. `run`) by using some kind of shorthand feature. (eg. `jbang path/to/file.java` and `jbang run path/to/file.java` would be considered equivalent)

Exceptions to this are allowed to resolve ambiguities (eg. trying to execute a file called "run" by typing `jbang run`) in which case requiring the command is considered okay (eg, you'd have to type `jbang run run`).

Suggested commands:

 - **jbang** *[-d] [-Dkey=value]... [-o] <path|url|alias>*
 - **jbang run** *[-d] [-Dkey=value]... [-o] <path|url|alias>*
 - **jbang init** *<path|url|alias>*
 - **jbang edit** *[--live[=< editor >]] <path|url|alias>*
 - **jbang alias add** *<name> <path|url>*
 - **jbang alias remove** *<name>*
 - **jbang alias list**
 - **jbang clear-cache** (cache clear?)
 - **jbang completion**
 - **jbang version**

**Comment by maxandersen** [comment]
the one "combination" command I use constantly are `jbang --init=cli --edit-live=idea <path>`

wondering how to best do this in this structure ?

**Comment by maxandersen** [comment]
maybe allow `jbang init --kind=cli --edit-live=idea <path>` while still having `jbang edit ...` ?

**Comment by quintesse** [comment]
Or one, yet to be named, command that can do both, a bit like it is now, eg. `jbang xxxx --init=cli --edit-live=code <path>`. Possible idea for the name `project`, `file`, `script`. Something sufficiently vague :-)
