### ISSUE TITLE
documentation add alias sample is incorrect

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#943]
Page https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html indicates:

`jbang alias add hello https://github.com/jbangdev/jbang-examples/blob/HEAD/examples/helloworld.java`

which gives the following error:

```
pyfourmond@ron-wood:~$ jbang alias add hello https://github.com/jbangdev/jbang-examples/blob/HEAD/examples/helloworld.java
[jbang] [ERROR] Script or alias could not be found or read: 'hello'
[jbang] Run with --verbose for more details
```
The way to set alias name on the command line has changed since then.

**Comment by quintesse** [comment]
Indeed, that seems to use the old syntax. It should be `jbang alias add --name hello https://github.com/jbangdev/jbang-examples/blob/HEAD/examples/helloworld.java` .
