### ISSUE TITLE
Exemple "classpath_example.java"  needs edition to work

### ISSUE THREAD

**Issue by tivrfoa** [jbangdev/jbang#95]
Hi,

I think ideally one could only copy and paste an example to work, but the "classpath_example.java" example needs edition in order to work.

The problem happens in this line:
`//DEPS log4j:log4j:1.2.17 (1)`

"(1)" must be removed.

So I would either place the comment direct on the code:

```
// - DEPS has to be start of line and can be one or more space separated dependencies.
//DEPS log4j:log4j:1.2.17
```

or move the number to the line above:

```
// (1)
//DEPS log4j:log4j:1.2.17
```

**Comment by maxandersen** [comment]
missed this. what file is it you see this? https://github.com/jbangdev/jbang/blob/master/examples/classpath_example.java#L3 does not have the marker.

**Comment by tivrfoa** [comment]
> missed this. what file is it you see this? https://github.com/jbangdev/jbang/blob/master/examples/classpath_example.java#L3 does not have the marker.

https://github.com/jbangdev/jbang/blame/master/readme.adoc#L397

**Comment by maxandersen** [comment]
gotcha! fixed.
