### ISSUE TITLE
add option to have jbang ignore dot files

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#967]
as discussed in #930 it could be interested for those "crazies" ( 🧙 )who like absolute clean home dir and not using standard files to have an option like `--ignore-dot-files` or even just JBANG_IGNORE_DOT_FILES=true to have jbang not try and be smart about .zshrc/.bashrc etc.

**Comment by quintesse** [comment]
I don't understand this option. Isn't running `jbang app setup --ignore-dot-files` not the same as not running it at all?

**Comment by maxandersen** [comment]
you are right :)
