### ISSUE TITLE
add --alias option in jbang app install

### ISSUE THREAD

**Issue by ia3andy** [jbangdev/jbang#970]
It would be nice to be able to do `jbang app install --fresh --force --alias q quarkus@quarkusio`

The goal would be to have `q` as an alias of `quarkus` without replacing it (`--name q` is replacing it)

**Comment by maxandersen** [comment]
Alias are not possible without modifying startup scripts and doesn't work on All platforms. 

Thus I'm tempted to say this is left to the user to setup whatever Alias mechanism he uses.

**Comment by quintesse** [comment]
We could perhaps turn those aliases in symlinks to the main one. It would make uninstalling somewhat harder though. (I'm not sure how easy Java makes it to figure out the target of a symlink)

**Comment by maxandersen** [comment]
symlinks are OS specific too ... also uninstalling becomes tricky. not a fan we do this.

**Comment by quintesse** [comment]
I tend to agree. We'd be inching more and more into the territory of what a user's shell already provides. It's like asking the `git` developers to add an option so you can use `g`.
