### ISSUE TITLE
Found Invalid Gradle JVM Configuration error in IntelliJ IDEA 2021.2

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang#971]
When opening a JBang script with the following headers:
```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS info.picocli:picocli:4.6.1
//DEPS io.quarkus:quarkus-devtools-registry-client:2.1.0.Final
//DEPS org.eclipse.jgit:org.eclipse.jgit:5.12.0.202106070339-r
//JAVA_OPTIONS "-Djava.util.logging.SimpleFormatter.format=%1$s [%4$s] %5$s%6$s%n"
//JAVA 11
```

The following error is displayed in IDEA: 

![image](https://user-images.githubusercontent.com/54133/127495537-02f091ff-8c36-4d9d-849e-27dcdc670197.png)

This is the command I used: `jbang edit --open=idea .github/workflows/deploy.java`

**Comment by maxandersen** [comment]
We don't modify gradle settyings for IntelliJ. Got any graalvm plugin Installed that ?

**Comment by gastaldi** [comment]
Not that I am aware of.

**Comment by maxandersen** [comment]
What does the gear icon let you do ? Would be good to know what kind of jdk IntelliJ assumes needs to be a graalvm...

**Comment by gastaldi** [comment]
I cleaned up the `~/.jbang/cache` folder and the warning is no longer shown. Probably some glitch during the project generation. I'll close it and reopen if the problem reappears
