### ISSUE TITLE
Add runtime options for aliases

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#975]
It would be a very useful feature to be able to define runtime options for aliases, eg. options that set memory limits.

This would mean adding a new section to the jbang-catalog.json file, eg:

```
{
  "aliases": {
    "hello": {
      "script-ref": "hello@quintesse",
      "java-options": [
        "-showversion"
      ]   
    }   
  }
}
```

Edit: renamed `runtime-options` to `java-options`

**Comment by maxandersen** [comment]
I was kinda thinking like jbang arguments but i kinda like This approach to as then it's more explicit. 

But how about we make it a set Keys Matching (Long form) arguments to jbang so they align?

Ie. In This case it would be "java-options" matching //DEPS JAVA_OPTIONS ?

Also - realising we need to figure what would semantics be for when flags overlaps with whats inside .java and whats on command line ?

**Comment by quintesse** [comment]
Not sure what you mean by:

> But how about we make it a set Keys Matching (Long form) arguments to jbang so they align?

Will change the name to `java-options`, because you're right that's the public-facing name in the source file. And this new key should match that.

Semantics: IMO it should be: _cli_ overrides _alias_ overrides _source_

**Comment by maxandersen** [comment]
I mean - this shouldn't be limited to just java options in future. Could also use it to add deps, setup agents etc.

**Comment by quintesse** [comment]
Sure, but then we just add more keys, right? I mean it already has `arguments` and `properties`, both of which match things on the CLI.

**Comment by maxandersen** [comment]
Yeah. I was just thinking to generalize it I guess we can just as well add them incrementally and deal with differences/similarités as they appear.

**Comment by quintesse** [comment]
I updated the PR with your requested change, some fixes and a test.
