### ISSUE TITLE
`jbang init` failing if script name has not a valid Java class name

### ISSUE THREAD

**Issue by sebastienblanc** [jbangdev/jbang#984]
with v 0.70
`jbang init --template=qcli kubectl-august ` is failing : 
`[jbang] [ERROR] 'kubectl-august' is not a valid class name in java. Remove the special characters`

If I remove the --template parameter it's working. 

it was working with 0.62.

**Comment by quintesse** [comment]
@maxandersen AFAICS you implemented this on purpose like this, the `TestInit` has specific tests for these situations:

- `jbang init invalid-name.java` this is okay
- `jbang init valid-name`  this isn't

The logic in the code and the tests seem to be that when you give an extension the name will be taken as explicit, while an extension-less name can be processed (ie kebab names will be converted to camel-case).

We can change this of course but I'm guessing you had a specific reason for implementing it like this?

**Comment by quintesse** [comment]
Wait, I see that the original issue doesn't have a `.java` extension either. In that case it just seems to work fine in 0.79. Perhaps you can update and confirm @sebastienblanc ?
