### ISSUE TITLE
`jbang version --update` often doesn't work

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#990]
This happens when a previous version is in the cache (the downloads have the same name).

A workaround is to add `--fresh`.

Possible solutions are to just implicitly add `--fresh` or knowing the version to upgrade to we could specifically download that version.

**Comment by maxandersen** [comment]
it should run with fresh explicitly enabled imo.

**Comment by quintesse** [comment]
Yes, at the point where we do the download we've actually lost the version information so not taking the cache into account is the simplest solution.
