### ISSUE TITLE
jbang edit should open editor by default

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#993]
This is a breaking and possibly controversial change but I constantly find two things about the edit command:

1) users don't realize what it does as it just prints out folder name by default
2) I have to constantly type out `jbang edit --open test.java` when it could just be `jbang edit test.java`

I've been thinking for a long time we should instead make `jbang edit xyz.java` simply just open editor (if not defined will ask to install vscodium) and if you don't want to open and work as before you do jbang edit --no-open xyz.java`

`jbang edit --open=idea xyz.java` will still work and so will `JBANG_EDITOR=idea jbang edit xyz.java`

This is "less" linux like but I feel it is a better modern default behavior.

**Comment by maxandersen** [comment]
another advantage is that for windows command.exe users it will be more natural.

**Comment by quintesse** [comment]
I think it's a better default, yes. I've never used the non-open version, whenever I did it was because I had accidentally left out the open flag. 👍
