### ISSUE TITLE
Java 17, 18 + Choice of vendor

### ISSUE THREAD

**Issue by aghasemi** [jbangdev/jbang#998]
Hi,

May I ask, if there are plans to add Java 17 (18) support? Does it depend on when they will be available on Adoptium website?

Also related, it may be nice and useful to be able to choose the JVM vendor (e.g. between AdoptOpenJDk OpenJ9 vs HotSpot, SAP Machine, ...).

Thanks
Best

**Comment by quintesse** [comment]
That does indeed depend on the moment it will be available on the Adoptium website.

And vendor selection is definitely something we're thinking about but it won't be easy so that might take a while (if ever).
There's already an issue for that: #316, so I'll be closing this one.

**Comment by maxandersen** [comment]
As @quintesse said we are currently dependent on adoptjdk / adoptium to support automatic download of java 17. 

Until then I recommend you use sdkman or similar. That would also be the way to get early builds support.
